### ISSUE TITLE
Inline Datepicker

### ISSUE THREAD

**Issue by brandenwagner** [kekeh/mydatepicker#10]
How do i make this inline? (always visible)?

**Comment by kekeh** [comment]
Inline is not supported. It requires code changes quite many places to support it inline.

**Comment by kekeh** [comment]
But you can try to do it :-)

**Comment by PardeepJain** [comment]
@brandenwagner ,

Use this datepicker with interactive desgin and to make it inline use "showTextBox: false" , see here live demo

https://github.com/MrPardeep/Angular2-DatePicker/

**Comment by kekeh** [comment]
I added option **"inline": true|false**

Sample app contains an example of inline mode. 
1. Fork and clone this repo
2. npm install
3. Open a terminal and type "npm start"
4. Open "http://localhost:5000" to browser

**Comment by bakoserge** [comment]
Brilliant job. keep it up.
