### ISSUE TITLE
How to disable user manual entry, should select only from date picker.

### ISSUE THREAD

**Issue by subhani1249** [kekeh/mydatepicker#100]

**Comment by kekeh** [comment]
Do you mean that selected date field should not be editable? It is now input box and you cannot do it non editable. Should I add a new option?

**Comment by kekeh** [comment]
@subhani1249 

I added new option **editableDateField** which default is **true**. Set it to **false** in **options** and input box is not editable.

New version of the component is: 1.0.23

**Comment by subhani1249** [comment]
Thank you
