### ISSUE TITLE
Icon font's not showing

### ISSUE THREAD

**Issue by webtrix** [kekeh/mydatepicker#102]
Hi,

Is it possible to supply the icon-font you're using in your component? I'm getting nice square icons, instead of the actual icons.

**Comment by kekeh** [comment]
Sure. If you have better fonts you can create a pull request and I will merge the pull request?

Now icons are defined here: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.css

starting from line 335

**Comment by webtrix** [comment]
It's not that I don't like the icons, they just don't show. But I think it has something to do with my webpack config, I see you have a whole string instead of a file that's being loaded. Probably need to make some changes in my config so this works.

**Comment by kekeh** [comment]
You can try to override those font styles: https://github.com/kekeh/mydatepicker#change-styles-of-the-component

First you have to create base64 string from the fonts.

**Comment by webtrix** [comment]
Don't really solves my problem, but I changed the component HTML so it uses Awesome font, and that works well. But thx anyway!

**Comment by JosephSKh** [comment]
@maartentibau how did you change the template? I'm looking for the HTMLs but I can't find them.
@kekeh please support.

Thank you,

**Comment by maartentibau** [comment]
@JosephSKh I've just downloaded the source code and created a new module on my project. That way you can alter the source HTML. Not the optimal solution tbh, but it did the trick for me.

**Comment by kekeh** [comment]
You can also try this new component: https://github.com/kekeh/ngx-mydatepicker
Demo with bootstrap input box and icons: https://kekeh.github.io/ngx-mydatepicker

You can set own styles to the input box, clear and calendar icons.

If you want to use mydatepicker here is how you can create own version of the component: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by JosephSKh** [comment]
never-mind I knew the code why they weren't showing,, thank u :)
Thank you for the fast reply ! :)

**Comment by brian-lai-asynchrony** [comment]
@JosephSKh and @maartentibau 

What were the causes of your icons not showing? I seem to be getting the square icons as well.

**Comment by JosephSKh** [comment]
@brian-lai-asynchrony 
add this to your component

```
import { ViewEncapsulation } from '@angular/core';
@Component({
  encapsulation: ViewEncapsulation.None
})
```
not sure if that's the right approach or not but it worked for me after doing so

**Comment by brian-lai-asynchrony** [comment]
@JosephSKh I already had that in my component so that's not the issue... Everything seems to be working fine except the left and right arrows and calendar icons are just showing up as blank squares.
![calendar](https://cloud.githubusercontent.com/assets/23217128/23873013/2a56d8f6-07f6-11e7-84a8-31ce69d95d00.png)

**Comment by JosephSKh** [comment]
@brian-lai-asynchrony .. make sure nth is overriding the font and make sure the fonts file is imported

**Comment by brian-lai-asynchrony** [comment]
@JosephSKh Thanks for the quick replies. Which fonts file are you referring to? I installed everything through npm and the only thing I see in the node_modules/mydatepicker folder that relates to fonts is the FONT-LICENSE file. I don't see any css files.

**Comment by JosephSKh** [comment]
@brian-lai-asynchrony u r welcome dude, I don't have access to the code right now .. if u can wait till tomorrow I can check what did I do and tell you

**Comment by brian-lai-asynchrony** [comment]
@JosephSKh Okay thank you - I'm still running into the icon issue so if you can help me out tomorrow that would be great.

**Comment by JosephSKh** [comment]
@brian-lai-asynchrony 
Add this to your `styles.css`
`.mydp .icon:before {
    font-family: mydatepicker !important;
}`

**Comment by brian-lai-asynchrony** [comment]
@JosephSKh That fixed it! Thank you so much for your help, it is greatly appreciated.

@kekeh Perhaps this should be put in the readme or documented somewhere.

**Comment by kekeh** [comment]
@brian-lai-asynchrony 

You can now try version 1.7.7 and without 

.mydp .icon:before { font-family: mydatepicker !important; }

Probably it is working now?

**Comment by JosephSKh** [comment]
@brian-lai-asynchrony Welcome man :)

**Comment by Tataraovoleti** [comment]
Hi Kekey,
i m getting square boxes instead of icons. We have Content security policy enabled. 

Browser is throwing fallowing error.

Refused to load the font 'data:application/octet-stream;base64,AAE
Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Is there any way to load font icons

**Comment by kekeh** [comment]
Hi @Tataraovoleti 

Fonts are embedded to the css file and they are base64 encoded. If you want to do It other way you have to do code changes and create own version of the component. If you are willing to create own version check readme on how to create own version of the component.

**Comment by pavans518** [comment]
Hi,
I am unable to get icons in the date picker

**Comment by pavans518** [comment]
Hi @JosephSKh,
Can you share me the font icons files for the date picker

Thanks
