### ISSUE TITLE
Support date object input

### ISSUE THREAD

**Issue by cmkramer** [kekeh/mydatepicker#105]
It would be very helpful if the directive would accept a Date object as an input instead of a custom object with year, month and day fields. The custom object forces someone to create their own converters from and to a standard Date object. Considering all the lack of null checks in functions such as parseDatePartNumber, a lot of unexpected exceptions occur due to need for tricky conversions.

So the request is:
* Accept a Date object as an input instead of an IMyDate
* Provide a Date object as an output instead of an IMyDate

**Comment by kekeh** [comment]
The **dateChanged** callback contain one extra parameter **jsdate** which is Javascript date object from the selected date. Otherwise **IMyDate** object is used in API.

More info from here: https://github.com/kekeh/mydatepicker#datechanged-callback

New version of the component is: 1.0.29

**Comment by alalonde** [comment]
This answers his first request, but not his second.  On my very first interaction with this library i ran into this unexpected behavior.
