### ISSUE TITLE
Allow providing selDate as a Date object

### ISSUE THREAD

**Issue by cmkramer** [kekeh/mydatepicker#106]
Currently the selDate expects one to provide the date in the configured locale format. This enforces a developer to either write their own locale converters and layers to ensure it can handle the configured locale, or it forces them to hardcode locale parsing in their own code even though the picker itself provides dynamic locale formats.

Allowing one to provide selDate as a Date object (see #105) or else as an IMyDate would remove the need for the programmer to worry about a locale setting.

**Comment by kekeh** [comment]
Now type of **selDate** attribute can be a **string** as earlier or **IMyDate** object for example: 
```javascript
{year: 2016, month: 12, day: 6}
```
More info from here: https://github.com/kekeh/mydatepicker#seldate-attribute

New version of the component is: 1.0.29
