### ISSUE TITLE
Dynamically loaded date causes nullpointer on selDate

### ISSUE THREAD

**Issue by cmkramer** [kekeh/mydatepicker#107]
Becase parseDatePartNumber does not check for null on the supplied dateString, it ends up throwing a nullpointer when an uninitialized datestring is passed. It tends to happen that date information is loaded asynchronously, causing the supplied selDate variable to not have been set during the initial render.

Suggestion: Please allow null or undefined to be passed and considered as a valid input. As it equals no input, it should be accepted without causing the directive to crash on input pattern validation.

**Comment by kekeh** [comment]
Now **empty string**, **null**, **undefined** or **{}** are valid values to the **selDate** attribute.

New version of the component is: 1.0.29.
