### ISSUE TITLE
Date picker width issue

### ISSUE THREAD

**Issue by subhani1249** [kekeh/mydatepicker#109]
![datepicker css](https://cloud.githubusercontent.com/assets/10893928/20959770/c3d3f5b4-bc82-11e6-84cc-8a15e5f89406.png)

**Comment by kekeh** [comment]
@subhani1249 

**width** is one option of mydatepicker. Have you copied options from the sampleapp? There the value **260px** is used. If you remove the **width** option the default width is **100%**.

https://github.com/kekeh/mydatepicker#options-attribute

**Comment by subhani1249** [comment]
ok , thankyou
