### ISSUE TITLE
Can't get the demo to run

### ISSUE THREAD

**Issue by chriscurnow** [kekeh/mydatepicker#11]
I just downloaded your demo (forked and cloned as per your instructions) and ran npm install, npm run tsc then npm start.

The component doesn't load, I get the following in the console:

`Error: execute
	invoke@http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:332:34
	run@http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:227:50
	http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:576:61
	invokeTask@http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:365:43
	runTask@http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:263:58
	drainMicroTaskQueue@http://127.0.0.1:60064/node_modules/angular2/bundles/angular2-polyfills.js:482:43
	promiseReactionJob@[native code]
	Error loading http://127.0.0.1:60064/src/app/sampleapp.js`

Any ideas about what I might be doing wrong?

**Comment by kekeh** [comment]
Now you can run example application. Take pull from repo and run npm install.

**Comment by chriscurnow** [comment]
Thanks for such a prompt response – very impressive.

**Comment by chriscurnow** [comment]
And, of course, it works:)
