### ISSUE TITLE
MyDatePicker is not working with IE11

### ISSUE THREAD

**Issue by ssashok10** [kekeh/mydatepicker#110]
I am using "mydatepicker" in a Angular2 application and it works very well on Chrome browsers. However, when i choose a date from IE11, the values become something like "NaN/03/7" which is invalid.  Is it a known issue with this control?

**Comment by kekeh** [comment]
Try here with IE11: http://kekeh.github.io/mydatepicker/

It is this application: https://github.com/kekeh/mydatepicker/tree/gh-pages

Probably you need to add core-js or es6-shim packages to your application. Check configuration from the link above.

**Comment by ssashok10** [comment]
I do have the below entries in my package.json

```
    "core-js": "^2.4.1",
    "es6-shim": "~0.35.1",
```

I have noticed one more issue as well. The date controls shows the days till 42. The same control shows the days correctly till 31 for this month in Chrome browser.

**Comment by kekeh** [comment]
In my test it works well with IE11. I am not able to reproduce this issue here: http://kekeh.github.io/mydatepicker/

Are you able to reproduce the issue in the link above?

**Comment by ssashok10** [comment]
The sample project that you have created is exactly similar to mine. However, i am not sure why the components are behaving differently for me. I upgraded the component version from 1.0.2 to 1.0.34 and now the initial date looks like "0-1/0-1/-1" instead of showing the current date ( in IE11 as well as Chrome). 

This is how i configured the "mydatepicker" control,

I added the below on my TS file,
```
    myDatePickerOptions = {
        todayBtnTxt: 'Today',
        dateFormat: 'mm/dd/yyyy',
        firstDayOfWeek: 'mo',
        sunHighlight: true,
        height: '34px',
        width: '100%',
        inline: false,
        selectionTxtFontSize: '15px',
        componentDisabled: false
    };
```

startDate: string = new Date().toLocaleString().substring(0, new Date().toLocaleString().indexOf(' ') - 1);

Below is part of my HTML,
```
<my-date-picker id="startDate" [options]="startDatePickerOptions" [selDate]="startDate"
                                            (dateChanged)="onStartDateChanged($event)"></my-date-picker>
```

Is there anything that i am missing on the implementation?

**Comment by kekeh** [comment]
In version 1.0.34 you can also set **selDate** value as **IMyDate** object. Try that:
```javascript
startDate: Object = {};

constructor() {
    let date = new Date();
    this.startDate = {year:  date.getFullYear(), month:  date.getMonth() + 1, day:  date.getDate()};
}
```

Above sets today to initial date value. HTML seems to be ok.

**Comment by ssashok10** [comment]
Hello,
    I have changed the "selDate" variable from string to object and it fixed all the issues that i went through. Thanks a lot for your immediate responses.
