### ISSUE TITLE
accessibility issues

### ISSUE THREAD

**Issue by martyjg** [kekeh/mydatepicker#111]
A few accessibility issues I've noticed with the markup for mydatepicker.

A scope attribute (e.g. scope="col") needs to be added to the weekday heading (".weekdaytitle")
[https://dequeuniversity.com/rules/axe/1.1/data-table](url)

A label (even if aria hidden) for the .selection input
[https://dequeuniversity.com/rules/axe/1.1/label](url)

A name/label is needed for the . btnpicker button
[https://dequeuniversity.com/rules/axe/1.1/button-name](url)

**Comment by kekeh** [comment]
Thanks. I merged pull request. You can verify here: http://kekeh.github.io/mydatepicker/

New version of the component is: 1.0.36.
