### ISSUE TITLE
displaying month issue

### ISSUE THREAD

**Issue by chinapoopoo** [kekeh/mydatepicker#112]
When I select next year's day of January (calendar is displaying December of this year),
then displayed day is for example 2016-12-02 - 2016-13-05 not 2016-12-02 - 2017-01-05
please check this issue
thanks a lot :)

**Comment by kekeh** [comment]
Is this **mydaterangepicker** issue?

In mydapicker if selecting previous month day from the selector. It only switch calendar view to previous month. It works similar way if selecting next month day from the selector but it switch to next month.

**Comment by kekeh** [comment]
I fixed similar bug from **mydaterangepicker**. You can verify here: https://kekeh.github.io/mydaterangepicker/

New version of the component is 1.0.8.

Can you close this issue if you see it is fixed.

**Comment by chinapoopoo** [comment]
It works!! thanks a lot :)
