### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by lakerko** [kekeh/mydatepicker#12]
Hi, I've never done this before so I apologize if I'm doing something wrong. I use this datepicker but it's substantially changed, although not in calculating the date and such.
I've encountered bug with the way you are detecting the dpos, mpos and ypos.
If the day or month is smaller than 10, then the whole date string is shorter and in substringing it you'll get wrong data. Now at the beginning of the month the whole date picker stopped working for me.

My fix was: (it's in the ngOnChanges in the if(this.selectionDayTxt !== '') branch)
```javascript
            let day:string = this.selectionDayTxt.substring(dpos, dpos + 2);
            if(day.indexOf('.') !== -1 || day.length < 2){
                mpos--;
                ypos--;
            }
            
            let month:string = this.selectionDayTxt.substring(mpos, mpos + 2);
            if(month.indexOf('.') !== -1 || month.length < 2){
                ypos--;
            }
```

You can see what it does. If the substring of the day or month contains dot, it means that the next substring will be corrupted. By this you set the positions for the substring to the correct value.

**Comment by kekeh** [comment]
Date format is for example "dd.mm.yyyy" which means that the day and and the month are always two digit. For example "06.04.2016". If you put "6.4.2016" then you have problem in ngOnChanges function.

**Comment by lakerko** [comment]
I have the same ngOnChanges as in the original code. and I do receive  "6.4.2016" instead of "06.04.2016" and I have the same options on input. That's why I thought that this component is made without the leading zeroes. At first I wanted to add this but I've come up with this easier solution.

I don't know why I'm getting the wrong format:/

Sorry for messing up your issue section. I thought it was a bug.

**Comment by kekeh** [comment]
No problem.
