### ISSUE TITLE
Incorrect date highlighted

### ISSUE THREAD

**Issue by raymondboswel** [kekeh/mydatepicker#123]
The date picker works really well, except for one visual issue. The date highlighted is one day before the date that was selected. I'm not sure if this is a general issue or if I'm doing something wrong. Please let me know. Thanks!

![datepicker](https://cloud.githubusercontent.com/assets/4745321/21419508/b42246de-c830-11e6-87bc-2ce7b9d8b884.png)

**Comment by kekeh** [comment]
I have not seen this kind of error before. Can you reproduce issue here: http://kekeh.github.io/mydatepicker/

It would be useful to see you date picker **options** and what the **dateChanged** callback returns when you select the date from the selector.

Also when the date is already selected there must be cross button also visible on the left side of calendar button and I don't see cross button the image above.

**Comment by raymondboswel** [comment]
The cross is hidden with css, as it breaks my other code if the date is cleared. However, your prompt to look at the dateChanged callback guided me in the right direction. I failed to update the selDate property which was bound to the date picker. I didn't pick this up earlier as it didn't have an impact on the dates emitted from my component. Thank you for your quick response!

**Comment by kekeh** [comment]
I added option **showClearDateBtn**. Setting it to **false** in options hides the clear date button automatically. Also selected date string is centered if you use this method.

You can try option here: http://kekeh.github.io/mydatepicker/
