### ISSUE TITLE
how to setValue of this module

### ISSUE THREAD

**Issue by hosken5** [kekeh/mydatepicker#125]

**Comment by kekeh** [comment]
Set **selDate** attribute to **my-date-picker** tag like below:
```html
<my-date-picker [options]="myDatePickerOptions" [selDate]="selectedDate"  (dateChanged)="onDateChanged($event)"></my-date-picker>
```
In the typescript set value of **selectedDate** variable for example:
```javascript
private selectedDate:Object = {};

constructor() {
  this.selectedDate = {year: 2016, month: 12, day: 26};
}
```

**Comment by hosken5** [comment]
thx,but should i use two way binding method which is very common in angular2 ?


原始邮件
发件人:kekehnotifications@github.com
收件人:kekeh/mydatepickermydatepicker@noreply.github.com
抄送:洪鹏飞hongpengfei@yimei180.com; Authorauthor@noreply.github.com
发送时间:2016年12月26日(周一) 15:33
主题:Re: [kekeh/mydatepicker] how to setValue of this module (#125)


Set selDate attribute to my-date-picker tag like below:
my-date-picker [options]="myDatePickerOptions" [selDate]="selectedDate" (dateChanged)="onDateChanged($event)"/my-date-picker
In the typescript set value of selectedDate variable for example:
private selectedDate:Object = {}; constructor() { this.selectedDate = {year: 2016, month: 12, day: 26}; }

**Comment by kekeh** [comment]
Not with the **selDate** attribute. Purpose of the attribute is set only initial date.

Date picker uses **callbacks** in communication from the date picker to the host application. When you select a date the **dateChanged** callback is called which inform host application that user selected the date. Parameter contain the details of the date. You need to implement that kind of callback to enable communication from the date picker to host application. See example below:

```html
<my-date-picker [options]="myDatePickerOptions" [selDate]="selectedDate"  (dateChanged)="onDateChanged($event)"></my-date-picker>
```
```javascript
onDateChanged(event:any) {
   console.log('onDateChanged(): ', event.date, ' - jsdate: ', new Date(event.jsdate).toLocaleDateString(), ' - formatted: ', event.formatted, ' - epoc timestamp: ', event.epoc);
}
```
Here is a complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

**Comment by hosken5** [comment]
thanks very march ! it feels great if our date pick can implementValueAccessor interface and incorporate with angular2 reactive form


原始邮件
发件人:kekehnotifications@github.com
收件人:kekeh/mydatepickermydatepicker@noreply.github.com
抄送:洪鹏飞hongpengfei@yimei180.com; Authorauthor@noreply.github.com
发送时间:2016年12月26日(周一) 16:17
主题:Re: [kekeh/mydatepicker] how to setValue of this module (#125)


Not with the selDate attribute. Purpose of the attribute is set only initial date.
Date picker uses callbacks in communication from the date picker to the host application. When you select a date the dateChanged callback is called which inform host application that user selected the date. Parameter contain the details of the date. You need to implement that kind of callback to enable communication from the date picker to host application. See example below:
my-date-picker [options]="myDatePickerOptions" [selDate]="selectedDate" (dateChanged)="onDateChanged($event)"/my-date-picker
onDateChanged(event:any) { console.log('onDateChanged(): ', event.date, ' - jsdate: ', new Date(event.jsdate).toLocaleDateString(), ' - formatted: ', event.formatted, ' - epoc timestamp: ', event.epoc); }
Here is a complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

**Comment by kekeh** [comment]
Check this issue: https://github.com/kekeh/mydatepicker/issues/49
