### ISSUE TITLE
Disabling/Enabling the dates in a specific range

### ISSUE THREAD

**Issue by prashobh-k** [kekeh/mydatepicker#127]
how to use both disableSince and disableUntil at both at the same time because when i am try to use both the entire dates are getting disabled.

**Comment by kekeh** [comment]
- If you want to disable all dates just set disableUntil = {year: 9999, month: 12, day: 31}
- If you want enable all dates just set disableUntil = {};

Here is an example how to do it dynamically: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-inline/sample-date-picker-inline.ts

But there is also option **componentDisabled** which disables whole component and user is not able open the selector and select a date. Check from here how it works: http://kekeh.github.io/mydatepicker/#normalmode

select **Disable component** checkbox and component is disabled.

**Comment by prashobh-k** [comment]
actually my requirement  i should be able to select the starting date of disabling but here it is disabling from the starting date of the calendar itself.

**Comment by prashobh-k** [comment]
and thank you for responding so fast :)

**Comment by kekeh** [comment]
When the date is selected the **dateChanged** callback is called. Readme: https://github.com/kekeh/mydatepicker#datechanged-callback

Implement that function and inside the function set disableSince = event.date
```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)"></my-date-picker>
```
```javascript
onDateChanged(event:any) {
  this.myDatePickerOptions.disableSince = event.date;
}
```

it disables forward from the selected date.

**Comment by prashobh-k** [comment]
i hope you are not getting exact requirement. its like i want to **disable** all  the date **in between** 15 dec to 29 dec .

**Comment by prashobh-k** [comment]
i have one more requirement in my project, i have to make the the date field mandatory which will be inside a form which is not working with the selector tag which you have created, i have one suggestion that if you make your my-date-picker directive as attribute directive so that i can put that in a input element and even i can do two-way binding with it actually it will be useful for everyone across the world who want a angular2 datepicker because many of the time the date picker has to be validated.


example:-              
`<input type="text"  class="i form-control" readonly  **[(ngModel)]="dateOfIssue"**   **ngbDatepicker**    (click)="issue.toggle()">`

this is a datepicker from ngbdatepicker   [https://ng-bootstrap.github.io/#/components/datepicker](url)

**Comment by kekeh** [comment]
ok you need to disable a date range. It is already possible disable dates one by one using the **disableDays** option but if you need to disable big range it is not the best method. I have to implement disable date range option.

You can already make datepicker value mandatory if you use **inputFieldChanged** callback:

https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

it returns boolean value indicating is date value valid or not in the input field. Using this boolean value you can for example enable/disable submit button or do something else.

Check here how it is working: http://kekeh.github.io/mydatepicker/#normalmode

open console of the browser to see what it is returning for example when editing input field directly.

**Comment by prashobh-k** [comment]
i am using angualr2 form validation on that it inputFieldChanged() won't work.

**Comment by kekeh** [comment]
I added a new option **disableDateRange**.  Check from here how it is working: https://github.com/kekeh/mydatepicker#options-attribute

New version of the component is: 1.1.11.

**Comment by prashobh-k** [comment]
Thank you it working very fine thank you for it and such a fast response :)

**Comment by prashobh-k** [comment]
One more help can you create a attribute directive, it will be a great help for other people also if it will there then we can put it in a input field ,change the the css of the input according our needs , two-way binding will also be possible by it and most important thing we can use it with angular2 form validations.

**Comment by prashobh-k** [comment]
would you can add AOT compatibility to your datepicker.

**Comment by kekeh** [comment]
If you are using module from npm, AOT support is already added:

- https://github.com/kekeh/mydatepicker/issues/66
- https://github.com/kekeh/mydatepicker/issues/93

**Comment by prashobh-k** [comment]
thank you for your response. how to write the opposite logic for **disableDateRange** because i want to enable some dates in a range. the other option which you have given disableUntil and disableSince can't be used together its actually disable all the dates.

**Comment by kekeh** [comment]
you can also disable days one by one using the **disableDays** option. 

For example: disableDays: [{year: 2016, month: 11, day: 14}, {year: 2016, month: 1, day: 15]

**Comment by kekeh** [comment]
I added **showInputField** option which shows/hides input box. You can implement own input box and set **showInputField** to **false**. Maybe this does not solve your requirement but this is good to know.

You can try it here: http://kekeh.github.io/mydatepicker

**Comment by matq007** [comment]
Hi @kekeh I ran into similar problem. I am using two date pickers not a date-range in this example. When the first date is set in first date-picker I tried to updated the options for another datepicker (disableUntil). But after picking the first date it's not disabling until in the second date-picker.

```
datePickerOptionsTo = {
    dateFormat:           environment.DATE_FORMAT.toLowerCase(),
    sunHighlight:         false,
    showClearDateBtn:     false,
    editableDateField:    false,
    firstDayOfWeek:       'mo',
    height:               '37px',
    selectionTxtFontSize: '14px',
    disableUntil:         {}
  };
```

My callback:
```
startDate(event): void {
    if (event !== null && event.formatted !== '') {
      this.tmpFrom = event.formatted;
      this.datePickerOptionsTo.disableUntil = event.date;
      console.log(this.datePickerOptionsTo);
    }
  }

```
It's setting the other option correctly, but it's not updating the calendar. I've seen that when I pick the date in second date-picker after that it actually sets the disableUntil. If I understand correctly the [options] should be dynamic, so it should change immediately when the variable is modified. Am I doing something wrong here?

Thanks :)

**Comment by kekeh** [comment]
Now you can enable dates one by one if they are disabled. Option name is **enableDays**. It takes array of **IMyDate** objects for example: [{year: 2017, month: 1, day: 5}, {year: 2017, month: 1, day: 6}]

```ts
import {IMyOptions} from 'mydatepicker';
// other imports here...

export class MyTestApp {

    private myDatePickerOptions: IMyOptions = {
        // other options...
        
        // disable January 2017
        disableDateRange: {begin: {year: 2017, month: 1, day: 1}, end: {year: 2017, month: 1, day: 31}},
        // enable 5th and 6th dates from January 2017
        enableDays: [{year: 2017, month: 1, day: 5}, {year: 2017, month: 1, day: 6}]
    };
}
```
New version of the component is: 1.2.6.

**Comment by goelinsights** [comment]
Is there an easy way to set the disableUntil to Today?  I'm trying to use today = new Date() and it's throwing an error (and it also is if I use { year: new Date().getFullYear(), month: ...} )

**Comment by kekeh** [comment]
The **setDisableUntil()** function below set **today** to value of **disableUntil** option:

```ts
import {IMyOptions} from 'mydatepicker';
// other imports here...

export class MyTestApp {
    private myDatePickerOptions: IMyOptions = {
        // other options...
        
        disableUntil: {year: 0, month: 0, day: 0}
    };

    setDisableUntil: void {
        let d: Date = new Date()

        let copy = this.getCopyOfOptions();
        copy.disableUntil = {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
        this.myDatePickerOptions = copy;
    }

    getCopyOfOptions(): IMyOptions {
        return JSON.parse(JSON.stringify(this.myDatePickerOptions));
    }
}
```

**Comment by kekeh** [comment]
I created Attribute directive datepicker. It is own component. It is here: https://github.com/kekeh/ngx-mydatepicker

Demo is here: https://kekeh.github.io/ngx-mydatepicker

It is not well tested but you can try it now.

**Comment by Daewl** [comment]
Hello All, i have a question with same title

i am trying to achive, disable past days and allow only selectible 4 days later include today. member can only select 18,19,20 and 21th of october, tomorrow it will ve 19,20,21 and 22th of october and so on. range has to by dynamic. customer wants to allow only  orders done in four days

thanks for help.

**Comment by kekeh** [comment]
@Daewl 

I haven't tested but the following could work:

```html
<!-- define options attribute to the tag as follows -->
<my-date-picker [options]="myOptions"></my-date-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateModel} from 'mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        minYear: 1900,
        maxYear: 2200,
        disableDateRanges: [
                 {begin: {year: 1900, month: 1, day: 1}, 
                  end: {year: 2200, month: 12, day: 31}}
        ], // disable all
        enableDays: []
    }

    constructor() {}

    // Enable four dates from today
    enableDays() {
        let enableDays: Array<any> = [];
        for(let i = 0; i < 4; i++) {
             let d: date = new Date();
             d.setDate(d.getDate() + i);
             enableDays.push({
                 year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()
             });
        }

        let copy = this.getCopyOfOptions();
        copy.enableDays = enableDays;
        this.myOptions = copy;
    }

    // Returns copy of myOptions
    getCopyOfOptions(): IMyOptions {
        return JSON.parse(JSON.stringify(this.myOptions));
    }
}
```

**Comment by Daewl** [comment]
@kekeh thanks for answer. tried your tip and got  error" Cannot find name 'date'."
can you check it?
here is my code.
https://stackblitz.com/edit/angular-tqgcgr

thx

**Comment by kekeh** [comment]
If you are using **ngModel** remove the **selDate** attribute. You can set initial date with **ngModel**.

I got Access denied error in your link, but the date picker code seems to be ok.

You have to call the **enableDays()** method for example from the **ngOnInit()** method.

**Comment by Niashr** [comment]
Hi kekeh,
Is it possible to get the event on the change in month and year which is available in the calendar top right and top left corner.

Thanks in advance.

**Comment by odenypeter** [comment]
Hi Kekeh,
I have a small problem, I am able to well display the date-field, select a date and even submit to the backend. However, I have 2 date fields (start_date and end_date). My requirement is that when a user selects the start_date, the end_date calendar should display from the date entered in the start_date field with all the dates before the start_date disabled. How can I achieve this?

**Comment by kekeh** [comment]
Hi @odenypeter 

Here is an example on how to diable dates: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

other complete example: https://plnkr.co/edit/f383ob?p=preview

if you want set initial date to end date picker you can use **ngModel** and set a date value to it. Example is here: https://github.com/kekeh/mydatepicker#1-ngmodel-binding

**Comment by odenypeter** [comment]
Thanks @kekeh. This was very helpful

**Comment by asmi12** [comment]
how to disable button based on past date and time in angular7
