### ISSUE TITLE
Datepicker placeholder

### ISSUE THREAD

**Issue by Jakub41** [kekeh/mydatepicker#128]
Hello,
I would like to know if it is possible to add a placeholder, showing for example, a text or the current date. Just inside the input field like -> placeholder="..." 

Thank you :)

**Comment by kekeh** [comment]
You can control placeholder of the input using options attribute:
- Set **showDateFormatPlaceholder** option to **true** and the date format is in placeholder of the input
- Set **showDateFormatPlaceholder** option to **false** (which is default) and then you can set custom placeholder text using the **customPlaceholderTxt** option. It can be any text for example current date.

Options: https://github.com/kekeh/mydatepicker#options-attribute

**Comment by Jakub41** [comment]
Thank you for quick reply :)

**Comment by Jakub41** [comment]
Could you please show me an example of usage because I'm doing something wrong thank you:
              [options]="myDatePickerOptions"
              (dateChanged)="onDateChanged($event)"
              [showDateFormatPlaceholder]="false"
              (customPlaceholderTxt)="customPlaceholderTxt('Date')"

**Comment by kekeh** [comment]
showDateFormatPlaceholder and customPlaceholderTxt are options:
```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)"></my-date-picker>
```

```javascript
private myDatePickerOptions = {
  showDateFormatPlaceholder: false,
  customPlaceholderTxt: 'my custom placeholder...'
  // other options...
}
```

Here: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal is complete example but it does not set customPlaceholderTxt option.
