### ISSUE TITLE
how to use ngModel attribute for angular 2

### ISSUE THREAD

**Issue by githubServic** [kekeh/mydatepicker#129]
Hi,
      thanks for great datepicker. I am trying to use this in angular 2. When i use ngmodel attribute somthing like  [(ngModel)]="test". it does not work.  It does not bind to my model for example test. so when i created a record and try to edit this record, it does not prepopulate with the value i created the record with in datepicker. do you know why?

**Comment by kekeh** [comment]
ngModel is not supported. Using the following attributes you can pass data to datepicker:
- options (mandatory)
- selDate
- defaultMonth
- locale

datepicker send back data to host application using callbacks:
- dateChanged (mandatory)
- inputFieldChanged
- calendarViewChanged

Check details from here: https://github.com/kekeh/mydatepicker/blob/master/README.md

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

**Comment by kibbled** [comment]
Was this a design decision or were you just trying to keep the framework simple? I ask because you would think an Angular2 DatePicker would support model binding. Thanks

**Comment by kekeh** [comment]
I added value accessor to my-date-picker. Now **ngModel** and **formControlName** attributes are supported. Check more info from the README file.

Here is an example (run sampleapp): https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

New version of the component is: 1.2.0
