### ISSUE TITLE
Feature request: Date Picker to open on the top/bottom of field based on available space

### ISSUE THREAD

**Issue by abhibly** [kekeh/mydatepicker#131]
Hello...I have observed that the datepicker when opened always opens at the bottom of input box. I have the datepicker input box at the bottom of window but i want that to be opened at the top of input box. Is it possible to dynamically alter the popup position of the datepicker based on the available space.Thank You

**Comment by mdarif-k** [comment]
Hi Kekeh,

It is an amazing date picker, i am also facing the same as Abhibly, can you provide any solution for that.

**Comment by kekeh** [comment]
I added option **openSelectorTopOfInput**. Set it to **true** and selector opens the top of input field. It is host application responsibility to decide how to show the selector (bottom/top). You can also dynamically change the value of this option.

By default there is arrow top of selector but you can disable it by setting the **showSelectorArrow** option to **false**.

You can try it here: http://kekeh.github.io/mydatepicker

New version of the component is: 1.1.15

**Comment by sanushakya** [comment]
Can you get time picker too as Date Picker ?
