### ISSUE TITLE
Date picker  inside a for loop with ngModel is giving an error.

### ISSUE THREAD

**Issue by NayabHussain** [kekeh/mydatepicker#132]

**Comment by kekeh** [comment]
**ngModel** is not supported by **my-date-picker** tag. Using the following attributes you can pass data to datepicker:
- options (mandatory)
- selDate
- defaultMonth
- locale

datepicker send back data to the host application using **callbacks**:
- dateChanged (mandatory)
- inputFieldChanged
- calendarViewChanged

Check details from here: https://github.com/kekeh/mydatepicker/blob/master/README.md

Here (sampleapp) is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

Can you share your HTML from the place where you are using the **my-date-picker** tag?

**Comment by NayabHussain** [comment]
Thanks  I got
