### ISSUE TITLE
Date is undefined , when we try to edit the date which is already binded to HTML page.

### ISSUE THREAD

**Issue by NayabHussain** [kekeh/mydatepicker#133]
Date is undefined (0-1 undefined 17 in input field), when we try to edit the date which is already binded to HTML page, I am using [selDate]="tempdate[i]" inside for loop, tempdate is of any type

**Comment by kekeh** [comment]
what is value of template[0]

**Comment by NayabHussain** [comment]
Is there any other option instead of appending zero  if day or month is lower than 10.

**Comment by kekeh** [comment]
Use object instead of string: https://github.com/kekeh/mydatepicker#seldate-attribute  for example value of the **selDate** can be: **{year: 2017, month: 1, day: 3}** 

using object prepend zero is not needed because properties of the object are numbers.

**Comment by NayabHussain** [comment]
In form validation , If I press reset button the date picker value is not clearing.

**Comment by kekeh** [comment]
Probably you mean cross button? When you click the cross button the **dateChanged** callback is called. Check that you reset value of **selDate** attribute in the **dateChanged** callback if the cross button is clicked.
