### ISSUE TITLE
dateFormat for more than 10 characters

### ISSUE THREAD

**Issue by Manumeld** [kekeh/mydatepicker#135]
Hello,
I would like to choose currently unsupported dateFormat which is a standard for Czech formatting, which is 'dd. mm. yyyy', i.e. format with spaces after dots. Unfortunately I found that in the ValidatorService on the 13th line there is fixed length format for 10 characters for my case. It is not possible to select a date by keyboard therefore, as the validation fails.

Can you broaden the strict validation please? Or how can I go around it?

Thank you

**Comment by kekeh** [comment]
I have fixed that recently: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/services/my-date-picker.validator.service.ts

Update the latest version 1.1.12
