### ISSUE TITLE
Clear Date Picker

### ISSUE THREAD

**Issue by sud-004** [kekeh/mydatepicker#136]
Solution porposed in #134  is not helping my cause,
I want to clear the date picker on click of a "**different button**" having it's own implementation 
setting the variable binded to [selDate] of type IMDate object to null inside that "different button" implementation is not helping 
Thanks in advance

**Comment by kekeh** [comment]
As you can see from the screenshot below it is different button solution. Here is how you can run the sampleapp: https://github.com/kekeh/mydatepicker#development-of-this-component

![screenshot_2017-01-03_18-11-42](https://cloud.githubusercontent.com/assets/11028839/21613973/4e0ff404-d1e0-11e6-8ac7-80d7c019650c.png)

Clicking the **Clear Date** button clears the selected date and it is described here: https://github.com/kekeh/mydatepicker/issues/70
