### ISSUE TITLE
Selecting the same date is returning Date Format in Text Box

### ISSUE THREAD

**Issue by bighnaraj123** [kekeh/mydatepicker#141]
I am using the older version of this plugin (0.0.36) and i have done some style change thru CSS. Now its last phase in my code deployment so cant update the version.

The issue I am facing is when I select a date for the first time date is coming in the text box. When i click the calendar icon once again the there is no selected date is highlighted. THe major problem is If i select once gain the same date then in the text box Date format is populating.
Dont know what is the issue.

**Comment by kekeh** [comment]
Difficult to say what is problem.  I tested 0.0.36 version and I didn't see this kind of problem and I haven see this kind of problem earlier.

Are you using **selDate** attribute?

**Comment by bighnaraj123** [comment]
The dateFormat i have used is MM/DD/YYYY. I am showing the placeholder if the date filed is empty. I am using the selDate attribute only. and thru CSS i am changing the look as per my requirement.

**Comment by kekeh** [comment]
Probably there is some problems with **selDate** attribute.

When you set initial date with **selDate** it must be in the same format as your **dateFormat** option is. Use lowecase letters in **dateFormat** option. 

If your date format is **mm/dd/yyyy** the value of **selDate** (for example today) must be **01/07/2017**. Notice prepend zeros if month or day is lower than 10.

The **dateChanged** callback is called when you select the date. You can also set value of **selDate** attribute in **dateChanged** callback as follows:

```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)" 
[selDate]="selectedDate"></my-date-picker>
```

```javascript
// dateChanged callback
onDateChanged(event:any) {
    // your own code...

    this.selectedDate = event.formatted;
}
```
