### ISSUE TITLE
How to change the Date Format

### ISSUE THREAD

**Issue by bighnaraj123** [kekeh/mydatepicker#142]
Hi,

I want to change the date format other than the prescribed by you i.e MM/DD/YYYY. Is it possible.
Please respond.
Thanks in advance

**Comment by kekeh** [comment]
It is possible change date format using **dateFormat** option. Use lowercase letters in the dateFormat option. Change date format for exampe as follows:

```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)" ></my-date-picker>
```
```javascript
private myDatePickerOptions = {
  // Other options...
  dateFormat: 'mm/dd/yyyy'
}
```

```javascript
// dateChanged callback
onDateChanged(event:any) {
    // your own code...
}
```
