### ISSUE TITLE
Weird dates returned when using "-"

### ISSUE THREAD

**Issue by garybushey** [kekeh/mydatepicker#145]
If I set my "dateFormat" in my date picker options to be "mm-dd-yyyy" I get weird results returned whenever I select a date.   Works fine with "mm/dd/yyyy" (which is what I will use going forward)

**Comment by kekeh** [comment]
In my test the **dateFormat** "mm-dd-yyyy" is working well. What kind of result you are getting?

For example sampleapp is working if I set dateFormat to "mm-dd-yyyy" here: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-normal/sample-date-picker-normal.ts

Here is instructions on how you run the sampleapp: https://github.com/kekeh/mydatepicker#development-of-this-component

Are you using **selDate** attribute?

**Comment by garybushey** [comment]
I get results like "0-1/0-1/17" and when I open the calendar again I am in the year 17 (rather than 2017).....and I just realized that I am an idiot and have a HUGE bug in my code and it is not due to your code.  Sorry for the trouble.
