### ISSUE TITLE
[Improvement] Add options type definition

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#147]
Hi again

in order to improve code completion and build-time checking, would you consider a PR adding type definition for datepicker options? 

Very likely, that would be just an interface, defined in its own file, that gets exported as a `.d.ts` file available to package users.

Please don't hesitate to share your thought about it. Regards

**Comment by kekeh** [comment]
There already is options interface: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-options.interface.ts

**Comment by BrainCrumbz** [comment]
Cool! It would be nice to import and re-export that from main/index/root/whatever file. Ideally, a library user should be able to write:

```ts
import { IMyOptions } from 'mydatepicker';
```

and have that type available in its source code. Actually, for usage from outside the library, you could also renaming that while re-exporting, like `MyDatePickerOptions`: that would make them very related to datepicker, and would also stick with a somewhat common TS habit of *not* prefixing interfaces with `I`.

**Comment by kekeh** [comment]
Now above import is possible in version 1.2.6.
