### ISSUE TITLE
[Improvement] Move placeholder text to separate property

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#148]
When you have (at least) two datepickers with same options, you might just want to set a distinct placeholder text for each one of them.

Instead of having to define and bind two separate options hashes, one could keep the same options for both and have the placeholder text as a dedicated, bound property, similar to the `placeholder` one already used by official HTML5. 

Just as an example. the end result for HTML using the library could be something like:

```html
<!-- ... -->
<my-date-picker id="startDatePicker"
                [options]="myDatePickerOptions"
                [placeholder]="After this date"
                (dateChanged)="onStartDateChanged($event)"></my-date-picker>
<!-- ... -->
<my-date-picker id="endDatePicker"
                [options]="myDatePickerOptions"
                [placeholder]="Before this date"
                (dateChanged)="onEndDateChanged($event)"></my-date-picker>
```

The other good side effect would be that placeholder text seems to be more often a "static" information, rather than something you want to bind to, so if you just need some text you can set that in HTML, and not clutter the TS code.

In case, I could try to put up a PR within our team. What do you think about it?

**Comment by kekeh** [comment]
Now in version 1.5.2 there is own attribute to placeholder text.

More info: https://github.com/kekeh/mydatepicker/issues/177
