### ISSUE TITLE
[Improvement] Let user code set aria-label

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#150]
While working with this component, from DOM inspection it looks like `aria-label` on embedded `input` node is set to a fixed text, *"Calendar input field"*. The same happens for the two buttons, `.btnclear` and `.btnpicker`.

For accessibility reasons, it might be better to move that as some input property available to user code, and ~not set it at all~ leave the fixed one if user does not set that.

Please share your thoughts (and hope you don't mind the issue profusion, mainly PR proposals 😄  )

**Comment by kekeh** [comment]
This is done in version 1.7.6.
