### ISSUE TITLE
[Improvement] Define types of callback event args

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#152]
A number of callbacks in this component pass an "$event" argument as input: `dateChanged`, `inputFieldChanged`, `calendarViewChanged`. Code completion and compile-time checking could be improved by exporting a public definition for their respective input event arguments, instead of only resorting to docs description.

Would you consider a PR aiming to this? Cheers

**Comment by kekeh** [comment]
I added type definitions to parameter data of callbacks:

- **dateChanged**: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date-model.interface.ts
- **inputFieldChanged**: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-input-field-changed.interface.ts
- **calendarViewChanged**: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-calendar-view-changed.interface.ts

**Comment by BrainCrumbz** [comment]
Thanks, will give it a spin soon!

**Comment by BrainCrumbz** [comment]
Just nitpicking: why not make `jsdate: Date` in [IMyDateModel ](https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date-model.interface.ts)?

**Comment by kekeh** [comment]
I changed it. Version 1.2.7
