### ISSUE TITLE
Feature Request: Only enable a set of days

### ISSUE THREAD

**Issue by jhleoh** [kekeh/mydatepicker#158]
The current option of disabling selective days won't handle the case when only a set of days need to be enabled.  e.g. I'm getting 30 random dates from my service and I only want these 30 dates to be enabled.  It appears the current feature cannot handle this.  Can we have an option to only enable a given set of dates?

**Comment by kekeh** [comment]
Now you can enable dates one by one if they are disabled. Option name is **enableDays**. It takes array of **IMyDate** objects for example: [{year: 2017, month: 1, day: 5}, {year: 2017, month: 1, day: 6}]

```ts
import {IMyOptions} from 'mydatepicker';
// other imports here...

export class MyTestApp {

    private myDatePickerOptions: IMyOptions = {
        // other options...
        
        // disable January 2017
        disableDateRange: {begin: {year: 2017, month: 1, day: 1}, end: {year: 2017, month: 1, day: 31}},
        // enable 5th and 6th dates from January 2017
        enableDays: [{year: 2017, month: 1, day: 5}, {year: 2017, month: 1, day: 6}]
    };
}
```
New version of the component is: 1.2.6.
