### ISSUE TITLE
Need help with day ordering

### ISSUE THREAD

**Issue by draytond** [kekeh/mydatepicker#159]
Currently the calendar shows days starting with Monday and ending on Sunday.

Is there an option to use the format where the week starts on Sunday and ends on Saturday?

**Sun Mon Tues Wed Thu Fri Sat**

instead of the current

**Mon Tues Wed Thu Fri Sat Sun**

Thanks.

**Comment by kekeh** [comment]
It is possible. Option firstDayOfWeek. More information see README option attribute.
