### ISSUE TITLE
Select date range programatically?

### ISSUE THREAD

**Issue by craigsh** [kekeh/mydatepicker#164]
Hi 

Thanks for the great date picker!

I have a requirement where the user needs to select a week and should be able to do so by clicking any day in the week and then the whole week would show as selected.

The date range feature seems like it would work except that it requires the user to manually pick the start and end dates. 

Is there any way I can easily do this programatically as soon as they select a date - i.e. then default the range to the Monday to Sunday of the week they're chosen the date on?

**Comment by kekeh** [comment]
Not possible with the datepicker but maybe you can try this: https://github.com/kekeh/mydaterangepicker

**Comment by kekeh** [comment]
You have to do code changes to achieve this kind of functionality. Here are instructions on how to develop this component: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by bujardeari** [comment]
But how do you set the dates when the component is initialized. I would like to select the last 30 day
