### ISSUE TITLE
[Feature request] Fix build when noImplicitThis is enabled 

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#166]
When setting `"noImplicitThis": true` in *tsconfig.json*, a number of errors from code in `node_modules\mydatepicker` show up at build time. Even after setting `"skipLibCheck": true` and `"skipDefaultLibCheck": true`, errors from the library keep being shown. 

Please note that all come from `node_modules\mydatepicker\src\` directory contents, which maybe should not be part of published package in the first place. So, before looking at this, it might be worth looking at cleaning up package.

As of 1.2.6, here's the list:

```
X:\whatever\node_modules\mydatepicker\src\my-date-picker\my-date-picker.component.ts:301:21
    'this' implicitly has type 'any' because it does not have a type annotation.
X:\whatever\node_modules\mydatepicker\src\my-date-picker\my-date-picker.component.ts:301:37
    'this' implicitly has type 'any' because it does not have a type annotation.
X:\whatever\node_modules\mydatepicker\src\my-date-picker\my-date-picker.component.ts:301:55
    'this' implicitly has type 'any' because it does not have a type annotation.
```

**Comment by kekeh** [comment]
Now in version 1.3.0
```javascript
    "noImplicitThis": true
    "skipLibCheck": true
```
works.

**Comment by BrainCrumbz** [comment]
Thanks for that, will upgrade to new version in these coming days!
