### ISSUE TITLE
How to set initial date if user selects any future date by using mydatepicker

### ISSUE THREAD

**Issue by DineshChopra** [kekeh/mydatepicker#168]
Hi,

Thanks for providing great date-picker.
I have a requirement, I have some past date ('02-Jan-2017') when my component loads, Now if user click on any future date then i have to set it back with initial date '02-Jan-2017'.

I used like that : 
<my-date-picker
                                    [options]="myDatePickerOptions"
                                    [selDate]="contractDate"
                                    (dateChanged)="chooseNewContractDate ($event)"></my-date-picker>

When any date is changed then I am executing method chooseNewContractDate and checking if its a future date then I have to set it back with initial date.

function chooseNewContractDate ($event){
.....
  if(isFutureDate){
    contractDate = '02-Jan-2017' // initial value when component loads
  }
}

But its now working fine my input box of date-picker shows future date.

Can you please guide us can we implement that requirment by using date-picker.

Regards,
Dinesh Chopra

**Comment by kekeh** [comment]
You can try somthing like this:

```javascript
chooseNewContractDate(event: IMyDateModel) {
    // other code...

    this.contractDate = event.formatted;  // first set selected date to value of selDate
    if(isFutureDate) {
        setTimeout(() => {
            this.contractDate = '02-Jan-2017';  // if date was future date, set back to original date
        }, 200);
    }
 }
```

In order the datepicker to detech **selDate** changes the value must be changed. That is why set **event.formatted** to **this.contractDate** at first. Then back to original date if it was future date.

You can set timeout value suitable to you.

**Comment by DineshChopra** [comment]
Thanks for fast response :)
