### ISSUE TITLE
Feature request: Autocomplete

### ISSUE THREAD

**Issue by hhagemann1** [kekeh/mydatepicker#169]
It would a nice feature to have the possibility to enable autocomplete. Eg. when a user only enters 6 digits and leaves the input field the date will be formattet as 'yyyy-mm-dd' or the format given in options

**Comment by nusje2000** [comment]
Maybe you can add support for something like the angular2-text-mask

**Comment by kekeh** [comment]
I added new option **inputAutoFill**. By default it is **true**. It automatically adds separator of the date format and leading zeros.

New version of the component is: **1.6.19**.

**Comment by boldwade** [comment]
This appears to no longer work as the inputAutoFill is not part of the interface.
