### ISSUE TITLE
Build error Since V1.3.0 -> ERROR in MyDatePickerModule is not an NgModule

### ISSUE THREAD

**Issue by bricejulia** [kekeh/mydatepicker#172]
Hi,

I can't build my project since v1.3.0.
Here is the error : 
ERROR in MyDatePickerModule is not an NgModule

Thanks by advance.

**Comment by dfeeney-mt** [comment]
Same problem here. It worked fine with 1.0.37, but since updgrading to v1.3.0 I get ERROR in MyDatePickerModule is not an NgModule

Angular 2.4.4
Angular-CLI 1.0.0-beta-26

**Comment by kekeh** [comment]
I was able to do it (mydatepicker version 1.3.0) work with "angular-cli": "**1.0.0-beta.21**", but it failed with version "angular-cli": "**1.0.0-beta.26**".

There are similar issues: https://www.google.fi/#q=ERROR+in+Module+is+not+an+NgModule

You can use version 1.2.9 of mydatepicker as a workaround.

**Comment by dfeeney-mt** [comment]
Thanks for the quick response @kekeh. That worked for me. It compiled without error.

**Comment by bricejulia** [comment]
Thanks @kekeh. That worked for me too.

**Comment by rainstormza** [comment]
Is it possible that I can use both angular cli version 1.0.0-beta.26 and mydatepicker version 1.3.0 right now ?
@kekeh

**Comment by kekeh** [comment]
I have fixed this bug. There is a new version **1.4.0** which works with angular cli version  **1.0.0-beta.26**.
