### ISSUE TITLE
How to make a default todays date in date picker input field?

### ISSUE THREAD

**Issue by sanushakya** [kekeh/mydatepicker#174]

**Comment by kekeh** [comment]
You can use **selDate** attribute. For example the following code initializes (today) date picker:

```html
<my-date-picker [options]="myOptions" [selDate]="selDate" (dateChanged)="onDateChanged($event)"></my-date-picker>
```

```javascript
import {IMyOptions, IMyDateModel, IMyDate} from 'mydatepicker';

private selDate: IMyDate = {year: 0, month: 0, day: 0};
private myOptions: IMyOptions {
    // other options here...
    dateFormat: 'dd.mm.yyyy'
}

constructor() {
    let d: Date = new Date();
    this.selDate = {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
}

onDateChanged(event: IMyDateModel) {
    // date selected...
}
```

**Comment by phuongnguyenxtivia** [comment]
Dear @kekeh ,

I followed this instruction and unfortunately, it didn't work for me. Below is my code
Template:
`<my-date-picker name="myDate" [options]="myDatePickerOptions" formControlName="myDate" (dateChanged)="onDateChanged($event)" [selDate]="selDate"></my-date-picker>`

Component:
```
private selDate: IMyDate = {year: 0, month: 0, day: 0};
...
        this.selDate = {year: this.currentMoment.year()
                , month: this.currentMoment.month() + 1
                , day: this.currentMoment.date()};
...
    private myDatePickerOptions: IMyOptions = {
        dateFormat: 'mm/dd/yyyy',
        editableDateField: false,
        openSelectorOnInputClick: true,
        showClearDateBtn: false,
        inputValueRequired: true,
        disableUntil: { year: 1000, month: 0, day: 1 },
        disableSince: { year: 9999, month: 12, day: 31 }
    };
```

Please advise

**Comment by kekeh** [comment]
It seems to be ok. But I don't know how currentMoment works. Try that at first to see that the **selDate** attribute works:

        this.selDate = {year: 2017
                , month: 2
                , day: 9};

**Comment by phuongnguyenxtivia** [comment]
@kekeh even I tried to hard-code as you mentioned and it does not work.

**Comment by kekeh** [comment]
Probably if you are using reactive forms it overrides the value set by the **selDate** attribute. So you can remove the selDate and set initialization date as follows:
```javascript
ngOnInit() {
    let d: Date = new Date();
    this.myForm = this.formBuilder.group({
        myDate: [{date: {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()}}, Validators.required] 
    });
}
```

**Comment by phuongnguyenxtivia** [comment]
Thank you for your explanation, @kekeh. It worked as well now.

**Comment by zaindaniyal** [comment]
I created a a variable and used it to give me today's date.

In Typescript:
`  date: any = { date: {year: (new Date()).getFullYear(), month: (new Date()).getMonth() + 1, day: (new Date()).getDate()} };
`
HTML:
`<my-date-picker name="filterDate" [options]="myDatePickerOptions" [(ngModel)]="date">
            </my-date-picker>`

**Comment by navin11** [comment]
How to show date picker with particular date without setting in input box?? need advise @kekeh

**Comment by kekeh** [comment]
If you are using ngModel binding here is an example: https://github.com/kekeh/mydatepicker#1-ngmodel-binding

If you are using reactive forms check above.

**Comment by kekeh** [comment]
You can open specific month and year with the dafaultMonth attribute: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

**Comment by yuvavjrnesh** [comment]
@kekeh 
how to display user give date in my date picker using ngmodel.
it returns object object only to me when i try to display date

**Comment by kekeh** [comment]
Here is example: https://github.com/kekeh/mydatepicker/wiki/Use-ngModel

**Comment by sharmamangita** [comment]
I am using mydatepicker for showing date now I want to set date in input box for this I am using that code.

    <my-date-picker  formControlName="myDate" [(ngModel)]="task.taskDateFormatted" [options]="myDatePickerOptionsinput" (calendarToggle)="onCalendarToggle($event)"  (dateChanged)="onDateChanged($event,task._id)" >
    </my-date-picker>

When I am using one date picker its working correct and set the value. But when I am using for multiple date-picker and each have different date then its showing error message.

[(ngModel)]="task.taskDateFormatted"

This is the error message :-

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '17 Jan 2019'. Current value: '16 Jan 2019' this is screenshot:-

https://www.screencast.com/t/etEFtqyq9

Thank you

**Comment by Saiprasad2020** [comment]
@kekeh 
<my-date-picker name="myDate" [options]="myDatePickerOptions" formControlName="myDate" (dateChanged)="onDateChanged($event)" [selDate]="selDate"></my-date-picker>


It workd for me But if i used twice [selDate]="selfromdate" and [selDate]="seltodate" 

It's taking only one we can't use [selDate] twice in same form .. 
it's over riding one date with other which we are passing last date(todate) is overriding the first one (selfromdate)

So it's showing only one date which we enter last How we can override this problem
