### ISSUE TITLE
my-date-picker element has ng-valid class although inside input field has invaliddate class

### ISSUE THREAD

**Issue by arvsharm** [kekeh/mydatepicker#175]
I want to show inline help for date control but even though the date is invalid and invaliddate class is added to input field top level my-date-picker element has ng-valid class

I am trying to show the inline help with following ngIf condition

```
<div class="inline-help" *ngIf="myForm.controls['myDate'].controls['dob'].dirty && 
                    	 !myForm..controls['myDate'].controls['dob'].valid">
        				Only date in format mm/dd/yyyy can be provided
</div>
```

**Comment by kekeh** [comment]
You do it as follows:

```html
<form [formGroup]="myForm" novalidate>
    <!-- possible other components here... -->
    <my-date-picker name="reactiveFormsDate" [options]="myDatePickerOptions" formControlName="myDate"></my-date-picker>

    <p class="error" *ngIf="myForm.controls.myDate.errors">Only date in format mm/dd/yyyy can be provided</p>
</form>
```

```javascript
ngOnInit() {
        this.myForm = this.formBuilder.group({
            myDate: ['', Validators.required]   // not initial date set
        });
}
```

You can validate the date with **Validators.required** validator.

If the date is not valid in the input box the text "Only date in format mm/dd/yyyy can be provided" is shown.

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

The example contain **ngModel** and **reactive forms** example. You can also run the sampleapp to see how it works. Instruction on how to run sampleapp are here: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by arvsharm** [comment]
If I use required validator it works but my date field is not required so i can't use required Validator. Is there any other way without making field as required.

**Comment by kekeh** [comment]
You can use **inputFieldChanged** callback as follows:

```html
<form [formGroup]="myForm" novalidate>
    <!-- possible other components here... -->
    <my-date-picker name="reactiveFormsDate" [options]="myDatePickerOptions" formControlName="myDate" 
        (inputFieldChanged)="onInputFieldChanged($event)"></my-date-picker>

    <p class="error" *ngIf="!validDate">Only date in format mm/dd/yyyy can be provided</p>
</form>
```

```javascript
import {IMyOptions, IMyInputFieldChanged} from 'mydatepicker';

private myDatePickerOptions: IMyOptions = {
        dateFormat: 'dd.mm.yyyy',
        // other options
};

private validDate = false;

ngOnInit() {
        this.myForm = this.formBuilder.group({
            myDate: ['']   // not initial date set
        });
}

onInputFieldChanged(event: IMyInputFieldChanged) {
        this.validDate = event.valid;
}
```

**Comment by arvsharm** [comment]
Thanks a lot. It works fine now.
