### ISSUE TITLE
ctorParameters.map is not a function error

### ISSUE THREAD

**Issue by bruno-serfe** [kekeh/mydatepicker#176]
Hi guys, I'm leaving this in order you have knowledge about this error with angular2 v2.4.1 & mydatepicker@1.4.2 (recent update)

See the attached screenshot 
![ctorparameters_error](https://cloud.githubusercontent.com/assets/11821195/22431553/b296420a-e6f0-11e6-8ca9-6f8dd8424e4d.png)

**Comment by kekeh** [comment]
What kind of configuration you have?

**Comment by bruno-serfe** [comment]
I'm using this https://github.com/AngularClass/angular2-webpack-starter And I'm using Angular v2.4.1 not v2.2.4

**Comment by kekeh** [comment]
I tested mydatepicker with the latest **angular2-webpack-starter** and it worked.

- mydatepicker version: 1.5.2
- angular2-webpack-starter version 5.4.1 (this uses angular 2.4.3)

Can you try latest mydatepicker **1.5.2** at first.

![screenshot_2017-01-30_19-34-50](https://cloud.githubusercontent.com/assets/11028839/22434793/33151b92-e726-11e6-96ee-2243f21df403.png)

**Comment by bruno-serfe** [comment]
OK, thanks, I'll try and I'll get back to you soon.

Best!

**Comment by kekeh** [comment]
Did you find a solution?

**Comment by AndreAlves10** [comment]
I'm having this issue too.

![datepicker](https://cloud.githubusercontent.com/assets/25454839/22462372/ef04a164-e7a4-11e6-8920-8a768e5ce63b.png)

I have an angular-cli project and Angular v2.0.2. Any ideas why this is happening?

Thank you!

**Comment by kekeh** [comment]
What is the version of Angular-cli and mydatepicker?

**Comment by AndreAlves10** [comment]
Thanks for the quick reply kekeh!

I'm using Angular-cli v1.0.0-beta.17 and the latest update of mydatepicker.

**Comment by kekeh** [comment]
There is new version **1.6.0** which should fix this error. Can you try that new version?

Older version of Angular taken into use (2.3.1 -> 2.2.4) to prevent ctorParameters.map error.

**Comment by AndreAlves10** [comment]
Works perfectly!

Thank you kekeh.
