### ISSUE TITLE
use another control to open datepicker

### ISSUE THREAD

**Issue by CliffyMk** [kekeh/mydatepicker#178]
i am trying to use another image for the in built calendar icon. 

so what i want is another image on top of the existing and on that click open it.

or if u can provide me the way to override the existing image .

**Comment by kekeh** [comment]
Easiest way is to build own version of this component. Here is how: https://github.com/kekeh/mydatepicker#development-of-this-component

Replace **icon icon-cross** and **icon icon-calendar** classes below for example bootstrap glypicon classes and build the component.

From file: ./src/my-date-picker/my-date-picker.component.html
```html
<button type="button" aria-label="Clear Date" class="btnclear" *ngIf="selectionDayTxt.length>0&&opts.showClearDateBtn" (click)="removeBtnClicked()" [ngClass]="{'btnclearenabled': !opts.componentDisabled, 'btncleardisabled': opts.componentDisabled, 'btnleftborder': opts.showInputField}" [disabled]="opts.componentDisabled">
    <span class="icon icon-cross" [ngStyle]="{'line-height': opts.height}"></span>
</button>
<button type="button" aria-label="Open Calendar" class="btnpicker" (click)="openBtnClicked()" [ngClass]="{'btnpickerenabled': !opts.componentDisabled, 'btnpickerdisabled': opts.componentDisabled, 'btnleftborder': opts.showInputField||selectionDayTxt.length>0&&opts.showClearDateBtn}" [disabled]="opts.componentDisabled">
    <span class="icon icon-calendar" [ngStyle]="{'line-height': opts.height}"></span>
</button>
```

**Comment by CliffyMk** [comment]
how to use another button to activate the datepicker.

**Comment by kekeh** [comment]
Now it is not possible to open the selector from the external button.

**Comment by kekeh** [comment]
You can try the latest **1.6.2** version. Here are instructions on how to programmatically open calendar: https://github.com/kekeh/mydatepicker/wiki/Open-selector-programmatically
