### ISSUE TITLE
Feature request: change icon position

### ISSUE THREAD

**Issue by Mercality** [kekeh/mydatepicker#179]
By default the calendar icon is on the right sided of the input. It would be nice to be able to change it to the left for those with other inputs with left aligned icons.

**Comment by kekeh** [comment]
You can try this: https://github.com/kekeh/ngx-mydatepicker

It is attribute directive datepicker and you can set your own styles to input box, calendar and clear buttons.

Here is demo which input box and buttons are bootstrap styled: https://kekeh.github.io/ngx-mydatepicker/

This component is not yet well tested but you can try.
