### ISSUE TITLE
How to programatically open the calendar window?

### ISSUE THREAD

**Issue by JozefJarosciak** [kekeh/mydatepicker#180]
Just a quick question. I am using mydatepicker in an icon view, meaning, user needs to click the icon in order for calendar to open.

Is there a way to invoke the calendar view on a specific keypress, such as F9?

 f9KeyPress(event): void {
        if(event.keyCode === 120) {
        // WHAT DO I PUT HERE?
        }
    }

  <my-date-picker [options]="myDatePickerOptions"
                    (dateChanged)="onDateChanged($event)"
                    [selDate]="selectedDateNormal"
                    class="right"
                    #datePickerBox>

and then in TS

 setTimeout(() => { this.renderer.invokeElementMethod(this.datePickerBox.nativeElement, 'focus'); }, 0);
or
 this.datePickerBox.nativeElement.click;

doesn't work... albeit doing the same fire event on any input field would work just fine.

**Comment by kekeh** [comment]
Currently it is not possible to open calendar window programmatically. I will investicate this feature.

**Comment by kekeh** [comment]
You can try the latest 1.6.2 version. Here are instructions: https://github.com/kekeh/mydatepicker/wiki/Open-selector-programmatically

**Comment by JozefJarosciak** [comment]
Awesome, I'll try it out tomorrow and let you know if this helped.

**Comment by hoangnguyen1612** [comment]
When I call:
<div title="Click here to edit" (dblclick)="toggleSelector($event)" tabindex="0" class="inline-edit">{{value}}</div>

Then I got an error: 

> TypeError:

 Cannot read property 'openBtnClicked' of undefined

**Comment by kekeh** [comment]
What is version of mydatepicker?

**Comment by hoangnguyen1612** [comment]
Thanks for your reply!
I'm using: `"mydatepicker": "^1.6.3",`
And here is my config:
`private myDatePickerOptions: IMyOptions = {
        dateFormat: 'yyyy/mm/dd',
        inline: false,
        height: '30px',
        width: '110px',
        selectionTxtFontSize: '14px',
        showClearDateBtn: false,
        showInputField: true
    };
`

**Comment by kekeh** [comment]
I mean environment (webpack, systemjs)?

**Comment by hoangnguyen1612** [comment]
I'm using webpack

**Comment by kekeh** [comment]
Did you add variable #mydatepicker to my-date-picker tag?

**Comment by hoangnguyen1612** [comment]
Yes, I added it.
`<my-date-picker #mydatepicker [options]="myDatePickerOptions" [(ngModel)]="model" (dateChanged)="onDateChanged($event)"></my-date-picker>`

**Comment by kekeh** [comment]
I changed the way how to open the selector because current implementation wasn't reliable. I added **selector** attribute. With this attribute you can open the selector.

Here is an example on how to use: https://github.com/kekeh/mydatepicker/wiki/Open-selector-with-selector-attribute

This change is in version 1.6.4.

**Comment by JozefJarosciak** [comment]
Thanks for this implementation. BTW. To the same question, once you programatically open it, how do go about focusing on the calendar component.  And how about closing it calendar programatically?

**Comment by kekeh** [comment]
I did change to the functionality of **selector** attribute. Now it is working similar than the calendar button. If the selector is open it closes it and if the selector is closed it opens it.

More info are here: https://github.com/kekeh/mydatepicker/wiki/Open-selector-with-selector-attribute

Version: 1.6.5

I will investigate focus issue.

**Comment by JozefJarosciak** [comment]
It works in 1.6.5, thanks. 
It'd be great for the focus to work, because we're using our own custom input fields with this component.

**Comment by kekeh** [comment]
Selector is now automatically focused when it is opened. You can move focus with tab and shift + tab.

Version: 1.6.6

**Comment by JozefJarosciak** [comment]
I've updated to version 1.6.7, but unfortunately it still doesn't seem to focus into calendar once I open it programatically.  The focus stays in the input field of my cursor. 
![image](https://cloud.githubusercontent.com/assets/3492464/22659445/a33efdee-ec6b-11e6-8328-81b185f1cd4a.png)
Note: the input field is our own implementation, we don't use mydatepicker input field.

**Comment by kekeh** [comment]
Check that you are not using old version from browser cache.

**Comment by JozefJarosciak** [comment]
npm view mydatepicker version shows:
1.6.7
And caching is disabled in the browser (chrome's network tab)
Weird...

**Comment by JozefJarosciak** [comment]
Ignore whatever I was saying, I didn't have the 1.6.7 installed. 
However, this introduced a bug which forced me to go back to 1.6.6. 
The problem in 1.6.7 is that the calendar gets focus as you've implemented and tabbing inside the calendar view works, but pressing 'enter' button on any date no longer selects the date and whole calendar becomes immediately unresponsive, generating tons of errors.
Calendar works fine until I press F9, which in my code gets calendar focused programatically.
BTW. Nor I am able to press F9 again to close the calendar windows, , it can no longer be closed in any way. It breaks my app to a point I have to refresh it.

**Comment by JozefJarosciak** [comment]
Can you roll back to 1.6.6, or fix the issue that introduction of focusing created?

**Comment by hoangnguyen1612** [comment]
@kekeh thank you so much. I applied it.

**Comment by hoangnguyen1612** [comment]
@kekeh sorry for this inconvenience!
I applied your code but the calendar doesn't focus date that I choose in ngModel.
![image](https://cloud.githubusercontent.com/assets/6647638/22683639/804aca94-ed4b-11e6-8f44-6dd9da42e7e6.png)

But when I clicked the button calendar icon, the calendar showed correctly:
![image](https://cloud.githubusercontent.com/assets/6647638/22683685/b2a8f876-ed4b-11e6-8a5c-1ecdc7cc406a.png)

**Comment by kekeh** [comment]
@hoangnguyen1612 

At first install the latest version 1.6.8. After that:

```html
<my-date-picker name="ngModelDate" [options]="myOptions" [selector]="selector" 
                           [(ngModel)]="model" required></my-date-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateModel} from 'mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        dateFormat: 'dd.mm.yyyy'
    }
    // Initialize date
    private model: Object = {date: {year: 2018, month: 10, day: 9}};

    // Initialize selector to zero - selector is closed
    private selector: number = 0;

    constructor() {}

    // Calling this function opens the selector if it is closed and 
    // closes the selector if it is open
    onToggleSelector(event: any) {
        event.stopPropagation();
        // Increase value of the selector by one in order the component detect 
        // changes constantly
        this.selector++;
    }
}
```

Here is complete example which works: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

**Comment by kekeh** [comment]
@JozefJarosciak 

I am ot able to reproduce the error, but I did one change. New version is 1.6.8. Are you able to reproduce the error here: http://kekeh.github.io/mydatepicker

**Comment by JozefJarosciak** [comment]
It still doesn't work for me.

I have 3 input fields that are contained in a DIV, that captures the keyup event.
Something like this:
<div class="partial-dates" (keyup)="captureKeyPress($event);">
<input><span>/</span>
<input><span>/</span>
<input><span>/</span>
</div>

The TS has the following:
`    
    import {IMyOptions, IMyDateModel} from 'mydatepicker';
    constructor() {}
    // Initialize selector to zero - selector is closed
    private openCalendarWindow: number = 0;

    myDatePickerOptions: IMyOptions = {
        dateFormat: 'dd/mm/yyyy',
        showInputField: false,
        showClearDateBtn: false
    };


    /**
     * This method updates Calendar popup with values from partial date input fields
     */
    onDatePickerDateChange(event: IMyDateModel) {
     // I update 3 input fields with split of calendar values
    }

    onOpenCalendarSelector() {
        event.stopPropagation();
        this.openCalendarWindow++;
    }

    // Keystroke Capture
    captureKeyPress(event): void {
        // capture F9 Key
        if(event.keyCode === 120) {
            this.onOpenCalendarSelector();
        }
    }
`

This is the error I am getting:

![image](https://cloud.githubusercontent.com/assets/3492464/22691587/2961b63a-ed09-11e6-9588-1a475b52ee8b.png)

**Comment by kekeh** [comment]
I put your code into my application and it worked well with version 1.6.8. The selector opened with F9 key and it was focused.

Is this error related to mydatepicker at all or is this related to PartialDateComponent template? When checking the error code it is showing that inline template line 32 caused this. It is referring to PartialDateComponent inline template?

**Comment by JozefJarosciak** [comment]
Unable to figure out, something is breaking somewhere and the errors are not pointing me to a right place. Can you make the focus configurable/optional?
Much appreciated and sorry for the hassle, I know I asked for it in the first place...

**Comment by kekeh** [comment]
Did you get the error when press F9 key? Install 1.6.9 at first I fixed one related to focusing.

You can also try this. Move keyup to each input.
```html
<div class="partial-dates" >
     <input (keyup)="captureKeyPress($event);"><span>/</span>
     <input (keyup)="captureKeyPress($event);"><span>/</span>
     <input (keyup)="captureKeyPress($event);"><span>/</span>

    <my-date-picker [options]="myDatePickerOptions"
                    (dateChanged)="onDatePickerDateChange($event)"
                    [selDate]="selectedDateNormal"
                    [selector]="openCalendarWindow"
                    class="right"></my-date-picker>

</div>
```
