### ISSUE TITLE
Resetting a reactive form

### ISSUE THREAD

**Issue by ayls** [kekeh/mydatepicker#182]
Hi,
 
I can't seem to figure out how to do this properly. I have a reactive form initialized like this:
```
this.form = this.fb.group({
            'date' : [{ date: { day: 4, month: 2, year: 2017 } }, Validators.required],
            'title': ['some title', Validators.required],
            'body' : ['some text', Validators.required]
});    
```

Then after I save the form I want to reset the state of the form so it is no longer dirty. I am running this:

```
this.form.reset({
            'date' : /* new date here in the { date: {...} } format */,
            'title': 'a new title',
            'body' : 'updated text'
});
```
After this the title and body have their status reset (have new values and are no longer marked as dirty), but the date control's state is still dirty.

I noticed that this case (clearing the value) works (dirty is false after running it):

```
this.form.controls['date'].reset();
```
But it seems when resetting to a new value the control gets marked as dirty. This causes an issue (dirty become true): 

```
this.form.controls['date'].reset({ date: {...} });
```

What is the correct way to reset mydatepicker to a new value?

I am using version 1.6.1 and Angular version 2.3.1

**Comment by kekeh** [comment]
Try to latest version **1.6.2**. Now you can reset to specific date and the value of dirty becomes false. For example:

```ts
this.form.controls['date'].reset({ date: {...} });
```

**Comment by ayls** [comment]
Thanks! That was an impressively quick turnaroud :)
