### ISSUE TITLE
Feature request: disable future or past

### ISSUE THREAD

**Issue by nusje2000** [kekeh/mydatepicker#183]
It would be nice to have something in the settings to disable dates in the future or in the past, for things like birthdays (Can't be in the future) or upcoming appointments (Can't be in the past) .

**Comment by kekeh** [comment]
You can already disable day in many ways. Check here: https://github.com/kekeh/mydatepicker#options-attribute

starting from the disableUntil option. Is this something you looking for?

**Comment by nusje2000** [comment]
thanks, I thought I red the entire documentation. That is exactly what I'm looking for.
