### ISSUE TITLE
Warning while running webpack npm start

### ISSUE THREAD

**Issue by neoms21** [kekeh/mydatepicker#184]
Hi,

I get all these warnings if I include mydatepicker in webpack configuration.
Due to this warnings, hmr stops working.  Is there something I'm doing incorrectly in configuring the mydatepicker ?

This is how my app.module.ts looks like:
import {MyDatePickerModule} from "mydatepicker";

@NgModule({
    declarations: [
        AppComponent,
        APP_DECLARATIONS
    ],
    entryComponents: [APP_ENTRY_COMPONENTS],
    imports: [
        APP_IMPORTS,
        BrowserModule,
        HttpModule,
        FormsModule,
        ReactiveFormsModule,
        SidebarModule,
        MyDatePickerModule,

WARNING in ./~/mydatepicker/dist/my-date-picker.module.js
Cannot find source file '../../src/my-date-picker/my-date-picker.module.ts': Error: Can't resolve '../../src/my-date-picker/my-date-picker.module.ts' in 'D:\Code\Acoach-mobile\node_modules\mydatepicker\dist'
 @ ./~/mydatepicker/index.js 5:9-48
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

WARNING in ./~/mydatepicker/dist/my-date-picker.component.js
Cannot find source file '../../src/my-date-picker/my-date-picker.component.ts': Error: Can't resolve '../../src/my-date-picker/my-date-picker.component.ts' in 'D:\Code\Acoach-mobile\node_modules\mydatepicker\dist'
 @ ./~/mydatepicker/dist/my-date-picker.module.js 4:0-58
 @ ./~/mydatepicker/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

WARNING in ./~/mydatepicker/dist/directives/my-date-picker.input.directive.js
Cannot find source file '../../../src/my-date-picker/directives/my-date-picker.input.directive.ts': Error: Can't resolve '../../../src/my-date-picker/directives/my-date-picker.input.directive.ts' in 'D:\Code\Acoach-mobile\node_modules\mydatepicker\dist\directives'
 @ ./~/mydatepicker/dist/my-date-picker.module.js 5:0-82
 @ ./~/mydatepicker/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

WARNING in ./~/mydatepicker/dist/services/my-date-picker.locale.service.js
Cannot find source file '../../../src/my-date-picker/services/my-date-picker.locale.service.ts': Error: Can't resolve '../../../src/my-date-picker/services/my-date-picker.locale.service.ts' in 'D:\Code\Acoach-mobile\node_modules\mydatepicker\dist\services'
 @ ./~/mydatepicker/dist/my-date-picker.component.js 3:0-73
 @ ./~/mydatepicker/dist/my-date-picker.module.js
 @ ./~/mydatepicker/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

WARNING in ./~/mydatepicker/dist/services/my-date-picker.validator.service.js
Cannot find source file '../../../src/my-date-picker/services/my-date-picker.validator.service.ts': Error: Can't resolve '../../../src/my-date-picker/services/my-date-picker.validator.service.ts' in 'D:\Code\Acoach-mobile\node_modules\mydatepicker\dist\services'
 @ ./~/mydatepicker/dist/my-date-picker.component.js 4:0-79
 @ ./~/mydatepicker/dist/my-date-picker.module.js
 @ ./~/mydatepicker/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

**Comment by kekeh** [comment]
Did you install mydatepicker from npm?

**npm install mydatepicker --save**

It is looking under the **src** folder: '../../src/my-date-picker/my-date-picker.module.ts'

There is not the **src** folder in the npm package.

**Comment by neoms21** [comment]
Yes I installed it from npm. I even tried copying the src folder directly just to see if warnings would disappear but no joy as paths are looking in different location then where src actually goes.

**Comment by kekeh** [comment]
This is webpack project and it is working: https://github.com/kekeh/mydatepicker/tree/gh-pages

This application is running here: http://kekeh.github.io/mydatepicker/

**Comment by neoms21** [comment]
Ummm OK.  Then I guess I've to check my Webpack  config. It must be doing
something special.

I'll publish my findings here.

**Comment by neoms21** [comment]
I couldn't find anything in my webpack config so for now have just excluded the source maps for datepicker. Only other thing is I'm using webpack 2.2.1 while in the project you mentioned it's 1.3

I'm using https://github.com/qdouble/angular-webpack2-starter#readme as a starter pack for my project

**Comment by kekeh** [comment]
I tried angular-webpack2-starter and it work but there are warnings in console when you run application:

WARNING in ./~/mydatepicker/dist/my-date-picker.module.js
Cannot find source file '../../src/my-date-picker/my-date-picker.module.ts': Error: Can't resolve '../../src/my-date-picker/my-date-picker.module.ts' in '/home/keijo/code/angular-webpack2-starter/node_modules/mydatepicker/dist'
 @ ./~/mydatepicker/index.js 5:9-48
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

I don't know why source files are needed. npm package of mydatepicker doesn't contain typescript source files. Only javascript and *.d.ts files.

![screenshot_2017-02-07_17-48-27](https://cloud.githubusercontent.com/assets/11028839/22698601/a784a8d4-ed5d-11e6-8a95-4c1aba5f21cf.png)

**Comment by kekeh** [comment]
I solved the issue. This is from the **constants.js** file from the angular-webpack2-starter package.
```javascript
exports.EXCLUDE_SOURCE_MAPS = [
  // these packages have problems with their sourcemaps
  root('node_modules/@angular'),
  root('node_modules/rxjs'),
  root('node_modules/mydatepicker')  // Add this line
]
```

Just add the above line and install the latest mydatepicker: **npm install mydatepicker**

Then warnings go away.
