### ISSUE TITLE
Event when mouse click outside calendar

### ISSUE THREAD

**Issue by hoangnguyen1612** [kekeh/mydatepicker#185]
Hi @kekeh ,
Thanks for your component help me so much. But I have a issue, how to I can get emit event when mouse click outside calendar?

I saw your code:
`renderer.listenGlobal("document", "click", function (event) {
            if (_this.showSelector && event.target && _this.elem.nativeElement !== event.target && !_this.elem.nativeElement.contains(event.target)) {
                _this.showSelector = false;
            }
            if (_this.opts.editableMonthAndYear && event.target && _this.elem.nativeElement.contains(event.target)) {
                _this.resetMonthYearEdit();
            }
        });`

Maybe having an emit sending to parent when `_this.showSelector = false;` ? Thank you!

>

**Comment by kekeh** [comment]
Why you need this kind of event. I think maybe there are other way to solve the issue?

**Comment by kekeh** [comment]
I added new callback **calendarToggle**.

More info from here: https://github.com/kekeh/mydatepicker#calendartoggle-callback

This change is in version 1.6.10.

**Comment by hoangnguyen1612** [comment]
@kekeh Thank you so much! But I have a new issue. 
When I open two date picker:
![image](https://cloud.githubusercontent.com/assets/6647638/22918662/00b87812-f2be-11e6-867a-8eca2ff94976.png)

when I click to open the second date picker, the first date picker don't close?

**Comment by kekeh** [comment]
There was a bug. I fixed it in version **1.6.12**. Try that version.

**Comment by hoangnguyen1612** [comment]
@kekeh Thank you so much!
