### ISSUE TITLE
Invalid dates on iOS browsers

### ISSUE THREAD

**Issue by saratSubramaniam** [kekeh/mydatepicker#186]
Hello,
Used the ng2-my-datepicker in my angular 2 application. It works well with desktop browsers, but fails in iOS browsers in the iPads.
The issue comes up while setting a date to the date picker. The year and month values are shown as NAN, and inside the date picker, year and month cannot be changed.
Any thoughts anybody ?

**Comment by kekeh** [comment]
ng2-my-datepicker is separate component. This component is mydatepicker.

But if you are using **mydatepicker** you can initialize date picker as follows: https://github.com/kekeh/mydatepicker/wiki/Initialize-with-selDate-attribute

Value of **selDate** can be **IMyDate** object or **string**. Here is documentation: https://github.com/kekeh/mydatepicker#seldate-attribute

If you are using a **string** you must prepend month and day with zeros if their value is lower than 10. For example if your **dateFormat** is 'dd.mm.yyyy'. Value of **selDate** (today) must be '07.01.2017'.

**Comment by saratSubramaniam** [comment]
Sorry, **mydatepicker** is the one I'm using, yes. sorry for the type error.
Anyway the issue I had was fixed when a regular expression was added which solved the date formatting issues with iOS.

This was the fix
new Date(dateObject.replace(/-/g, "/"));
