### ISSUE TITLE
dateFormat option - Didn't work with format string of "mm/dd/yyyy"

### ISSUE THREAD

**Issue by phuongnguyenxtivia** [kekeh/mydatepicker#187]
Dear @kekeh,

Thank you so much for the great date picker, I use it easier than other date picker.

One minor problem I got today is dateFormat option didn't work correctly with string of "mm/dd/yyyy". Did the component support that kind of date format? Please advise.

Thank you and best regards,
Peter.

**Comment by kekeh** [comment]
This dateFormat is supported. Check here on how to define the dateFormat and the other options: https://github.com/kekeh/mydatepicker/wiki/Set-placeholder

What kind of problems there is?

**Comment by phuongnguyenxtivia** [comment]
Dear @kekeh ,

I already set dateFormat as "mm/dd/yyyy" but it didn't work as expected.
    private myDatePickerOptions: IMyOptions = {
        dateFormat: "mm/dd/yyyy",
        editableDateField: false,
        inputValueRequired: true,
        ...

After I selected one date from the date picker, in the input field, it always shows the date with format of "yyyy-mm-dd".

**Comment by kekeh** [comment]
I tested it and the date format worked ok. Format **yyyy-mm-dd** is the default value. Component uses the default value. Did you set options right way to the component? For example:

```html
<my-date-picker [options]="myDatePickerOptions" 
                (dateChanged)="onDateChanged($event)"></my-date-picker>
```
```javascript
private myDatePickerOptions: IMyOptions {
    // other options here...
    dateFormat: 'mm/dd/yyyy'
}
```

Try other option for example **showTodayBtn: false**. The when you open the calendar the today button should not be visible. If it is visible your options are not passed to the component. This is just verifying the options.

**Comment by phuongnguyenxtivia** [comment]
Hi @kekeh,

I did as you mentioned, the showTodayBtn is invisible now. Below is the way I applied this component.
HTML:
`                  <my-date-picker name="myDate" [options]="myDatePickerOptions" formControlName="myDate" [locale]="getCurrentLang()" (dateChanged)="onDateChanged($event)"></my-date-picker>`

Typescript Component:
```
    private myDatePickerOptions: IMyOptions = {
        dateFormat: "mm/dd/yyyy",
        editableDateField: false,
        inputValueRequired: true,
        showTodayBtn: false,
        disableUntil: { year: 0, month: 0, day: 0 },
        disableSince: { year: 9999, month: 12, day: 31 }
    };
onDateChanged(event: IMyDateModel) { // do something }
```

Also attached the pictures. Please let me know if I need more modification. Thank you so much.

![capture](https://cloud.githubusercontent.com/assets/23478138/22743780/e03772e6-ede0-11e6-8bfc-a1e3562b0ece.PNG)

![capture1](https://cloud.githubusercontent.com/assets/23478138/22743828/051fad58-ede1-11e6-9b2f-5e888eb8b76e.PNG)

**Comment by kekeh** [comment]
You can put **showTodayBtn** value back to **true**.  Seems that you are using some **locale**. If you are using locale attribute it overrides value of **dateFormat**.

You can check values of each locale from here: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/services/my-date-picker.locale.service.ts

If you are using **en** locale it uses dateFormat **yyyy-mm-dd** and it overrides your locale which is defined in options attribute.

locale is optional attribute and you can remove it if you want text to be English because it is default. After that your own dateFormat works.

**Comment by phuongnguyenxtivia** [comment]
Oh, sorry, this is my bad, I didn't read this section carefully. Thanks @kekeh  for your explanation. 

So would you have a plan to support dateFormat cannot be override in the future? Because many projects need to do both of **locale** and **dateFormat**.

**Comment by Akhilesh601** [comment]
Hi @kekeh,

when i am using IMyDpOptions as array then dateformat is not getting applied in mydatepicker.
e.g:
public poEndDatePickerOptions: IMyDpOptions[] = [{
    dateFormat: 'mm-dd-yyyy',
    showWeekNumbers: false,
    editableDateField: true,
  }];
   <my-date-picker [options]="poEndDatePickerOptions[i]" (dateChanged)="onPoEndDateChanged($event,i)"></my-date-picker>
but when i am selecting date in html its displaying in format mm/dd/yyyy. it seems dateFormat is not getting applied.
 when i am using IMyDpOptions without array its working perfectely. means which ever format i am giving itsd displaying in the same format in html.

any help will be appreciated

**Comment by kekeh** [comment]
Hi @Akhilesh601 

You can do as follows if you have multiple date pickers.
```html
<div *ngFor="let opt of poEndDatePickerOptions">
    <my-date-picker [options]="opt"></my-date-picker>
</div>
```

```javascript
public poEndDatePickerOptions: IMyDpOptions[] = [{
    dateFormat: 'mm-dd-yyyy',
    showWeekNumbers: false,
    editableDateField: true,
}, 
{
    dateFormat: 'mm-dd-yyyy',
    showWeekNumbers: false,
    editableDateField: true, 
}];
```

**Comment by kanishkamehta801** [comment]
@Akhilesh601  Did it worked, I am also facing the same issue.

**Comment by Akhilesh601** [comment]
@kanishkamehta801  yes this issue has resolved for me.
