### ISSUE TITLE
making the input required

### ISSUE THREAD

**Issue by CliffyMk** [kekeh/mydatepicker#188]
any way to make the input required

**Comment by kekeh** [comment]
Here is an example using ngModel: https://github.com/kekeh/mydatepicker/wiki/Use-ngModel

or

if you are using reactive forms: https://github.com/kekeh/mydatepicker#2-reactive-forms

**Comment by CliffyMk** [comment]
but i want to change the border to red like normal required controls on form submit.

**Comment by kekeh** [comment]
Set border to red is not possible. Only background is red if the date is not valid in the input box. If input box is empty background is not red.

You have to set the **indicateInvalidDate** option true which is the default value.
