### ISSUE TITLE
Focus directive attaches to input with (focus) event binding

### ISSUE THREAD

**Issue by DarkXaHTeP** [kekeh/mydatepicker#189]
I have a few inputs on the page that have a focus handlers. After updating of mydatepicker I found out that last of the inputs becomes focused after page load. The cause of this issue is that inputFocus directive from mydatepicker package uses [focus] as a selector and attaches to the inputs where it is not desired. Could you please add some kind of prefix to selector? e.g. "[myFocus]" or "[my-focus]"?

Thanks

**Comment by DarkXaHTeP** [comment]
One more suggestion: such changes should be followed by at least minor version increase according to semantic versioning. This is definitely not a patch

**Comment by kekeh** [comment]
You can now try version 1.6.9

**Comment by DarkXaHTeP** [comment]
Thanks, it helped
