### ISSUE TITLE
Block out dates

### ISSUE THREAD

**Issue by karlclement** [kekeh/mydatepicker#19]
Hi there,

I have 2 issues, how would I block any date in the past? Also, I'd like to be able to block out weekends, how could I do that?

Thanks!

**Comment by kekeh** [comment]
Hi,

Current version of date picker doesn't support this. You have to implement it.

**Comment by kekeh** [comment]
Added disable dates backward and forward options. The sample app contains example. Disable weekends is not done yet.

**Comment by kekeh** [comment]
I added also disableWeekends option. The sample app contains an example.
