### ISSUE TITLE
Feature request: custom calendar icon

### ISSUE THREAD

**Issue by tomasznastaly** [kekeh/mydatepicker#190]
Hello, currently we have ugly:P calendar icon. I want to replace it with my own SVG icon. It's possible actually? can we add this feature?

**Comment by kekeh** [comment]
It is quite difficult to change. Font icons are in this file as base64 encoded string: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.css

Check  in line 419.

But you can edit the the template and change this line:
<span class="icon icon-calendar" [ngStyle]="{'line-height': opts.height}"></span>

Change class for example to **glyphicon glyphicon-calendar**. It is bootstrap glypicon. After that you have to build own version of the component. Her is how you can do it: https://github.com/kekeh/mydatepicker#development-of-this-component

I have used fontello http://fontello.com/ to generate font icons (base64). You can also do that and then replace base64 encoded string and content properties under that.

**Comment by kekeh** [comment]
You can try this: https://github.com/kekeh/ngx-mydatepicker

It is attribute directive datepicker and you can set your own styles to input box, calendar and clear buttons.

Here is demo which input box and buttons are bootstrap styled: https://kekeh.github.io/ngx-mydatepicker/

This component is not yet well tested but you can try.

**Comment by kekeh** [comment]
I changed fonts icons to Font Awesome font icons. This is available in version 1.7.0.
