### ISSUE TITLE
Callbacks parameters

### ISSUE THREAD

**Issue by jogaian282** [kekeh/mydatepicker#192]
Currently having dateChanged event callback . But when we want to use datepicker multiple times and for example we want to calculate age of patient registered and as well in same time we want to calculate guarantor age, in this type of scenario how to pass parameters and bind model value of both ages differently in view. Thanks in advance

**Comment by kekeh** [comment]
@jogaian282 

Your requirement is quite high level. I don't understand your requirement from the text above. Can you tell more.

Do you want to change call parameters? Now it is IMyDateModel

**Comment by jogaian282** [comment]
![screen shot from 2017-02-10 13-35-32](https://cloud.githubusercontent.com/assets/19630898/22818974/e5bda274-ef95-11e6-8534-ed08b1e233de.png)    I  attached screen shot . Please find it . My requirement is calculating age when  selected calling date changed event written logic for age calculation and binding result from model to view. This to be happened for both patient and guarantor age as mentioned in screen shot. Please find it and how to pass parameters and bind separate  age fields in view.

**Comment by kekeh** [comment]
You have two date pickers and you want to separate callback for both. Right?

You can do it as follows:
```html
<my-date-picker [options]="myOptions" 
                (dateChanged)="onDateChanged1($event)"></my-date-picker>

<my-date-picker [options]="myOptions" 
                (dateChanged)="onDateChanged2($event)"></my-date-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateModel} from 'mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        dateFormat: 'dd.mm.yyyy'
    }

    private date1: IMyDate = {year: 0, month: 0, day: 0};
    private date2: IMyDate = {year: 0, month: 0, day: 0};

    constructor() {}

    onDateChanged1(event: IMyDateModel) {
        // date 1 selected 
        this.date1 = event.date;
    }

    onDateChanged2(event: IMyDateModel) {
        // date 2 selected
        this.date2 = event.date;
    }
}
```

**Comment by kekeh** [comment]
What could be the parameter xx in example above?

**Comment by jogaian282** [comment]
Thanks. Again thanks for your quick response. I fixed the problem and will close this issue.
