### ISSUE TITLE
Clear the dates on click.

### ISSUE THREAD

**Issue by pranavsreedhar92** [kekeh/mydatepicker#195]
How to clear the dates on click of button. Tried with the following code.

**HTML Page**
<button (click)="clearDate()">Clear</button>

<my-date-picker name="driver_dob" formControlName="driver_dob" [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)"></my-date-picker>

**ts file**
clearDate(): void {
        // Clear the date using the setValue function
        this.form_addDriver.setValue({driver_dob: ''});
}

**Comment by kekeh** [comment]
You should use the **selDate** attribute. Check example from here: https://github.com/kekeh/mydatepicker/wiki/Initialize-with-selDate-attribute

If you don't want to set initial date you can forget the code from the **constructor**, but otherwise you can use the example code to clear the date.
