### ISSUE TITLE
Disable future years and months by disabling headerbtncell

### ISSUE THREAD

**Issue by jogaian282** [kekeh/mydatepicker#196]
Is there a way to disable 2018 by clicking the icon? I am able to disable future dates but 2018 is clickable? Please provide a solution

**Comment by kekeh** [comment]
I added new option **showCalendarIfDisabled** which disables header buttons if **minYear**, **maxYear**, **disableUntil** or **disableSince** are used. Set the **showCalendarIfDisabled** option to **false** to disable header buttons.

This is in version 1.6.13.

You can first test it here: http://kekeh.github.io/mydatepicker/#inlinemode
