### ISSUE TITLE
Future dates are getting disabled when binding values.

### ISSUE THREAD

**Issue by pranavsreedhar92** [kekeh/mydatepicker#197]
Future dates are disabled and will be enabled only if a trigger happens.

**HTML**
<my-date-picker [formControl]="dob" [options]="myDatePickerOptions" [(ngModel)]="model"></my-date-picker>

**ts File**
private myDatePickerOptions: IMyOptions = {
        dateFormat: 'yyyy-mm-dd',
};

**Comment by kekeh** [comment]
Do you mean that future dates are disabled without option?

**Comment by pranavsreedhar92** [comment]
yes

**Comment by kekeh** [comment]
@pranavsreedhar92 

What is first disabled date?

I am not able to reproduce this issue based on information you gave. Are you using ngModel binding or reactive forms? In your HTML there is formControl attribute. 

- If you are using ngModel binding follow instructions from here: https://github.com/kekeh/mydatepicker#3-ngmodel-binding
- If you are using reactive forms follow instructions from here: https://github.com/kekeh/mydatepicker#2-reactive-forms

Here is complete example of both options: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

**Comment by pranavsreedhar92** [comment]
I am using ngModel for binding dates. Attaching the screenshot.  
Please let me known any options has to be enabled.

![issue-1](https://cloud.githubusercontent.com/assets/13045965/23096221/c181b586-f63d-11e6-9f60-238065e03e2b.png)

**Comment by kekeh** [comment]
I see problem in your screenshot because 2nd and 9th of next month are marked Sunday even they are Thursday. Are you trying to set any initial date? Can you any error in console of the browser?

Can you try  the following options:
```html
<my-date-picker name="myDate" [options]="myDatePickerOptions" 
                           [(ngModel)]="model"></my-date-picker>
```

```javascript
private myDatePickerOptions: IMyOptions = {
        dateFormat: 'yyyy-mm-dd'
};

private model: string = '';   // not initial date set

// If you want to set initial date you can do it as follows:
// private model: Object = {date: {year: 2018, month: 10, day: 9}};
```

**Comment by pranavsreedhar92** [comment]
I am setting an initial date from ts file.

private regDate : Object;

this.regDate = this.formatDate(this.vehicle.registrationDate);

**Function to set date**
public formatDate(string){

//Spliting the date into year, month and, day 
	return  {
		date: { year: spiltDob[0], month: month, day: day} 
        };
}

**Comment by kekeh** [comment]
Are you setting initial date with **ngModel** or **selDate** attribute? If you are using the **selDate** attribute remove it and try date picker without initial date to see if it is causing error.

```html
<my-date-picker name="myDate" [options]="myDatePickerOptions" 
                           [(ngModel)]="model"></my-date-picker>
```

```javascript
private myDatePickerOptions: IMyOptions = {
        dateFormat: 'yyyy-mm-dd'
};

private model: string = '';   // not initial date set
```

**Comment by kekeh** [comment]
probably you are setting strings to the value of ngModel properties. Value of **year**, **month** and **day** must a **number** not a string.

I was able to reproduce error when I used strings as a value of year. 

```javascript
public formatDate(string){
    //Spliting the date into year, month and, day
    return {
        // ERROR is here: Use number to the value year, month and day
        date: { year: spiltDob[0], month: month, day: day} 
    };
}
```
