### ISSUE TITLE
[Question]: Programatic/reactive way to disable/enable dates? 

### ISSUE THREAD

**Issue by fwertz** [kekeh/mydatepicker#199]
I have a use case where I need to enable only certain dates of the month, but only when the month is selected/revealed. Is this possible? The only way I know how this can be done with the picker is using `options.enableDays`. I'm using a viewRef to grab the date picker and trying methods like `setOptions()` and the closest I've got is the control view updates but not until it is toggled.

Is something like this possible, or even hackable?

**Comment by kekeh** [comment]
You can dynamically change date picker options. Also disable/enable days. You can implement the **calendarViewChanged** callback and disable/enable days in this function like below:
```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)"
           (calendarViewChanged)="onCalendarViewChanged($event)"></my-date-picker>
```

```javascript
// this function is called when calendar month change, parameter contains information 
// of the selected month
onCalendarViewChanged(event: IMyCalendarViewChanged) {
    // first disable February of 2017 and then enable 14th and 15th of the month
    let copy = this.getCopyOfOptions();
    copy.disableDateRange = {begin: {year: 2017, month: 2, day: 1}, end: {year: 2017, month: 2, day: 28}};
    copy.enableDays = [{year: 2017, month: 2, day: 14}, {year: 2017, month: 2, day: 15}];
    this.myDatePickerOptions = copy;
}

// You need to create new copy of options in order to date picker detect changes
getCopyOfOptions(): IMyOptions {
    return JSON.parse(JSON.stringify(this.myDatePickerOptions));
}
```

Here is example which dynamically change options of date picker: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-inline/sample-date-picker-inline.ts

**Comment by fwertz** [comment]
Hey man! Thanks for the detailed reply. This almost meets my use case. The problem is the calendar doesn't redraw when it's open. When switching between months, the enabled dates are for the previous month selected. I am using `onCalendarViewChanged` to capture the change event. 

Maybe this helps illustrate:

![image](https://cloud.githubusercontent.com/assets/748204/23227806/2b264b42-f908-11e6-8c52-5ebadc4c7547.png)

**Comment by kekeh** [comment]
I fixed redraw problem. Update the latest version (1.6.18) from npm. Is it ok?

**Comment by sagar-kiwi** [comment]
how can i disable all past dates from current

**Comment by kekeh** [comment]
Here is an aexample: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

it disables past dates starting from yesterday, but you can remove the line:

  d.setDate(d.getDate() - 1);
