### ISSUE TITLE
Button currentDate is not working

### ISSUE THREAD

**Issue by khoanguyenlio** [kekeh/mydatepicker#2]
I use demo online and button CurrentDate seem not working.
Sorry my mistake but when I put it in form, when i click on CurrentDate button and I got  EXCEPTION: Error during evaluation of "ngSubmit"??

**Comment by kekeh** [comment]
I fixed that by adding type="button" to button element in the HTML template. Please update to the latest version.

**Comment by khoanguyenlio** [comment]
Thank you <3
