### ISSUE TITLE
How to support date format in different ways

### ISSUE THREAD

**Issue by arvsharm** [kekeh/mydatepicker#200]
Hi,

I have used date format as mm/dd/yyyy in myDatePickerOptions and it works fine but how to configure it to also support m/d/yyyy so if user enters 2/5/2017 it should come as valid date in IMyInputFieldChanged

Thanks
Arvind

**Comment by arvsharm** [comment]
I tried a workaround where in inputFieldChanged event handler converting entered m/d/yyyy format string to date object and assigning to date field using patchValue. 
So it works fine and date becomes valid but while saving form date comes as blank.

**Comment by kekeh** [comment]
Hello @arvsharm 

I added new option **inputAutoFill**. By default it is **true**. It automatically adds separator of the date format and leading zeros.

New version of the component is: **1.6.19**.
