### ISSUE TITLE
disableUntil, day is included

### ISSUE THREAD

**Issue by tomasznastaly** [kekeh/mydatepicker#201]
Currently, disableUntil & disableSince, include the day. For example:
datePickerOptions.disableSince = {
      year: 2017
      month: 12,
      day: 2
    };

So the day "2" is also disabled, i don't want it. Is possible to make disableSince to 2017/12/1 ?

My problem:
I have two date pickers - start date and end date.
If in startDatePicker i choose  1/03/2017 then i want endDatePicker to have disabled dates since 28/02/2017

My function:
```
  onStdFromChanged(event) : void {
    let stdToPickerOptionsCopy = FilterComponent.getCopyOfObject(this.stdToPickerOptions);
    stdToPickerOptionsCopy.disableUntil = {
      year: event.date.year,
      month: event.date.month,
      day: event.date.day - 1
    };

    this.stdToPickerOptions = stdToPickerOptionsCopy;
  }
```

This event.date.day -1 works on dates between 2-31,  but if i choose 1/03/2017,  nothing happened.

Any idea? good if we have disableUntil&disableSince with option to include the day or not.

**Comment by kekeh** [comment]
You have to use javascript Date object to decrease one day. Implement the **onStdFromChanged** function this way:
```javascript
onStdFromChanged(event) : void {
    let d: Date = new Date(event.year, event.month - 1, event.day, 0, 0, 0, 0);

    // set previous date
    d.setDate(d.getDate() - 1);

    let stdToPickerOptionsCopy = FilterComponent.getCopyOfObject(this.stdToPickerOptions);
    stdToPickerOptionsCopy.disableUntil = {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    };

    this.stdToPickerOptions = stdToPickerOptionsCopy;
}
```
