### ISSUE TITLE
Too much dependencies with fixed version

### ISSUE THREAD

**Issue by papaiatis** [kekeh/mydatepicker#202]
Going through the dependencies in package.json reveals way too much things to install. They don't even sorted out well, eg.: @angular components should go to the "dependencies" section.
The worst part is that almost each dependency has a fixed version, eg.: @angular 2.2.4.  This way when I try to install this package I got a lot of "unmet peer dependencies".

It would be very nice to extract the datepicker module only to a separate package without all the karma, gulp, webpack, etc (long list) stuff so that it would be a clean and easy install.

**Comment by kekeh** [comment]
Those mydatepicker dependencies are only for developing purposes. 

If you want to include datepicker into your own application you have to install it from **npm** (npm install mydatepicker). If you install mydatepicker from the npm, there is not any dependencies.

If you want to develop mydatepicker then you only need to install those dependencies. Here is how you can do it: https://github.com/kekeh/mydatepicker#development-of-this-component

What you are trying to do?
