### ISSUE TITLE
Open/Close Date picker on input mouseover and mouseleave

### ISSUE THREAD

**Issue by RathodGirish** [kekeh/mydatepicker#203]
Hi I am using mydatepicker in my angular2 project.
It is working excellent.

I need to open and close Datepicker on mouseover and mouseleave event.
Is there any way to open and close Datepicker manually using mouse event.

Please any suggestions?
Thanks

**Comment by kekeh** [comment]
You can open/close calendar programmatically. Here is an example: https://github.com/kekeh/mydatepicker/wiki/Open-selector-with-selector-attribute

Does this solve your requirement?

**Comment by RathodGirish** [comment]
Yeah cool
https://github.com/kekeh/ngx-mydatepicker works perfectly.

Thanks a lot @kekeh  :)
