### ISSUE TITLE
Option to keep the same dateFormat for different locales

### ISSUE THREAD

**Issue by zzakir** [kekeh/mydatepicker#204]
Right now, if I set the dateFormat in IMyOptions, it is ignored when I change the locale. Is it possible to keep the same dateFormat for different locales?

**Comment by kekeh** [comment]
I changed the way how the locale attribute works. Now the **locale** options can be overridden by **options** attribute. 

Now you can keep the same date format if you set the date format in options.
 
This is implemented in version 1.7.1.

**Comment by zzakir** [comment]
Thank you very much @kekeh
