### ISSUE TITLE
Input is constantly untouched

### ISSUE THREAD

**Issue by zacol** [kekeh/mydatepicker#205]
Current version of component is constantly untouched. There is not `this.onTouchedCb();` execution in the component file. I think that it should be trigger at least two time - when user close calendar tooltip (first condition in constructor if statement) and when user click on clear button (`removeBtnClicked()` function).

Also, there should be one more `this.onTouchedCb()` if datepicker is run into inline mode.

**Comment by kekeh** [comment]
I did not find any good documentation from the ControlValueAccessor. But maybe touch event occurs when user set focus to the input box. Otherwise it would be change event (edit, clear input box). Right?

**Comment by zacol** [comment]
I agree with you, documentation for ControlValueAccessor is quite poor.

> `registerOnChange(fn: any)` is a method that registers a handler that should be called when something in the view has changed. It gets a function that tells other form directives and form controls to update their values. In other words, that’s the handler function we want to call whenever counterValue changes through the view.

> `registerOnTouched(fn: any)` Similiar to registerOnChange(), this registers a handler specifically for when a control receives a touch event. We don’t need that in our custom control.

This is a quite from https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html. As far as I understand, `registerOnChange` and `registerOnTouched` are similar functions but they handle different situations. The first one update ngModel/formControl/formControlName when value changed into your component. Another one is responsible for updating touch flag for control.

Right now, I can't run your sample up with reactive implementation but in my app I can change date, I see new date in input, but control still has untouched class. When I add `registerOnTouched` everything works fine.

I will check your example in home and let you know about result :)

**Comment by kekeh** [comment]
Hello @zacol 

Now module becomes touched in the following situations.
- lost focus from the input box
- select a date
- clear a date
- edit a date in the input box

This fix is in version 1.7.2.

**Comment by zacol** [comment]
Thank you very much. I will test it as soon as possible ;)
