### ISSUE TITLE
ngModel binding is not working

### ISSUE THREAD

**Issue by kkarandikar0807** [kekeh/mydatepicker#206]

**Comment by kekeh** [comment]
Can give more information what is the problem?

Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

Here is sampleapp which uses ngModel binding and at least it is working: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

**Comment by F3L1X79** [comment]
I wasn't able to make it working with a sub-attribute of a model, like:
`[(ngModel)]="mymodel.date"`

**Comment by kekeh** [comment]
@F3L1X79 

I don't see it is overriding mymodel completely. Check this example: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-access-modifier/sample-date-picker-access-modifier.ts

this file contains example of ngModel and reactive forms, but you can concentrate the ngModel

```javascript
// initialize to specific date 09.10.2018
private model = {
        mydate: <Object> {date: {year: 2018, month: 10, day: 9}},
        property1: true,
        property2: 'testing...'
};
```

After date selection the model is:
![screenshot_2017-03-02_17-16-45](https://cloud.githubusercontent.com/assets/11028839/23513305/348b1482-ff6c-11e6-8d46-9b3f3717cbb1.png)

**Comment by F3L1X79** [comment]
Shouldn't be property1 & property2 outside of `mydate` object in that case?

**Comment by kekeh** [comment]
mydate object is overridden but not property1 and property2.

**Comment by F3L1X79** [comment]
Yes, but there are not located at the root object anymore - they're passed into mydate attribute. (Or this is how it looks in your console). I'll go for further testing myself.

**Comment by F3L1X79** [comment]
Ok nevermind me, I completely misread the console...

Guess you can close this ticket, sorry a lot! (And BTW thank you for this nice plugin)
