### ISSUE TITLE
Need order of days to start with Sunday

### ISSUE THREAD

**Issue by JozefJarosciak** [kekeh/mydatepicker#207]
Our UI guidelines require for the order of days should start with Sunday, like this:
![3-1-2017 12-25-39 pm](https://cloud.githubusercontent.com/assets/3492464/23472890/564a4232-fe7c-11e6-8478-b7c0491aa445.jpg)

Would it be possible to have it configurable, so it doesn't always start with Monday, like this:
![calendar in unity](https://cloud.githubusercontent.com/assets/3492464/23472889/56485ae4-fe7c-11e6-8d2b-730271cb0420.jpg)

**Comment by kekeh** [comment]
There is option **firstDayOfWeek**. One of the following: mo, tu, we, th, fr, sa, su.

Set option firstDayOfWeek to 'su'
