### ISSUE TITLE
Is it possible to change the options attribute after date picker is rendered?

### ISSUE THREAD

**Issue by madukhai** [kekeh/mydatepicker#208]
I have two date picker in one page one is from and one is till (the mydaterangepicker doesn't match our requirement).

and I need to set the options(dateUntill) when the other one's value is set.

and I tried add a listener and change the option value, and the option(dateSince) is changed (console.log())

but the date picker still doesn't have that option

**Comment by kekeh** [comment]
You can change options dynamically. Probably you mean disableUntil and disableSince options.

Here is an example on how to change options of other date picker when the date is selected: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options
