### ISSUE TITLE
Feature request: Multi-select

### ISSUE THREAD

**Issue by isaacplmann** [kekeh/mydatepicker#209]
I'd like the ability to select a list of dates from an inline datepicker.

If you like the idea, I'd be happy to write a PR.

**Comment by isaacplmann** [comment]
I'd like to contribute to your library, just waiting for the go ahead.

**Comment by kekeh** [comment]
That is ok.

**Comment by isaacplmann** [comment]
Sorry, I found another way to solve my problem.
