### ISSUE TITLE
Issues while integrating with rollup

### ISSUE THREAD

**Issue by aqibshehzad** [kekeh/mydatepicker#212]
I my using your latest version of mydatepicker and have issues while integrating with rollup.

Issue detail are given below:

Template parse errors:↵Can't bind to 'myinputautofill' since it isn't a known property of 'input'. ("h" [ngClass]="{'invaliddate': invalidDate&&opts.indicateInvalidDate}" placeholder="{{placeholder}}" [ERROR ->][myinputautofill]="autoFillOpts" [ngStyle]="{'height': opts.height, 'line-height': opts.height, 'font"): t@0:389↵Can't bind to 'mydpfocus' since it isn't a known property of 'div'. (": opts.height}"></span></button></div></div><div class="selector" *ngIf="showSelector||opts.inline" [ERROR ->][mydpfocus]="opts.inline?'0':'1'" [ngStyle]="{'bottom': getSelectorTopPosition()}" [ngClass]="{'inlin"): t@0:1806↵Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("><div class="headermonthtxt"><input type="text" *ngIf="editMonth" class="monthinput" maxlength="10" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.monthTxt" (keyup)="userMonthInput($event)" (click)="$event.stop"): t@0:2636↵Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("/div><div class="headeryeartxt"><input type="text" *ngIf="editYear" class="yearinput" maxlength="4" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.year" (keyup)="userYearInput($event)" (click)="$event.stopPropa"): t@0:3997

What type of issue is that?

Systemjs.config.js:

(function (global) {
    // map tells the System loader where to look for things
    var map = {
        'app': '/Angular2/Appjs/app', // 'dist'
        '@angular': '/Angular2/node_modules/@angular',
        'angular2-in-memory-web-api': '/Angular2/node_modules/angular2-in-memory-web-api',
        'rxjs': '/Angular2/node_modules/rxjs',
        'mydatepicker': '/Angular2/node_modules/mydatepicker'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        'mydatepicker': {}
    }

    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'forms',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'router',
      'router-deprecated',
      'upgrade',
    ];
    // Individual files (~300 requests):
    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }
    // Bundled (~40 requests):
    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }
    // Most environments should use UMD; some (Karma) need the individual index files
    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    // Add package entries for angular packages
    ngPackageNames.forEach(setPackageConfig);
    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
})(this);

rollup-config.js:

/// <reference path="Appjs/app/main.js" />

import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
entry: 'Appjs/app/main.js',
dest: 'dist/build.js', // output a single application bundle
sourceMap: false,
format: 'iife',
onwarn: function(warning) {
    // Skip certain warnings

    // should intercept ... but doesn't in some rollup versions
    if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }
    // intercepts in some rollup versions
    if ( warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1 ) { return; }

    // console.warn everything else
    console.warn( warning.message );
},
plugins: [
    nodeResolve({jsnext: true, module: true}),
    commonjs({
        include: 'node_modules/rxjs/**',
        
        
    }),
    uglify()
]
}

here is my tsconfig file:
{
  "compilerOptions": {
	
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
	"outDir": "./Appjs/app"
  },
  "compileOnSave": true,
  "exclude": [
        "node_modules",
        "wwwroot"
  ]
}

Can anyone help to fix?

**Comment by kekeh** [comment]
One thing is that you have include the mydatepicker this way:
```javascript
(function (global) {
    System.config({
        paths: {
            'npm:': 'node_modules/'
        },
        map: {
            // Other components are here...

            'mydatepicker': 'npm:mydatepicker/bundles/mydatepicker.umd.js'
        },
        packages: {
        }
    });
})(this);
```

**Comment by aqibshehzad** [comment]
it didn't help either.

**Comment by aqibshehzad** [comment]
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'myinputautofill' since it isn't a known property of 'input'. ("h" [ngClass]="{'invaliddate': invalidDate&&opts.indicateInvalidDate}" placeholder="{{placeholder}}" [ERROR ->][myinputautofill]="autoFillOpts" [ngStyle]="{'height': opts.height, 'line-height': opts.height, 'font"): t@0:389
Can't bind to 'mydpfocus' since it isn't a known property of 'div'. (": opts.height}"></span></button></div></div><div class="selector" *ngIf="showSelector||opts.inline" [ERROR ->][mydpfocus]="opts.inline?'0':'1'" [ngStyle]="{'bottom': getSelectorTopPosition()}" [ngClass]="{'inlin"): t@0:1806
Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("><div class="headermonthtxt"><input type="text" *ngIf="editMonth" class="monthinput" maxlength="10" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.monthTxt" (keyup)="userMonthInput($event)" (click)="$event.stop"): t@0:2636
Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("/div><div class="headeryeartxt"><input type="text" *ngIf="editYear" class="yearinput" maxlength="4" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.year" (keyup)="userYearInput($event)" (click)="$event.stopPropa"): t@0:3997
Error: Template parse errors:
Can't bind to 'myinputautofill' since it isn't a known property of 'input'. ("h" [ngClass]="{'invaliddate': invalidDate&&opts.indicateInvalidDate}" placeholder="{{placeholder}}" [ERROR ->][myinputautofill]="autoFillOpts" [ngStyle]="{'height': opts.height, 'line-height': opts.height, 'font"): t@0:389
Can't bind to 'mydpfocus' since it isn't a known property of 'div'. (": opts.height}"></span></button></div></div><div class="selector" *ngIf="showSelector||opts.inline" [ERROR ->][mydpfocus]="opts.inline?'0':'1'" [ngStyle]="{'bottom': getSelectorTopPosition()}" [ngClass]="{'inlin"): t@0:1806
Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("><div class="headermonthtxt"><input type="text" *ngIf="editMonth" class="monthinput" maxlength="10" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.monthTxt" (keyup)="userMonthInput($event)" (click)="$event.stop"): t@0:2636
Can't bind to 'mydpfocus' since it isn't a known property of 'input'. ("/div><div class="headeryeartxt"><input type="text" *ngIf="editYear" class="yearinput" maxlength="4" [ERROR ->][mydpfocus]="2" [value]="visibleMonth.year" (keyup)="userYearInput($event)" (click)="$event.stopPropa"): t@0:3997
    at e.u (http://localhost:45284/bundles/AngularLib1:1:88464)
    at e [as constructor] (http://localhost:45284/Angular2/dist/build.js:8:18548)
    at new e (http://localhost:45284/Angular2/dist/build.js:8:20181)
    at t.parse (http://localhost:45284/Angular2/dist/build.js:12:4577)
    at t._compileTemplate (http://localhost:45284/Angular2/dist/build.js:17:3551)
    at http://localhost:45284/Angular2/dist/build.js:17:1101
    at Set.forEach (native)
    at t._compileComponents (http://localhost:45284/Angular2/dist/build.js:17:1072)
    at i (http://localhost:45284/Angular2/dist/build.js:16:30995)
    at n.invoke (http://localhost:45284/bundles/AngularLib1:1:95283)
    at i.run (http://localhost:45284/bundles/AngularLib1:1:91001)
    at http://localhost:45284/bundles/AngularLib1:1:88028
    at n.invokeTask (http://localhost:45284/bundles/AngularLib1:1:95976)
    at i.runTask (http://localhost:45284/bundles/AngularLib1:1:91657)
    at ht (http://localhost:45284/bundles/AngularLib1:1:86726)
    at e.u (http://localhost:45284/bundles/AngularLib1:1:88464)
    at e [as constructor] (http://localhost:45284/Angular2/dist/build.js:8:18548)
    at new e (http://localhost:45284/Angular2/dist/build.js:8:20181)
    at t.parse (http://localhost:45284/Angular2/dist/build.js:12:4577)
    at t._compileTemplate (http://localhost:45284/Angular2/dist/build.js:17:3551)
    at http://localhost:45284/Angular2/dist/build.js:17:1101
    at Set.forEach (native)
    at t._compileComponents (http://localhost:45284/Angular2/dist/build.js:17:1072)
    at i (http://localhost:45284/Angular2/dist/build.js:16:30995)
    at n.invoke (http://localhost:45284/bundles/AngularLib1:1:95283)
    at i.run (http://localhost:45284/bundles/AngularLib1:1:91001)
    at http://localhost:45284/bundles/AngularLib1:1:88028
    at n.invokeTask (http://localhost:45284/bundles/AngularLib1:1:95976)
    at i.runTask (http://localhost:45284/bundles/AngularLib1:1:91657)
    at ht (http://localhost:45284/bundles/AngularLib1:1:86726)
    at u (http://localhost:45284/bundles/AngularLib1:1:88464)
    at o (http://localhost:45284/bundles/AngularLib1:1:87610)
    at o (http://localhost:45284/bundles/AngularLib1:1:87363)
    at http://localhost:45284/bundles/AngularLib1:1:88019
    at n.invokeTask (http://localhost:45284/bundles/AngularLib1:1:95976)
    at i.runTask (http://localhost:45284/bundles/AngularLib1:1:91657)
    at ht (http://localhost:45284/bundles/AngularLib1:1:86726)
    at XMLHttpRequest.invoke (http://localhost:45284/bundles/AngularLib1:1:96885)

**Comment by aqibshehzad** [comment]
can you share some repo having both the things together (angular2 with mydatepicker and rollup)

**Comment by kekeh** [comment]
I don't know is there any that kind of project. Can you show @NgModule of your application?

You have import at least the following modules:
```javascript
@NgModule({
    imports: [BrowserModule, FormsModule, MyDatePickerModule],
    ....
})
```

**Comment by aqibshehzad** [comment]
we have created shared module which mean to be shared with all where globally in project and which is imported in app.module like this 

`import { SharedModule } from './modules/shared.module';`

and inside this shared module i have this 

`


import { NgModule }       from '@angular/core';
import { CommonModule }  from '@angular/common';
import { FormsModule }    from '@angular/forms';
import { RouterModule }   from '@angular/router';
import { HttpModule } from '@angular/http';
import {MyDatePicker} from 'mydatepicker/dist/my-date-picker.component';
@NgModule({
    imports: [
        CommonModule
       
    ],
    declarations: [
        MyDatePicker
    ],
    exports: [
        MyDatePicker
    ]
  
})
export class SharedModule {
}

`

what you suggest i am doing any mistake there?

**Comment by kekeh** [comment]
You try to import **MyDatePicker** which is wrong. You have to import **MyDatePickerModule** as follows:

```javascript
import {NgModule} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {BrowserModule} from '@angular/platform-browser';
import {MyDatePickerModule} from 'mydatepicker';

@NgModule({
    imports: [BrowserModule, FormsModule, MyDatePickerModule],
    ....
})
```

**Comment by aqibshehzad** [comment]
ok i will try and let you know. but by doing this it will give any error and the calendar is working fine but with rollup it give error basically in the final build section it added template of the calendar control and the string of type angular2 is not handled properly in the browser.

**Comment by aqibshehzad** [comment]
it didnot help either as when i include in the aap module it will  bundle all of the files including umd type files which are already bundled file and include in the final build if i removed it will not include those files.

**Comment by kekeh** [comment]
Did you find a solution?

**Comment by kekeh** [comment]
I close this issue because no answer. You can reopen this issue if you have same problem.

**Comment by samHuaman** [comment]
When I try to import like this: 
`import { MyDatePickerModule } from 'mydatepicker';`
gives me this error: "Cannot find module 'mydatepicker'".
So I import in this way:
`import { MyDatePickerModule } from 'mydatepicker/src/my-date-picker';`
but when I compile it, show me this in the explorer console:
compiler.es5.js:1689 Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'my-date-picker'.

anf this:
'my-date-picker' is not a known element:

A little help, please.

**Comment by kekeh** [comment]
@samHuaman 

You have to import **MyDatePickerModule** as follows:

```javascript
import {NgModule} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {BrowserModule} from '@angular/platform-browser';
import {MyDatePickerModule} from 'mydatepicker';

@NgModule({
    imports: [BrowserModule, FormsModule, MyDatePickerModule],
    ....
})
```

Check folder **node_modules/mydatepicker** that there is **index.d.ts** and **index.js** files. Some users npm installs invalid package of mydatepicker. Try to install it again:
  - npm remove mydatepicker
  - npm install mydatepicker --save

**Comment by samHuaman** [comment]
Now it imports in the right way, but it still throwing me this:
'my-date-picker' is not a known element.

Here is my app.module.ts:
```
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { MyDatePickerModule } from 'mydatepicker';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    MyDatePickerModule,
    ...
  ],
  providers: [
    ...
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And the component where I'm calling it:
```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { IMyDpOptions } from 'mydatepicker';

declare var jQuery:any;

@Component({
    selector: 'user-create',
    templateUrl: 'user-create.component.html',
    providers: [FormBuilder, ModalComponent]
})

export class UserCreateComponent implements OnInit {

    ExpireDate: string = '';

    date: Date = new Date();

     private myDatePickerOptions: IMyDpOptions = {
        dateFormat: 'dd-mm-yyyy'
    };

    private model: Object = { 
        date: { 
            year: this.date.getFullYear(), 
            month: this.date.getMonth(), 
            day: this.date.getDay()
        } 
    };
   
   ...
```

And in the html file:
```
<my-date-picker name="ExpireDate" [options]="myDatePickerOptions"
             [(ngModel)]="ExpireDate" required></my-date-picker>
```
