### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by edwinmoss** [kekeh/mydatepicker#216]
We are getting the following [object Object] our html:

input aria-label="Calendar input field" class="selection" ngtype="text" ng-reflect-klass="selection" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" ng-reflect-opts="[object Object]" maxlength="10" placeholder="" style="height: 34px; line-height: 34px; border: none; padding-right: 30px;"

Any ideas?

**Comment by kekeh** [comment]
It is Angular specific debug information in development mode. If you want to remove them run your application in production mode. For example:

```javascript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';

// Set production mode
enableProdMode();

// or
platformBrowserDynamic().bootstrapModule(YourAppModule, {useDebug: false});
```

**Comment by edwinmoss** [comment]
Thanks!

Is there any plan to support class="ng-pristine ng-invalid ng-touched"?

**Comment by kekeh** [comment]
There is already. You can check them from the **my-date-picker** tag in HTML. They are not in the input field.

![screenshot_2017-03-10_11-08-54](https://cloud.githubusercontent.com/assets/11028839/23789081/04d0e85e-0582-11e7-8975-fff2e6127c5d.png)

**Comment by edwinmoss** [comment]
hmm… this is what we are seeing:

<my-date-picker _ngcontent-ilb-37="" name="fromDate" required="" inputvaluerequired="false"><div class="mydp" style="width: 100%;"><div class="selectiongroup"><input aria-label="Calendar input field" class="selection" ngtype="text" maxlength="10" placeholder="" style="height: 34px; line-height: 34px; border: none; padding-right: 30px;"><div class="selbtngroup" style="height: 34px;"> <button aria-label="Open Calendar" class="btnpicker btnpickerenabled btnleftborder" type="button"><span class="icon icon-calendar" style="line-height: 34px;"></span></button></div></div></div></my-date-picker>

no notion of class

—Ed

Ed Moss
ed.moss@4ssom.com
801-310-1811 (mobile)

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of this email is prohibited.









On Mar 10, 2017, at 2:12 AM, kekeh <notifications@github.com> wrote:

There is already. You can check them from the my-date-picker tag in HTML. They are not in the input field.

 <https://cloud.githubusercontent.com/assets/11028839/23789081/04d0e85e-0582-11e7-8975-fff2e6127c5d.png>

**Comment by kekeh** [comment]
Try for example this option: https://github.com/kekeh/mydatepicker#3-ngmodel-binding

**Comment by edwinmoss** [comment]
I did successfully reproduce the desired result with your example. However, we are using the control in a formGroup and ngModel is not possible in a formGroup/reactive form.

This is what we are doing:

  <form class="form-horizontal" [formGroup]="productOrderForm" (ngSubmit)="onSubmitSubjectOptions($event)">
      <my-date-picker [options]="myDatePickerOptions" [attr.inputValueRequired]="subjectOfInterest.monitoring" name="fromDate" [selDate]="subjectOfInterest.birthDate" (dateChanged)="onFromDateChanged($event)" required></my-date-picker>

any ideas?

Thanks so much for your help!

—Ed

Ed Moss
ed.moss@4ssom.com
801-310-1811 (mobile)

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of this email is prohibited.









On Mar 10, 2017, at 8:35 AM, kekeh <notifications@github.com> wrote:

Try for example this option: https://github.com/kekeh/mydatepicker#3-ngmodel-binding <https://github.com/kekeh/mydatepicker#3-ngmodel-binding>

**Comment by kekeh** [comment]
If you are using reactive forms option you need a **formControlName** attribute as follows:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions"
                    formControlName="myDate"></my-date-picker>
```

Check this example: https://github.com/kekeh/mydatepicker#2-reactive-forms

Then you get **pristine**, **invalid**, **touched** and others as follows:
```javascript
constructor(private formBuilder: FormBuilder) { }

ngOnInit() {
    this.myForm = this.formBuilder.group({
        myDate: ['', Validators.required]   // not initial date set - required set
    });
}

printControlStatus(): void {
    console.log('Value: ', this.myForm.controls['myDate'].value,
             ' - Valid: ', this.myForm.controls['myDate'].valid,
             ' - Invalid: ', this.myForm.controls['myDate'].invalid,
             ' - Dirty: ', this.myForm.controls['myDate'].dirty,
             ' - Pristine: ', this.myForm.controls['myDate'].pristine,
             ' - Touched: ', this.myForm.controls['myDate'].touched);
}
```

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

the example contains ngModel and reactive forms example

**Comment by edwinmoss** [comment]
Wow, I sure made a mess of this. Sorry this was such an implementation issue.

Thank you for your patience.
