### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'my-date-picker'

### ISSUE THREAD

**Issue by javierrobles08** [kekeh/mydatepicker#219]
Hi it says Can't bind to 'options' since it isn't a known property of 'my-date-picker', im using angular-cli and also if i remove the options attribute it says "'my-date-picker' is not a known element"

**Comment by kekeh** [comment]
Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

**Comment by javierrobles08** [comment]
it was the Reactive Forms i forget add it on the Form Group, thank you!
