### ISSUE TITLE
v1.7.6 with "ERROR in MyDatePickerModule is not an NgModule"

### ISSUE THREAD

**Issue by nunofmendes** [kekeh/mydatepicker#220]
I am having trouble using MyDatePickerModule. Whenever I run: 

`ng serve`

It shows the following error message:

ERROR in MyDatePickerModule is not an NgModule
webpack: Failed to compile.

I am using: @angular/cli: 1.0.0-rc.2

Any sugestions? I noticed this happened in older versions of MyDatePickerModule. How can I solve this?

Thanks

**Comment by kekeh** [comment]
I tested mydatepicker version 1.7.6 with @angular/cli: 1.0.0-rc.2 and it worked ok. 

Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

Can you share your app.module.ts file?

**Comment by kekeh** [comment]
Closing this because no answer.
