### ISSUE TITLE
How to open the calendar by clicking anywhere in the input field

### ISSUE THREAD

**Issue by suchyn11** [kekeh/mydatepicker#222]
Hi, 

I need to be able to open the calendar by clicking anywhere in the component, not just the icon. I am listening to (click) event (on the whole component), which then triggers increasing the selector variable, which is binded like [selector]="selector"

However, I get an error saying this:
Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

When I add a button, which triggers increasing the value, everything is fine (because I am not listening on whole component) I also tried the handle the event like event.stopPropagation(), but with no luck

Could you please advise?
Thanks!

**Comment by kekeh** [comment]
There is option openSelectorOnInputClick. Option editableDateField must be false.

**Comment by kormic** [comment]
I am having a similar issue, I don't know if I should open a new issue for this.
I have set my option to editableDateField to false and openSelectorOnInputClick to true but when I click on the date picker I get an exception:

Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

If i click on the icon the calendar opens and closes just fine. I using two way bind to handle my dates.

**Comment by kekeh** [comment]
Have you set own options to both date pickers?

**Comment by kormic** [comment]
Actually....no! I will try that I 'll let you know...

Thank you for your time!

**Comment by suchyn11** [comment]
I followed your advice, but got the same error as @kormic 

The options variable is set to all of the datepickers, so there should not be a problem

**Comment by kekeh** [comment]
I tried two date pickers with same options:
- openSelectorOnInputClick: true,
- editableDateField: false,

and they worked ok.

@kormic and @suchyn11 
You can use **disableUntil** and **disableSince** options to prevent user select "wrong" date. Here is example setting disableUntil to endDate date picker: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

Also the input field can be editable if you do it like example above.

**Comment by kekeh** [comment]
I don't know what is the problem but can you try now version 1.7.8.

**Comment by Ailrun** [comment]
I have a similar issue with this.

1. I use reactive form of angular 2.4.0
1. I use mydatepicker 1.7.10
1. I use just single mydatepicker with other types of form inputs.
1. I set `editableDateField` as `false`, and `openSelectorOnInputClick` as `true`.
1. App displays `Expression has changed after ...` when I click input area.
1. App works well when I click calendar icon.

**Comment by Ailrun** [comment]
@kekeh 
I have a similar issue.

1. I use reactive form of angular 2.4.0
1. I use mydatepicker 1.7.10
1. I use just single mydatepicker with other types of form inputs.
1. I set `editableDateField` as `false`, and `openSelectorOnInputClick` as `true`.
1. App displays `Expression has changed after ...` when I click input area.
1. App works well when I click calendar icon.

**Comment by kekeh** [comment]
@Ailrun 

Can you show your package.json. I try to reproduce the error. Are you using angular-cli or something else predefined project configuration?

**Comment by Ailrun** [comment]
@kekeh
To your reproducing, I retry with test project, with angular-cli 1.0.0-rc.1 creating project

1.
```
$ ng new test-datepicker
...
$ cd test-datepicker
$ yarn add mydatepicker
```

2. Change following files

app.module.ts
``` typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MyDatePickerModule } from 'mydatepicker';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    HttpModule,
    MyDatePickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

app.components.ts
``` typescript
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { IMyOptions } from 'mydatepicker';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public form: FormGroup;

  public datepickerOptions: IMyOptions;

  public constructor() {
    this.form = new FormGroup({});
    this.form
      .setControl('date', new FormControl(
        '', []
      ));
    this.datepickerOptions = {
      editableDateField: false,
      openSelectorOnInputClick: true
    };
  }
}
```

app.component.html
``` typescript
<form [formGroup]="form">
  <my-date-picker [options]="datepickerOptions"
                  formControlName="date">
  </my-date-picker>
</form>
```

3. `ng s` or `ng serve`.

4. click input area.

**Comment by kekeh** [comment]
Thanks @Ailrun 

I was able to reproduce error with your instructions and I did one fix. You can now try version 1.7.12.

**Comment by Ailrun** [comment]
@kekeh
Ye It now works on real app. Thanks for your fast response!

**Comment by Ailrun** [comment]
@suchyn11 @kormic I think you guys need to check this update too.

**Comment by kormic** [comment]
Busy days...as soon as i try this out I will let you know.

**Comment by suchyn11** [comment]
Still repro. When the first click is on icon, it does not crash and i can click on the input to open the datepicker. When the first click is on the input, it crashes giving me the same error as above.

my version 1.7.14

**Comment by kekeh** [comment]
I created another fix. Try to update version 1.7.15.

@suchyn11 
Are using Chrome browser?

**Comment by Ailrun** [comment]
That's weird. For my case, it works well in both chrome and firefox

**Comment by suchyn11** [comment]
OMG...

weird indeed, because whilst it doesnt work on my local environment (on my laptop), when it accidentally got deployed on Firebase server, everything works perfectly well..

It is this kind of issue which just makes you shake your head, I guess..

@all Thanks for help, @kekeh good job 👍
