### ISSUE TITLE
placeholder in safari is not removed after picking date

### ISSUE THREAD

**Issue by tomasznastaly** [kekeh/mydatepicker#227]
I found a bug. On Safari browser, after picking a date, the placeholder is not removed from input:
[
![placeholder](https://cloud.githubusercontent.com/assets/16205492/24191764/08448ce2-0eed-11e7-8c31-f4a905485c40.JPG)
](url)

is possible to fix it?
thanks!

**Comment by kekeh** [comment]
Are you able to reproduce error here: http://kekeh.github.io/mydatepicker/

**Comment by kekeh** [comment]
Probably you are using quite Old version?

**Comment by kekeh** [comment]
I am not able to reproduce with iPad Safari. Update mydatepicker the latest version 1.7.16.

Closing this issue because no answer.
