### ISSUE TITLE
Feature Request: Day selection of past/next select date

### ISSUE THREAD

**Issue by gearsandcode** [kekeh/mydatepicker#228]
Currently selecting a day from the past or next month will change the ui to that month. It would be nice if it would also select that day in addition.

**Comment by m3hari** [comment]
+1

**Comment by galkinrost** [comment]
+1

**Comment by mscahill** [comment]
+1

**Comment by alalonde** [comment]
I don't think you'd want to change this to be the new default, but having it be a config toggle would be nice.

**Comment by kekeh** [comment]
I added new option **allowSelectionOnlyInCurrentMonth**. If you set it to **false** it allows select a date from the past or the next months.

This is in version **2.0.32**.
