### ISSUE TITLE
Feature Request: Expose focus and blur events

### ISSUE THREAD

**Issue by gearsandcode** [kekeh/mydatepicker#229]
I need to utilize a floating label and need to know when the input field is focused or blurred.

**Comment by kekeh** [comment]
I added focusBlur event to input box. More info from here: https://github.com/kekeh/mydatepicker#focusblur-callback

New version is 1.7.8

**Comment by gearsandcode** [comment]
Thanks!

Now I had to do this though.. haha
```
/*
TODO - update to 1.7.8, scrap the renderer.listeners and refactor as the package was
  literally updated to support this within minutes of my finishing this.
  see: https://github.com/kekeh/mydatepicker/commit/4ce0839eb415a6c60efbecabc35a28673103c64c
*/

**Comment by kekeh** [comment]
Try version 1.7.9 instead. Event name is inputFocusBlur: https://github.com/kekeh/mydatepicker#inputfocusblur-callback

**Comment by gearsandcode** [comment]
TODO added to update TODO about removing TODOs.

**Comment by gearsandcode** [comment]
@kekeh sorry that this is so specific to my use case, but can this callback return the event.value that  the inputFieldChanged callback returns? I need to know about the focus and blur events and if the field contains a value as the formControl value is empty when the date is not valid.

**Comment by kekeh** [comment]
I changed functionality of inputFocusBlur event. More info check from here: https://github.com/kekeh/mydatepicker#inputfocusblur-callback

New version is 1.7.11.
