### ISSUE TITLE
Bind to TypeScript Date object

### ISSUE THREAD

**Issue by BenDevelopment** [kekeh/mydatepicker#233]
Hi,

First thank you for your work!
Do you plan to add support to bind to a Date type object?

Ben

**Comment by kekeh** [comment]
If you are using ngModel or reactive forms you can set initial value as follows: 

{date: {year: 2018, month: 10, day: 9}}

when you select some date the model contains date in [IMyDate](https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date.interface.ts) format, formatted date, epoc timestamp and also there is also jsdate property which is javascript date object of selected date.

No plan to change this.
