### ISSUE TITLE
Question when using disableSince and enableDays together

### ISSUE THREAD

**Issue by Tgure** [kekeh/mydatepicker#234]
I am trying to only have certain days available and it is working using disableSince and enableDays together but when you navigate backwards in the calendar you can no longer navigate back forward even though those months do have enabled days.  Setting disableHeaderButtons="false" does not help either.  Is there a way to possibly just highlight days based on enableDays and not disable other days or allow the header buttons to navigate forwards and backwards?  Thanks

**Comment by kekeh** [comment]
The **disableHeaderButtons** doesn't help if you are using **minYear** and **maxYear**. But it helps if you are using **disableSince** and **disableUntil**. This should work:

For example:
```javascript
disableSince: {year: 1900, month: 1, day: 1},
enableDays: [{year: 2017, month: 3, day: 29}, ...],
disableHeaderButtons: false,
minYear: 2000,
maxYear: 2030
```

**Comment by Tgure** [comment]
@kekeh Thanks that worked.
