### ISSUE TITLE
Any option to hide disabled dates from picker?

### ISSUE THREAD

**Issue by iagocanalejas** [kekeh/mydatepicker#235]
I had set the option `disableSince: {year: 2012, month: 1, day: 1},` and i would like this dates not to be showed in the picker. 

Is this possible?

**Comment by kekeh** [comment]
Date picker automatically prevent to navigate months which are fully disabled by **disableSince** or **disableUntil** options if the **disableHeaderButtons** option is **true** which is the default value.

You can also use **minYear** or **maxYear** options to prevent to navigate specific year. The **disableHeaderButtons** option doesn't affect the minYear or maxYear options.

This is quite new feature so update date picker the latest version: 1.7.15

**Comment by kekeh** [comment]
You can set default month using this: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

if you are using default month attribute there is not selected date (calendar shows default month when it is opened).

If you want to set default date (date selected) there is many options:
1. If you are using ngModel binding read this: https://github.com/kekeh/mydatepicker#3-ngmodel-binding
2. If you are using reactive forms read this: https://github.com/kekeh/mydatepicker#2-reactive-forms
3. If you are not using both of above you can use selDate attribute: https://github.com/kekeh/mydatepicker#seldate-attribute
