### ISSUE TITLE
Something's wrong with front

### ISSUE THREAD

**Issue by NaLLiFFuNT** [kekeh/mydatepicker#236]
Could you provide information what front should include into my app. 

Also how to customize picker view? Is the only way creating fork? I do hope there're other solutions.

**Comment by kekeh** [comment]
Here is installation instructions: https://github.com/kekeh/mydatepicker#installation

You can try to override styles. Check this issue: https://github.com/kekeh/mydatepicker/issues/118

Also creating own version of the component is one option to set own style: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by iagocanalejas** [comment]
Yeah but when you first open the picker you need to navigate back through blocked years.
Is there a way to set the initial/default year, month and day?¿

**Comment by NaLLiFFuNT** [comment]
Thanks, i double checked with fronts, my custom front had overridden front of this picker. Everything is okay.
