### ISSUE TITLE
Closing the selector not possible

### ISSUE THREAD

**Issue by CodeNashor** [kekeh/mydatepicker#237]
I researched your code and I don't see any possiblity to close the selector.
You said something with '[selector]=selector' will open/close the selector. This does exactly nothing, also your karma-tests does not cover this case.

My datepicker won't close on date-select and I don't know why, I used your example code.

I just wanna know, if there is a possibility to close the selector manually (per code)?

**Comment by kekeh** [comment]
When you select a date calendar should close automatically. If not there are some problems. Can you see any error on the console of the browser?

You can programmetically open/close calendar by selector attribute.

**Comment by CodeNashor** [comment]
I just used your code-example on http://kekeh.github.io/mydatepicker/ .
Exact same code, still not working.

Also my angular-version and some others are the same.
Im using webpack 2 and grunt not gulp. I dont know, but I think there should be the problem.

I debugged your code and he sets the showSelector correctly on false. But in the Angular code (ZoneXXX.js), he does not fire a 'invoke' function, which does a 'apply' to bind the new data to the HTML Template.

No console errors, IE/Firefox/Chrome same behaviour.

Im trying some other things and post again soon.

**Comment by CodeNashor** [comment]
Ok I tried the same in a new project with same angular version, but without grunt and webpack (with ng serve) and it works.

I really don't know what causes the problem, but here my package.json:

`{
  "name": "XXX",
  "version": "2.0.0",
  "dependencies": {
    "@angular-redux/store": "6.0.1",
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/router": "3.4.4",
    "@angular/upgrade": "2.4.4",
    "@types/angular": "^1.5.16",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-local-storage": "^0.1.33",
    "@types/angular-mocks": "^1.5.5",
    "@types/angular-resource": "^1.5.6",
    "@types/angular-sanitize": "^1.3.3",
    "@types/angular-spinner": "^0.5.30",
    "@types/angular-toastr": "^1.6.30",
    "@types/angular-translate": "^2.4.33",
    "@types/jasmine": "2.5.41",
    "@types/jquery": "^2.0.33",
    "@types/lodash": "4.14.56",
    "@types/lodash-es": "4.14.3",
    "@types/materialize-css": "^0.97.31",
    "@types/ng-file-upload": "^11.1.30",
    "@types/pickadate": "^3.5.27",
    "@types/webpack-env": "^1.13.0",
    "ag-grid": "^8.2.0",
    "ag-grid-angular": "^8.2.0",
    "angular": "1.5.11",
    "angular-animate": "1.5.11",
    "angular-i18n": "1.5.11",
    "angular-local-storage": "0.5.0",
    "angular-messages": "1.5.11",
    "angular-mocks": "1.5.11",
    "angular-resource": "1.5.11",
    "angular-sanitize": "1.5.11",
    "angular-spinner": "1.0.0",
    "angular-toastr": "2.1.1",
    "angular-translate": "2.13.1",
    "angular-translate-loader-partial": "2.13.1",
    "angular-translate-loader-static-files": "2.13.1",
    "angular-translate-loader-url": "2.13.1",
    "angular-ui-router": "1.0.0-rc.1",
    "angular-utils-pagination": "0.11.1",
    "angular2-jwt": "0.1.28",
    "bourbon": "4.2.7",
    "core-js": "2.4.1",
    "google-code-prettify": "1.0.5",
    "jquery": "2.2.4",
    "lodash-es": "4.17.4",
    "material-design-icons": "3.0.1",
    "materialize-css": "0.97.7",
    "moment": "2.17.1",
    "mydatepicker": "1.7.15",
    "ng-draggable": "1.0.0",
    "ng-file-upload": "12.2.13",
    "ng-redux": "3.4.0-beta.1",
    "ng2-datepicker": "^1.8.3",
    "pdfjs-dist": "1.6.483",
    "redux": "3.6.0",
    "redux-freeze": "0.1.5",
    "redux-localstorage": "0.4.1",
    "redux-logger": "2.7.4",
    "redux-observable": "0.14.1",
    "redux-observable-decorator": "1.0.0",
    "rxjs": "5.0.3",
    "spin.js": "2.3.2",
    "webpack-hot-middleware": "2.17.1",
    "zone.js": "0.7.6"
  },
  "repository": {},
  "devDependencies": {
    "@angular/compiler-cli": "2.4.4",
    "@angular/language-service": "^2.4.10",
    "@types/jasmine": "^2.5.35",
    "angular2-template-loader": "~0.6.2",
    "autoprefixer": "~6.7.0",
    "awesome-typescript-loader": "~3.0.8",
    "babel-core": "~6.22.1",
    "babel-loader": "~6.4.0",
    "babel-preset-es2016": "~6.22.0",
    "css-loader": "~0.26.1",
    "exports-loader": "~0.6.4",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "~0.10.1",
    "grunt": "~1.0.1",
    "grunt-cli": "~1.2.0",
    "grunt-concurrent": "~2.3.0",
    "grunt-contrib-clean": "~1.0.0",
    "grunt-contrib-copy": "~1.0.0",
    "grunt-contrib-jshint": "~1.1.0",
    "grunt-contrib-watch": "~1.0.0",
    "grunt-force-task": "~2.0.0",
    "grunt-karma": "~2.0.0",
    "grunt-keepalive": "~1.0.0",
    "grunt-newer": "~1.2.0",
    "grunt-sass-lint": "~0.2.0",
    "grunt-shell": "~2.1.0",
    "grunt-svgmin": "~4.0.0",
    "grunt-text-replace": "~0.4.0",
    "grunt-tslint": "~4.0.0",
    "html-loader": "~0.4.5",
    "html-webpack-plugin": "~2.28.0",
    "ignore-loader": "~0.1.1",
    "imports-loader": "~0.7.0",
    "jasmine-core": "~2.5.2",
    "jasmine-reporters": "~2.2.0",
    "jasmine-spec-reporter": "~3.2.0",
    "jshint-stylish": "~2.2.0",
    "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-coverage": "~1.1.0",
    "karma-fixture": "~0.2.6",
    "karma-jasmine": "~1.1.0",
    "karma-json-fixtures-preprocessor": "0.0.6",
    "karma-junit-reporter": "~1.2.0",
    "karma-ng-html2js-preprocessor": "~1.0.0",
    "karma-phantomjs-launcher": "~1.0.1",
    "karma-source-map-support": "~1.2.0",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "~2.0.1",
    "load-grunt-tasks": "~3.5.0",
    "mkdirp": "~0.5.1",
    "ng-annotate-loader": "~0.2.0",
    "node-sass": "~4.3.0",
    "phantomjs-prebuilt": "~2.1.13",
    "postcss-loader": "~1.3.3",
    "protractor": "~5.0.0",
    "protractor-jasmine2-screenshot-reporter": "~0.3.2",
    "raw-loader": "~0.5.1",
    "reflect-metadata": "^0.1.9",
    "resolve-url-loader": "~2.0.2",
    "sass-lint": "~1.10.2",
    "sass-loader": "~6.0.2",
    "string-replace-loader": "~1.0.5",
    "style-loader": "~0.13.2",
    "time-grunt": "~1.4.0",
    "to-string-loader": "~1.1.5",
    "tslint": "~4.3.1",
    "tslint-eslint-rules": "~3.2.3",
    "typescript": "~2.1.6",
    "uglify-js": "^2.8.10",
    "uglifyjs-webpack-plugin": "^0.3.0",
    "url-loader": "~0.5.7",
    "webpack": "~2.2.1",
    "webpack-dev-server": "~2.4.1"
  },
  "engines": {
    "node": ">=4.2.0"
  },
  "scripts": {
    "start": "webpack-dev-server --config config/webpack-dev-server.conf.js --hot --inline",
    "test": "grunt test"
  }
}
`

If I find the solution, I will let you know it.

**Comment by kekeh** [comment]
Is this still valid issue?

**Comment by kekeh** [comment]
Closing this issue because no answer. You can reopen the issue if you have the same problem.
