### ISSUE TITLE
Reactive forms + disabling formControl doesn't work

### ISSUE THREAD

**Issue by NaLLiFFuNT** [kekeh/mydatepicker#239]
I use this picker with Reactive forms. if i disable form control, picker doesn't come disabled.
I've found temporary solution, i clone options object of the picker, and change componentDisabled property.
However, i believe, it should work under the hood.

my controller's code looks like this
`
 onDisableDateField() {
   this.form.get('date').disable();
  }
`

**Comment by BrainCrumbz** [comment]
Not sure how are you actually working with the full reactive form, maybe a reduced sample could help. Anyway, in case it may help, this is how we disable a whole form with all its input controls:

1. In form `fieldset` node, bind `disabled` to some component boolean property, e.g. `isFormDisabled`
1. In component code, when needed, set that property to true/false

For example:

```html
  <form [formGroup]="searchForm" accept-charset="UTF-8" role="form">
    <fieldset [disabled]="disabled">
      <!-- ... other controls ... --->
      <my-date-picker formControlName="dateFrom">
      </my-date-picker>
      <!-- ... other controls ... --->
    </fieldset>
  </form>
```

There's only a small visual issue, as the datepicker field and button do not **look** disabled (as for other Twitter Bootstrap controls), but it is actually functionally disabled. HTH

**Comment by kekeh** [comment]
Now this works:
```javascript
onDisableDateField() { this.form.get('date').disable(); }
```
Update the latest version 2.0.3.
