### ISSUE TITLE
"openSelectorOnInputClick" option gives error

### ISSUE THREAD

**Issue by jmat992** [kekeh/mydatepicker#240]
Using "openSelectorOnInputClick" option in the config options and clicking on the input field shows error: "Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'." error? I have correctly set inline : flase and editableField: false in options as shown in documentation. Any suggestions?

**Comment by kekeh** [comment]
Are you using latest version 1.7.16? Recently I fixed this kind of bug.

**Comment by jmat992** [comment]
Currently I am using version 1.7.6.

**Comment by kekeh** [comment]
You have to update the latest version. It fixes the error.

**Comment by danhastings** [comment]
this is an issue with the latest version from npm. i am having the same issue

**Comment by kekeh** [comment]
What kind of environment you have? I will try to reproduce.

**Comment by kekeh** [comment]
I fixed this bug. Try version **1.9.9** from npm.

**Comment by danhastings** [comment]
works now! thanks

**Comment by Spardevil** [comment]
openSelectorOnInputClick gives error. I'm using version 2.0.31. Getting this 
 `ReferenceError: openSelectorOnInputClick is not defined`

**Comment by kekeh** [comment]
I tested the option and it worked ok. You can also test functionality here: http://kekeh.github.io/mydatepicker/

uncheck the **Editable date field** checkbox and then click the input box. I don't see any error messages.

You have to set **editableDateField** option also to **false** if you set the **openSelectorOnInputClick** to **true**.
