### ISSUE TITLE
dynamically set require validation in options not working

### ISSUE THREAD

**Issue by hewstone** [kekeh/mydatepicker#241]
First of all, love the date picker!!! You've done a great job! 

In short, here is the issue.  The InputValueRequired cannot be set dynamically in the options.

I've seen the other issues on validation however, they don't tend to talk about how to dynamically add a "require" validation.  I have a case where if STATUS is set to a particular value then the DATE field needs to be required.  In my template bound to the [options] with the _inputValueRequired_ initally set to false.  Then when the status changes to a value where the date is required I set it to true.  It does not appear to accept honor that new updated value.  

Also why do I have to specify "required" attribute on the control in my template in order to make form validation work if i already specify it in the options?

Just a thought.  It might be a bit less confusing to support the angular directive "[required]" to pass that value all the way down to the input control in the template.  Then form validation could work as a typical form control

**Comment by hewstone** [comment]
I found a work around for this, however, I'd like to request passing the [required] from the control all the way down to the binding on the input and doing away with the inputValueRequired on the options.  This would be more consistent with the way angular shows in their documentation.  Here is the work around:

The binding to the [options] property is not doing a deep watch and just watching the reference to the assigned object, it will never get updated if a property changes.  The way to make it update is to set it to a completely different object.  This changes the reference and causes it to rebind to the template.

Below is a solution that worked for me.

```
<my-date-picker name="actualstartdate" [options]="datepickerRequiredOptions"
[(ngModel)]="task.ActualStartDate" #actualstartdate="ngModel" 
[required]="isCompletedRequiredField()"></my-date-picker>

 <div *ngIf="actualstartdate.errors" class="text-danger">
     <div [hidden]="!actualstartdate.errors.required">
           Required
     </div>
  </div>
```


```
   this.datepickerRequiredOptions: IMyOptions = {
       dateFormat: 'mm/dd/yyyy',
    }

 private isDateRequiredField() {
        var required = false;
        if (this.task && this.task.Status) {
            required = this.task.Status.toUpperCase().indexOf('COMPLETE') > -1
        }
       
        //this works IF you set it to a new object.  You cannot just modify the existing object
        this.datepickerRequiredOptions = {
            dateFormat: this.datepickerRequiredOptions.dateFormat,
            inputValueRequired: required
        };
        return required;
    }
```

**Comment by kekeh** [comment]
Hi @hewstone 

The **inputValueRequired** option is unnecessary. You can forget it and set **required** field as follows in case of ngModel binding:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    [(ngModel)]="model.mydate" required></my-date-picker>
```
or in case of reactive forms:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    formControlName="myDate"></my-date-picker>
```

```javascript
ngOnInit() {
    this.myForm = this.formBuilder.group({
        myDate: ['', Validators.required]   // not initial date set
    });
}
```

Here is an example on how to modify options (disableUntil): https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

**Comment by pratiksha-chandel** [comment]
Not working for me , help please .
logic is implemented just want to heilights datepicker with red color and show error popup message . 
like required works in input statement .

<my-date-picker *ngIf="!!isEditable" #changeOrCancelDate formControlName="changeOrCancelDate" [options]="myDatePickerOptions"  [defaultMonth]="defaultMonth"
                          [placeholder]="utilService.placeholder" [ngModel]="orderCustomProperties.changeOrCancelDate | stringToDate"
                          (ngModelChange)="orderCustomProperties.changeOrCancelDate = utilService.convertDateToString($event)" [options]="myOptions"
                          (dateChanged)="onDateChanged($event)"></my-date-picker>
