### ISSUE TITLE
Red border if option inputValueRequired is not working in Chrome and IE

### ISSUE THREAD

**Issue by kristina-san** [kekeh/mydatepicker#242]
Hello,
I used the date picker with this options:

`private myDatePickerOptions: IMyOptions = {    `
`showInputField: true,    `
`dateFormat: 'dd.mm.yyyy',`
`width: '223px',`
`inputValueRequired: true`
`};`

in a reactive form
`this.myForm = this.formBuilder.group({`
`    myDate: [this.dateOfBirth, Validators.required]`
`});`

`<my-date-picker name="dateOfBirth" [options]="myDatePickerOptions" formControlName="dateOfBirth"></my-date-picker>`

With Firefox version 52.0.2: if I delete the input, the border gets red because of the inputValueRequired option.
![firefox](https://cloud.githubusercontent.com/assets/4233759/24614154/b3b8cae2-188a-11e7-8632-658ac7ad28b2.PNG)

With Chrome version 59.0 and with IE11: if I delete the input, nothing happens. 
![chrome](https://cloud.githubusercontent.com/assets/4233759/24614213/dbf05912-188a-11e7-9dfd-88ba41027ad7.PNG)

Is it a known issue?
Thank you.

**Comment by kekeh** [comment]
The **inputValueRequired** option is unnecessary. You can forget it and set **required** field as follows in case of ngModel binding:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    [(ngModel)]="model.mydate" required></my-date-picker>
```
or in case of reactive forms:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    formControlName="myDate"></my-date-picker>
```

```javascript
ngOnInit() {
    this.myForm = this.formBuilder.group({
        myDate: ['', Validators.required]   // not initial date set
    });
}
```
