### ISSUE TITLE
selDate not working

### ISSUE THREAD

**Issue by daituzhang** [kekeh/mydatepicker#244]
Using mydatepicker@1.7.16 

I tried both
"the string must be in the same format as the dateFormat option is. For example '2016-06-26'
the object must be in the IMyDate format. For example: {year: 2016, month: 6, day: 26}"

But none of above work, and no error message showed up either.
Is there a way that I can fix it?

Thank you!

**Comment by kekeh** [comment]
If you are using ngModel binding or reactive forms they override the selDate attribute. In those case you have set initial value in the following ways.

**ngModel binding**

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    [(ngModel)]="model"></my-date-picker>
```

```javascript
// for example set 4.4.2017 to initial value
private model: Object = {date: {year: 2017, month: 4, day: 4}};
```
**reactive forms**

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    formControlName="myDate"></my-date-picker>
```

```javascript
ngOnInit() {
    // for example set 4.4.2017 to initial value
    this.myForm = this.formBuilder.group({
        myDate: [{date: {year: 2017, month: 4, day: 4}}, Validators.required]  
    });
}
```

**Comment by daituzhang** [comment]
Thank you! That fixes my problem!
