### ISSUE TITLE
ISSUE "Pointer" facing the wrong way when setting "openSelectorTopOfInput = true"

### ISSUE THREAD

**Issue by methgaard** [kekeh/mydatepicker#246]
Hi.
When setting the datetimepickers "openSelectorTopOfInput" to true, the "pointer" (I dont know what it is called) still points up and therefore away from den datepicker field ( please see image below)
![image](https://cloud.githubusercontent.com/assets/10635795/24750095/eb18a04c-1ac5-11e7-9ceb-d6a6ada04446.png)

**Comment by kekeh** [comment]
You can set option **showSelectorArrow** to false. It hides the arrow. Not possible to show arrow to the bottom of the calendar.
