### ISSUE TITLE
issue with multiple date pickers in a page

### ISSUE THREAD

**Issue by mrasal** [kekeh/mydatepicker#25]
@kekeh, I need to filter data using a date range. I have added two date pickers on a page and tried to change the date but both the input change the date when I change the date from one date picker.

Also I need to add calendar icon with inputs.

**Comment by kekeh** [comment]
Check sample app included into this project. I added second date picker to it. 

What do you mean calendar icon with inputs?

**Comment by mrasal** [comment]
Thanks for your reply, I got the idea how I can add 2nd date picker. I have attached the image below for understanding of calendar icon. See blue icon with input box, like this I need to add icon.

![calendar](https://cloud.githubusercontent.com/assets/17316871/15883446/d762ebbe-2d65-11e6-9625-4292ff371a64.jpg)

**Comment by kekeh** [comment]
If you want to change icon you have to edit file: **/src/my-date-picker/my-date-picker.component.html**

Line 6: <button type="button" class="btnpicker" (click)="openBtnClicked()">**<span class="icon icon-calendar">**</span></button>

bolded part is icon

If you want to change button style edit **btnpicker** from  **mydatepicker/src/my-date-picker/my-date-picker.component.scss**
