### ISSUE TITLE
Turn option.componentDisabled into @Input() disabled

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#250]
Currently (1.8.5) and in earlier versions too (1.7.14 at least) mydatepicker does disable input field and button when its containing `fieldset` has `disabled` attribute set: nothing happens when clicking on both of them.

But their visual styles do not match their disabled state, at least not the "Bootstrap style": cursor should show the not-allowed pointer, input background should be greyed, hovering on button should not change its color.

Beside this visual issue, then there's a feature proposal/change: disabling the whole component *seems* (?) relatively more important than disabling a part of it. So while it seems good to keep other *disableXxx* flags in options, why not move `componentDisabled` to a first level `disabled` property? Actually better avoid name conflicts with standard HTML property, so something like `datePickerDisabled`.

Would you consider a PR addressing those issues? Any direction on where to put the hands first? Thanks

**Comment by kekeh** [comment]
If you want bootstrap visual styles to input box, calendar and close buttons you can try this attribute directive date picker. Otherwise it is similar date picker as mydatepicker.

repo: https://github.com/kekeh/ngx-mydatepicker
demo (bootstrap style): https://kekeh.github.io/ngx-mydatepicker

**Comment by BrainCrumbz** [comment]
Thanks for suggestion on visual styles. What do you think about the `options.componentDisabled` Vs `@Input() disabled` change?

**Comment by kekeh** [comment]
I added **disabled** attribute. Here is an example how to use: https://github.com/kekeh/mydatepicker/wiki/Disable-component-with-disabled-attribute

Update to the latest version: 1.8.6

**Comment by BrainCrumbz** [comment]
Glad you liked the idea ... and even more that you actually added that. Cool
