### ISSUE TITLE
Can we customize it as a dropdown for Month/Year selection?

### ISSUE THREAD

**Issue by tshaik49** [kekeh/mydatepicker#253]
Hi, 
Currently it's not a drop down and user either might have to click many times to go to a selected month or year Or have to type it, instead is that possible to make it a drop down so it's easy to select?
![datepicker](https://cloud.githubusercontent.com/assets/27377050/24980146/fb41bc04-1fa4-11e7-8304-52ebf81c734e.PNG)

**Comment by kekeh** [comment]
Currently there is only input box when clicking month or year label.

**Comment by tshaik49** [comment]
Yes, Can we customize it to a drop down?

**Comment by kekeh** [comment]
Hi @tshaik49

You can create own version. Check instructions from readme file. 

I want to keep input boxex as they are now.
