### ISSUE TITLE
datepicker icon not rendering properly, clashing with formbuilders css style sheet

### ISSUE THREAD

**Issue by kuebano** [kekeh/mydatepicker#255]

**Comment by kekeh** [comment]
Can you add image here? What is version of mydapicker?

**Comment by kuebano** [comment]
<img width="198" alt="datepicker" src="https://cloud.githubusercontent.com/assets/15814498/25001584/15131620-203e-11e7-9f3c-cfcea955d53e.PNG">

**Comment by kuebano** [comment]
version 1.7.4

**Comment by kekeh** [comment]
Try to update the latest version 1.9.1. I have done changes to fonts recently.

Let me if it is working or not.

**Comment by kuebano** [comment]
i just upgraded....it still didnt work

**Comment by kekeh** [comment]
I don't know is this solution but try to add this to your styles.css

.mydp .mydpicon:before { font-family: mydatepicker !important; }

**Comment by kuebano** [comment]
it worked. the icon are showing properly, but then my calendar is no longer showing
<img width="139" alt="datepicker one" src="https://cloud.githubusercontent.com/assets/15814498/25004604/16014084-204d-11e7-8b14-076a158d3d01.PNG">
<img width="463" alt="datepicker two" src="https://cloud.githubusercontent.com/assets/15814498/25004607/191d7c6a-204d-11e7-8d8c-8c4e63266e16.PNG">

**Comment by kekeh** [comment]
What version you are now using. Probably the error is not related to icons.

**Comment by kekeh** [comment]
**isMarkedDate** is function I added to the latest version of mydatepicker and it should be there. It works ok here: http://kekeh.github.io/mydatepicker

Try to following:
- npm remove mydatepicker
- npm install mydatepicker --save

**Comment by kuebano** [comment]
thanks alot!..it working perfectly now

**Comment by kekeh** [comment]
Ok. Closing this issue.
