### ISSUE TITLE
Can i use mydatepicker for mm/yyyy format? 

### ISSUE THREAD

**Issue by istiak-mlbd** [kekeh/mydatepicker#256]
I want to use it to only get month and year from the datepicker. for this reason i want to show the user only month and year selection view except the day selection view. 
How can i customize this?

**Comment by kekeh** [comment]
This is not possible because mydapicker is date picker. This feature requires lot of code changes.

**Comment by kekeh** [comment]
If you want create month picker from this component, you need to do code changes. You can create own version of component. Here is instructions on how to start: https://github.com/kekeh/mydatepicker#development-of-this-component
