### ISSUE TITLE
Initializing with null date

### ISSUE THREAD

**Issue by queejie** [kekeh/mydatepicker#257]
First, thanks for this module!

I've tried, without success, initializing the ngModel value variously to:
- null
- {date: null}
- {date: {year:null, month:null,day:null}}
- {date: {year:'', month:'',day:''}}

If it is null, a date that was previously used on the form in the past is used, ignoring the current model value
![image](https://cloud.githubusercontent.com/assets/1616827/25007774/9eb1bb52-202f-11e7-9153-35c20ac97975.png)
.  In all the other cases bad strings are displayed in the input field.

**Comment by kekeh** [comment]
Just put empty string to value of ngModel

**Comment by kekeh** [comment]
Hera are examples: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-access-modifier/sample-date-picker-access-modifier.ts
