### ISSUE TITLE
Avoid paste special characters

### ISSUE THREAD

**Issue by luisbirchenz** [kekeh/mydatepicker#258]
Hi kekeh,
             I implemented your component in my project, everything work fine. But when it was sent to QA testing they reported us that the date field can be modified by pasting special characters like this: "~!@#$%^&*"  with the right mouse button. The point here is that when this happens the model of our form is not updated and the validation is not fired. We would like to know if there is a way to avoid it, I mean, paste special characters in this component by using the right mouse button.

I look forward to receiving your comments.

Best regards,

Luis.

**Comment by kekeh** [comment]
Now pasting with right mouse button works like typing the string to the input field.

New version is: 1.9.3

**Comment by luisbirchenz** [comment]
Thanks for replying it so quickly. 
I'll take a look and I'll let you know.

Thank you,

Luis.
