### ISSUE TITLE
About display year

### ISSUE THREAD

**Issue by sutinee742** [kekeh/mydatepicker#260]
Hi,
i have a Buddhist calendar project.
i want to customize your datepicker to display the B.D. year drowpdown, 
but i don't know the code for customize it.
example: year A.D. 2017 -->B.D. 2560
![image](https://cloud.githubusercontent.com/assets/20412020/25044123/f1632f3c-214e-11e7-95a1-f8fda44ac77e.png)
the dropdown look likes this image.

**Comment by kekeh** [comment]
If you want this kind of functionality you can create own version of the component. You can start from here: https://github.com/kekeh/mydatepicker#development-of-this-component
