### ISSUE TITLE
Angular4 The <template> element is deprecated

### ISSUE THREAD

**Issue by fl0ekill** [kekeh/mydatepicker#262]
In Angular 4
Google Chrome console warning : 

```
The <template> element is deprecated. Use <ng-template> instead ("
  </thead>
  <tbody>
    [WARNING ->]<template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
      <tr *ngIf="!(datePicke"): ng:///DatepickerModule/DayPickerComponent.html@38:4
```

>I think just change \<template> to \<ng-template> 

Thank you

**Comment by kekeh** [comment]
Probably this not mydatepicker error? I am not using template. Also the DayPickerComponent.html is not the mydatepicker file.

**Comment by fl0ekill** [comment]
oops sorry. It another datepicker
