### ISSUE TITLE
Year formatting is not happening

### ISSUE THREAD

**Issue by Yashavanta** [kekeh/mydatepicker#264]
Hi,

I am trying the format the date using dd/mm/yy format. 
But it is displaying like 17/04/yy.

**Comment by kekeh** [comment]
Currently it supports only full year for example dd/mm/yyyy

**Comment by kekeh** [comment]
If you want this kind of functionality you have to create own version of the component. It requires code changes quite many places.

Here are instructions on how to develop own version: https://github.com/kekeh/mydatepicker#development-of-this-component

I don't have plan to do this kind of feature so I close this issue.
