### ISSUE TITLE
ReactiveForm, issue if datepicker is not changed

### ISSUE THREAD

**Issue by industrylinq** [kekeh/mydatepicker#265]
Hi,

Quick question, when I'm using mydatepicker in a ReactiveForm and initialize mydatepicker  with an existing date and date is not changed by user I will get .jsdate undefined.

For example:

load using patchvalue or setvalue :
  const birthdate = {
      date: {
        year: moment(birthday).format('YYYY'),
        month: moment(birthday).format('M'),
        day: moment(birthday).format('D')
      }
    };

The date is initialized as expected, however if the user does not change the value in the datepicker I will get an error on submit. 

It seems like that the input date isn't converted to a mydatepicker model at pathcvalue/setvalue, so I can not get access to birthdate.jsdate when the date isn't changed. Result is an error undefined .jsdate.

Current solution is to track birthdate for changes and if changed only call .jsdate.
What am I doing wrong, or if this is expected behavior could you change the behavior that if a date is set/patched I can rely on a similar object as if a changed the object with datepicker.

Thank your so much,

Roel

**Comment by kekeh** [comment]
When you initialize birthdate above. Value of year, month and day must be numbers. Probably the moment.format() function returns a string?

**Comment by industrylinq** [comment]
Hi Keheh,

Momentjs does return a string, I updated my code to set a type number

```
setBirthday(birthday) {

    const year: number = Number(moment(birthday).format('YYYY'));
    const month: number = Number(moment(birthday).format('M'));
    const day: number = Number(moment(birthday).format('D'));

    return this.editCustomerForm.patchValue({
      cust_contact_persons: ({
        birthday: {
          date: {
            year: year,
            month: month,
            day: day
          }        })
    });
  }
```

This time the birthday is also rightfully initialized, however my issue is not resolved.
If datepicker is not dirty or untouched, it seems like I can not rely on a jsdate object.
See image below:

![image](https://cloud.githubusercontent.com/assets/5270822/25141130/747f80e4-2417-11e7-92e3-bbb09ae581d7.png)


I'm building in Angular 4.0.2. and using MomentJS 2.18.1 latest version

**Comment by kekeh** [comment]
Here is example of reactive forms: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

Files contain ngModel and reactive forms example. Files are part of sampleapp. You can run sampleapp. Here are instructions: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by kekeh** [comment]
jsdate value is set When you select a date from calendar. It works this way. If you only initialize to specific date and click submit the jsdate value is undefined in model.

Maybe I have fix that but you can use value of date in submit before that fix.

**Comment by industrylinq** [comment]
Hi Keheh,

I had followed all tutorials before submitting this ticket, as I do not want to waste your time :-)
If this is the expected behavior, I will just use my track changes at formcontrol.

Thank you so much for building an awesome datepicker.
