### ISSUE TITLE
How to get formatted property directly in Angular reactive form

### ISSUE THREAD

**Issue by mehunk** [kekeh/mydatepicker#267]
Now I use this datepicker in my reactive form, but when I submit this form, this inputTime input element value is a Object, not a string value.
![image](https://cloud.githubusercontent.com/assets/10388497/25160951/c352d444-24eb-11e7-90e6-678f54f360cb.png)
 <my-date-picker name="inputTime" locale="zh-cn" formControlName="inputTime"></my-date-picker>

How do I get the formatted property of the Object directly in the situation.

**Comment by kekeh** [comment]
When you select a date the value of model is [IMyDateModel](https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date-model.interface.ts) object. You can get string value for example **silentTime.formatted**.

Do you mean that value of input box is not a selected date string?

**Comment by mehunk** [comment]
Yes, when I get the value of the date input of my form, I will get the  IMyDateModel object. Although I can get the string value by using silentTime.formatted. However, I want to know if there is a way to get string value of the date input directly.

**Comment by kekeh** [comment]
It is not possible to get string value.

**Comment by christofferskog** [comment]
Extremely annoying that you can't have the string value as the model directly...

**Comment by robinkedia** [comment]
I too feel this annoying.. the datepicker should return string directly
