### ISSUE TITLE
Datepicker as popover

### ISSUE THREAD

**Issue by agent0** [kekeh/mydatepicker#268]
Hi,

is there a way to make the datepicker a popover on top of everything else? Currently, opening the datepicker enlarges the enclosing div, thus adding scrollbars and messing up the layout. Is it, e.g., possible to add the datepicker to the document body and use it with absolute positioning?

Regards, J.

**Comment by kekeh** [comment]
Calendar is already absolute positioned.

**Comment by agent0** [comment]
Ok, thanks. But why does it expand the enclosing div? Is this perhaps I have another div way up the DOM that has position:relative? And what to do in this case? Can I tell the component to add the generated HTML to the body instead of the component that uses the datepicker?

**Comment by kekeh** [comment]
You can test here: http://kekeh.github.io/mydatepicker/

opening calendar doesn't move elements in the bottom of calendar

Not possible to add calendar HTML to the body.

**Comment by agent0** [comment]
Thanks again, I will try to figure out what part of my layout causes the observed effect. In your example, if I shrink the window, the datepicker does not scroll the parent element. In my layout, opening the datepicker does scroll the parent element...

**Comment by agent0** [comment]
Ok, the behavior seems to be browser-dependent: in Chrome, opening the datepicker causes the parent element to adjust the viewport while in Firefox, the viewport remains the same. If it is not possible to render the HTML code outside the parent element (as e.g. Material2 does with its pop-ups) I guess there is nothing you could do about it. Thank you for your help and the very nice compoment...
