### ISSUE TITLE
Autocomplete with Microsoft Edge

### ISSUE THREAD

**Issue by kristina-san** [kekeh/mydatepicker#269]
Hello,

I've noticed a strange behavior of the date picker. Only in edge the date picker has a autocomplete function (see the picture below.) How can I get rid of it?

![image_3v](https://cloud.githubusercontent.com/assets/4233759/25167757/08a3261c-24e1-11e7-80c7-53dfbfa85ecf.png)

Thank you.

**Comment by kekeh** [comment]
I am not able to reproduce issue here: http://kekeh.github.io/mydatepicker/

Are you able to reproduce in the link above. Can you add step by step instructions on how to reproduce.

**Comment by kristina-san** [comment]
No, unfortunately I cannot reproduce the issue on the link.

I use the date picker in a reactive form and with these options:
    `this.myDatePickerOptions = {
      showInputField: true,
      dateFormat: 'dd.mm.yyyy',
      inputAutoFill: false,
      width: '223px',
      inputValueRequired: true,
      minYear: 1900,
      disableSince: { year: currentDate.getFullYear(), month: (currentDate.getMonth() + 1), day: (currentDate.getDate() + 1) }
    };` 
Sometimes the input field is preallocated. If I click in the input field, the autocomplete list opens. It doesn't depend on whether the form is submitted or not.

One problem that follows is that the input field is not filled if I use a date from the autocomplete list. As already stated, this is only with the Microsoft Edge browser.

**Comment by kekeh** [comment]
I added **autocomplete="off"** to the input field. It is in version **1.9.8**. Install that version from npm and try again.

Let me know if the fix is working or not.

**Comment by kristina-san** [comment]
It is working now! Thank you very much for your quick help!! :-)

But now I have the problem (due to the new version) that the inputValueRequired option is outdated and I cannot validate my form in the right way. If there is no input, I set the background to a red color (like in the image in my first post).

`my-date-picker /deep/ .selection:not(old):invalid {`
`  background-color: rgba(255,0,0,0.2);`
`}`

If I set required in my .html, it is not working. Do I anything wrong?

**Comment by kekeh** [comment]
If you are using **ngModel** binding you can set required flag as follows:

```html
<my-date-picker name="myDate" [options]="myDatePickerOptions"
    [(ngModel)]="model" required></my-date-picker>
```

If you are using **reactive forms** you can set required flag as follows:
```html
<my-date-picker name="myDate" [options]="myDatePickerOptions"
    formControlName="myDate" (inputFieldChanged)="onInputFieldChanged($event)"></my-date-picker>
```
```javascript
ngOnInit() {
    this.myForm = this.formBuilder.group({
        myDate: ['', Validators.required]   // not initial date set
    });
}

onInputFieldChanged(event: IMyInputFieldChanged) {
        console.log('onInputFieldChanged(): Value valid: ', event.valid);
}
```
You can set **indicateInvalidDate** to true and background is automatically set to red if the date is not valid.

The **inputFieldChanged** callback indicates also is the user typed date valid or not: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

you can implement this callback like above. Hopefully this helps.
