### ISSUE TITLE
How do I implement your changes?

### ISSUE THREAD

**Issue by jbaird2685** [kekeh/mydatepicker#27]
I'm sorry if this is not the proper medium to address this, but I have no other way, that I know of, to contact you.  I'm new at Angular2 and I tried to use the date picker after your update to RC3.  Still having tons of probems.  I copied the entire mydatepicker directory into node_modules and tried to run my program, but of course, it failed.  Can you tell me how to implement your changes, short of an update npm package?  Thanks in advance.

**Comment by kekeh** [comment]
You can run **npm install** which will update dependencies (Angular2 RC3 and others). That is enough. No other changes yesterday.

**Comment by kekeh** [comment]
Probably this is clear.
