### ISSUE TITLE
Change select date icon

### ISSUE THREAD

**Issue by lait1989** [kekeh/mydatepicker#270]
Hello! How i can change select date icon?

**Comment by kekeh** [comment]
Probably you mean icon of today button. I don't know if this is working or not but you can try:

```javascript
.mydp .icon-mydptoday:before {
  font-family: 'Glyphicons Halflings';
  font-size: 11px;
  content: '\e014';
}
```

you need to know what is content code of the icon.

Another way is to create own version of the component. Icons are embedded to this file: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.css

starting from the @font-face definition. They are 64base encoded data. I have used this http://fontello.com/ service to create base64 encoded data.

If you use this way you have to create own version of the component. Here are instructions: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by lait1989** [comment]
Thanks! I already solve this question.
