### ISSUE TITLE
Cannot install mypicker in angular-cli

### ISSUE THREAD

**Issue by rotmorf** [kekeh/mydatepicker#271]
npm install mydatepicker --save return that output. Somebody have simillar problem ?
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN angular-material@1.1.3 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.3 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.3 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.
`

**Comment by kekeh** [comment]
Dependency warnings not related to mydatepicker. Component is still installed. You can Check that under the node_modules folder is mydapicker folder.
