### ISSUE TITLE
A way of open the calendar when the user click in the input

### ISSUE THREAD

**Issue by Kleak** [kekeh/mydatepicker#273]
Is there a way to open the calendar when the user click in the input i have try with `inputFocusBlur` and `openBtnCliked` but i got an error.

```
Expression has changed after it was checked.
```

**Comment by kekeh** [comment]
There is option. Set **openSelectorOnInputClick** to **true** and **editableDateField** to **false**. After that input click opens the calendar.

**Comment by Kleak** [comment]
Thanks but i got the same error :/

**Comment by kekeh** [comment]
There is a bug. I have to check that bug.

**Comment by Kleak** [comment]
If there is a bug you should probably reopen the issue :)

**Comment by kekeh** [comment]
At first try update the latest version: 1.9.8. I have recently fixed similar error. If you can reproduce the error let me know.

**Comment by Kleak** [comment]
I use 1.9.8

**Comment by kekeh** [comment]
Hi @Kleak 

I fixed this bug. Try version **1.9.9** from npm.
