### ISSUE TITLE
How to make a range date where I don't select start date or end date

### ISSUE THREAD

**Issue by kilofafeure** [kekeh/mydatepicker#274]
I would like to know if would be possible use the date range where I don't have to inform the start date or the end date.

Thanks in advance.

**Comment by kekeh** [comment]
You need two date pickers if you want a date range. 

I have also done date range picker which can be used to select a date range. **mydaterangepicker** repo is here: https://github.com/kekeh/mydaterangepicker and the demo is here: https://kekeh.github.io/mydaterangepicker

Was this answer to your question?

**Comment by kilofafeure** [comment]
Not, you haven't understood me...XD. 
I've already seen your dateRangePicker, but in the example I'm forzed to select begin and end date. Sometimes I d'ont need to select start date or end date, and I would like know if it's possible because I haven't achieved. 
I hope this explanation it's more clear. Sorry for my english.

**Comment by kekeh** [comment]
If start date or end date is optional probably best solution is two date pickers. For example if end date is not mandatory in some cases you can disable the date picker of end date.

With my date range picker both the start and the end date are mandatory.

**Comment by kilofafeure** [comment]
Ok, then it's not possible.
Thanks for all.
