### ISSUE TITLE
reset inputfield - binding not working

### ISSUE THREAD

**Issue by aavelyn** [kekeh/mydatepicker#277]
Hi again,

so currently the template looks like this. The control is added to form.

```
<div class="form-group date-picker">
			<label for="aForm_4">Deadline</label>
			<my-date-picker formControlName="deadline" [options]="myDatePickerOptions"></my-date-picker>
		</div>
```

the whole form is inside a component, which will be shown via a modal.

When the modal is opened, i'm using @viewChild to access a public method to set the mode for the form. That method resets the form using form.reset() and when I console.log the form, the control deadline is null.

however the previously selected date is still displayed in the input value.

same thing when i use template form via ngModel.

Cheers

**Comment by kekeh** [comment]
I close this issue. If you have same situation you can reopen this issue.
