### ISSUE TITLE
Unable to set input field with async data

### ISSUE THREAD

**Issue by spwizard** [kekeh/mydatepicker#279]
How do you set the input field to display a date from async data.
The only way it seems to display the date is when I click on the field.

Any help or example would be much appreciated.

Thanks

**Comment by monospaced** [comment]
👍

**Comment by kekeh** [comment]
1. If you are using **ngModel** binding:

  - you can  set model as follows
```html
<my-date-picker name="mydate" [options]="myDatePickerOptions" 
    [(ngModel)]="model"></my-date-picker>
```

```javascript
private model: Object = null;   // not initial date set

// calling this function set new date
setDate(): void {
    // for example set date: 09.10.2018, value of year, month and day must be number
    this.model = {date: {year: 2018, month: 10, day: 9}};
}
```

2. If you are using **reactive forms** you can use **setValue()** function:

  - Here is an example on how to use setValue() function: https://github.com/kekeh/mydatepicker#2-reactive-forms

**Comment by iamonuwa** [comment]
You can try this,
after async call returns value

`ngOnInit(){
          let date = this.staff.dob.split('-');
          this.myForm = this.formBuilder.group({
          dob : new FormControl({date: {year: date[0], month: date[1], day: date[2]}}, [Validators.required]),
        })
}`
