### ISSUE TITLE
Multiple date picker, not a range.

### ISSUE THREAD

**Issue by joshuabmartin** [kekeh/mydatepicker#286]
I'm currently trying to implement separate date pickers. But when I select a date on one picker it duplicates the same info on the other picker. I want to two separate date pickers but not a range. Does this make sense?

**Comment by kekeh** [comment]
Probably you want to set disableUntil or disableSince? Here is example: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

If you are using ngModel or reactive forms you need to add own model to both date pickers.

Check also this mydaterangepicker: https://github.com/kekeh/mydaterangepicker
demo: https://kekeh.github.io/mydaterangepicker
