### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'my-date-picker'.

### ISSUE THREAD

**Issue by ymallikreddy521** [kekeh/mydatepicker#288]
I followed the steps given in below link.
https://github.com/kekeh/mydatepicker#development-of-this-component

After successful built, when I integrate with in the application, 
https://github.com/kekeh/mydatepicker#installation

I get below error

Can't bind to 'options' since it isn't a known property of 'my-date-picker'.
1. If 'my-date-picker' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'my-date-picker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("       <input type='text' [(ngModel)]='listFilter' />
                <my-date-picker name="mydate" [ERROR ->][options]="myDatePickerOptions"></my-date-picker>
            </div>
        </div>

**Comment by kekeh** [comment]
After you have installed the generated mydatepicker package check that the 

**node_modules/mydatepicker** folder exists

You can also try to install from npm: **npm install mydatepicker**

if npm installation gives the same error then you probably have issue in your own application

**Comment by ymallikreddy521** [comment]
In angular-cli, its working fine. Thanks

**Comment by kamlekar** [comment]
@ymallikreddy521 what do you mean by `angular-cli, it is working fine`?

Can you please elaborate? I am facing the same issue here.

**Comment by aidionidis** [comment]
I faced the same issue, problem is that I was importing MyDateRangePickerModule inside the main AppModule, you have to import it in the same module of the component in wich you are going to use the picker.
Also, don't forget to import FormsModule BEFORE the MyDateRangePickerModule.

**Comment by esenpillai** [comment]
@aidionidis you saved my day. I couldn't find one article that provide solution to this problem. Either it says  follow the instruction it should work or it says can't reproduce. I have multiple modules, however adding this to app module will give access to my multiple sub modules (at least thats what I thought). End up getting this error message. When I do the imports on my individual modules as you stated, it started working.

**Comment by sailendebnath** [comment]
Can't bind to 'options' since it isn't a known property of 'my-date-picker'.


![capture](https://user-images.githubusercontent.com/16538324/47013939-6cfa1c00-d166-11e8-8c0d-0d534a71e0cd.PNG)

**Comment by chr1soscl** [comment]
> After you have installed the generated mydatepicker package check that the
> 
> **node_modules/mydatepicker** folder exists
> 
> You can also try to install from npm: **npm install mydatepicker**
> 
> if npm installation gives the same error then you probably have issue in your own application

I am installing npm install mydatepicker and importing to the module but still getting the same error, the version I am getting installed is mydatepicker@2.6.6, is this broken?
