### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by nasreddineskandrani** [kekeh/mydatepicker#29]
#hi!

when i add MyDatePicker to the directives part of my component (page) 
i get 
Uncaught SyntaxError: Unexpected token export

it is complaining about the export in
mydatepicker/src/index.ts

please test  your lib out of your project -> 1h and it's not working for me using npm install and following your steps.

You need to have css and js (ts) dependency that's it (no sass).

PLease update your lib to work with basic project as angular2-webackpack-starter

Thank you

**Comment by nasreddineskandrani** [comment]
for the moment i get it work doing that:

1. clone the current repo

2. copy directly the folder my-date-picker/ to my repo (without using npm)

3. compile manually scss file to css and change include scss to css in index.js 
you can use command line: sass --watch style.scss:style.css

4. invert order of export in my-date-picker/index.js
become: 
export * from './interfaces/index';
export * from './my-date-picker.component';

it works like that. 

Your npm install need to ship a css file not a scss please.
So you need a version working with only css.

by the way i like your picker.

**Comment by kekeh** [comment]
I changed scss files back to css. Component also added to the npm. You can try again by installing component with the following command **npm install mydatepicker**
