### ISSUE TITLE
Clear ngModel-binded Date from outside not working

### ISSUE THREAD

**Issue by PatriziaDietrich** [kekeh/mydatepicker#290]
Hi,
I used the datepicker with the ngModel-binding this way:
```
<my-date-picker id="date-picker" [options]="myDatePickerOptions"
                                                [(ngModel)]="date"></my-date-picker>
```
Now i want to clear the datepicker from outside with my own button (which is effecting also other inputs) this way:

```
resetForm() {
    this.date = {};
}
```

But the datepicker still shows the selected date. Can you help? Thanks :)

**Comment by kekeh** [comment]
You have to set empty string to model as follows:

```javascript
resetForm() {
    this.date = '';
}
```
