### ISSUE TITLE
[bug?] Emitted observable type is not consistent

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#291]
Hello

using current latest, 1.10.2, we're experiencing an issue described by following steps:

### Steps

1. Setup a `<my-date-picker>` instance within a form and assign its own `formControlName` to picker control
1. Observe `valueChanges` from the corresponding form AbstractControl: `this.myForm.controls['myDatePickerControlName'].valueChanges`
1. Setup console or some `<pre>` node to dump contents of observed values
1. Invoke `setValue()` on form to set the date programmatically, passing the date value as a `{ date: IMyDate; }` structure
1. Change the date manually by opening picker and selecting with mouse

### Expected

All observed values should have the same shape as `IMyDateModel`, or maybe null when form is setup.

### Actual

The first observed value, the one due to `setValue()` invocation, has a shape like `{ date: IMyDate; }`.

The second observed value, the one set manually, has a shape like `IMyDateModel`.

---

This messes up value observation when one is expecting always an `IMyDateModel`, e.g. because is interested in its `jsdate` field, which is not always available. And anyway it does seem an inconsistent behaviour.

[This plunker](http://plnkr.co/edit/2fEWYHSw2staCxipFC3F?p=preview) shows the issue: there's a timeout setting date programmatically, then one can open the picker and set a date manually.

**Comment by kekeh** [comment]
I fixed this bug in version 2.0.0. Now if date is valid the value type of model is IMyDateModel. In other cases value is null.

**Comment by BrainCrumbz** [comment]
Thanks. That choice makes sense. Will try this as well.
