### ISSUE TITLE
Initial date not visible when inline = true

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#292]
Not sure this is a bug, or a different feature, will try to explain through its steps:

### Steps

1. Setup a reactive form
1. Setup an instance of `<my-date-picker>` with `inline` option set to true within the form
1. After some timeout, programmatically set form values with `setValue()` to a date *visible* in currently displayed month
1. After some longer time, programmatically set form values with `setValue()` to a date *not visible* in currently displayed month

### Expected

After `setValue()` is first invoked, the datepicker should show the selected date in current month.
After it's invoked second time, the picker should move to the needed month and show the set date. 

### Actual

After first invocation is the same, date is displayed. 
After second invocation, displayed month stays the same and so selected date is not visible.

---

Point is that, if you think about non-inline picker, I can set date programmatically on form control, then when I click to open the picker, the picker is correctly positioned on expected month/year and shows selected date.

One could expect the same behaviour with inline picker, otherwise when e.g. I open a form to modify some entity with a date field already set, and the date control has `inline=true` option set, I will see the picker on current month, and not on the month of set date.

[This plunker](http://plnkr.co/edit/3mMkcAGE7hBfKQDqFnDM?p=preview) shows the issue.

**Comment by BrainCrumbz** [comment]
We also tried, as a workaround, to bind datepicker `[selDate]`, but this has the unwanted side-effect of actually selecting that date, as if the user clicked on it, and thus the form.valueChanges receives emits a new set of values, which is not really the case.

So we're back at square 1 on this. Please do not hesitate to ask for more info, if that can help

**Comment by kekeh** [comment]
I fixed this bug in version 2.0.0. Now calendar view is changed if the date set by **setValue()** is another month or year.

**Comment by BrainCrumbz** [comment]
Thanks! Will try new version in a short time.
