### ISSUE TITLE
[API change] From `selector` number attribute to an `{ open: boolean }` shaped object

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#293]
Opinion: the API to open/close datepicker selector through an attribute looks rather unusual. Even after looking at [wiki example](https://github.com/kekeh/mydatepicker/wiki/Open-selector-with-selector-attribute), one is left figuring out how do you actually *toggle* selector state? For example, how do you "send" 2 close messages in a row?

Another approach could be taken with the steps:

1. Rename attribute to something more intent-revealing, e,g. `selectorOpen`, `selectorState`, `selectorVisibility`, `openCloseState`, ...
1. Shape it as an object, not as a primitive, so that as long as client code creates a new objects instance, the input is "sensed" by component
1. Pass a boolean within the object, to state more clearly the intended state: `true` -> make it open, `false` -> make it close

All in all, it could look something like:

```ts
// mydatepicker code

export interface SelectorState {
  open: boolean;
}

// ...
  @Input()
  selectorState: SelectorState;
```

```html
<!-- client template -->

<my-date-picker [selectorState]="datePickerState" ... >
```

```ts
// client code

  doOpen() {
    this.datePickerState = {
      open: true;
    };
  }

  doClose() {
    this.datePickerState = {
      open: false;
    };
  }
```

**Comment by kekeh** [comment]
You can use ViewChild to call date picker function. Here is an example: https://github.com/kekeh/mydatepicker/wiki/Calling-date-picker-function

**Comment by BrainCrumbz** [comment]
Well, in reality, working with declarative, view-bound properties is considered vastly better than grabbing refs to component in template and imperatively invoking commands on it. Trying to show/hide a component sending a number "command" seems quite unusual, too.

**Comment by kekeh** [comment]
I added new interface **IMySelector**. Purpose of it is to open/close the selector as described above. More info: https://github.com/kekeh/mydatepicker#selector-attribute

This change is in version 2.0.20
