### ISSUE TITLE
[bug?] `disableSince` cached from old options value

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#294]
We haven't tried yet with 2.0.0, but for 1.10.2 there's the following strange behaviour. Here are the steps:

### Steps

1. Setup a `<my-date-picker>` instance and bind its `options` attribute to some component property
1. Set options property with both `disableUntil` and `disableSince` with a meaningful range, both in the past.
1. Open selector, should show current date and it should be in the disable range
1. Set options property again, this time only with `disableUntil`, same value as before, and **no** `disableSince`
1. Open selector

### Expected 

It should show current date, this time it should be in enabled range, having only `disableUntil` and being that in the past

### Actual

The current date still shows up in disable range. The old disabled range is still there, even after the new assignment. It seems like the old `disableSince` was stuck there. 

---

Sorry for not providing a plunker, at the moment plnkr.co seems to be down.

As a temporary workaround, what we do the second time is still set both `disableUntil` and `disableSince`, with the latter set to `{ day: 0, month: 0, year: 0}`.

**Comment by kekeh** [comment]
In step 4 you have to reset **disableSince** if you don't want to use it. For example:

```javascript
disableSince: { day: 0, month: 0, year: 0}
```

**Comment by BrainCrumbz** [comment]
Yep, found that workaround, although it does not seem intuitive. At the minimum, if that's the way it is supposed to be, there should be a mention in the docs. Thanks

**Comment by kekeh** [comment]
I updated to README.
