### ISSUE TITLE
Incorrect behavior while type date into input field

### ISSUE THREAD

**Issue by olgadichkovskaya** [kekeh/mydatepicker#296]
I use dateFormat for my-date-picker, for example 'mm/yyyy'. I have inputFieldChanged callback:

`
onInputFieldChanged(event: IMyInputFieldChanged) {
  console.log('onInputFieldChanged(): Value: ', event.value, ' - dateFormat: ', event.dateFormat, ' - valid: ', event.valid);
}
`

When I select the date using calendar - date is valid. When I type the same date into the field - isn't.

![picker](https://cloud.githubusercontent.com/assets/28594256/25894771/e05c4994-3585-11e7-9212-6211be023a63.png)
(valid = true only when use calendar to select the date)

**Comment by kekeh** [comment]
Date format **mm/yyyy** is not officially supported because this is a date picker not a month picker. You have to use **dd/mm/yyyy** instead.

It should work.
