### ISSUE TITLE
[Question] How to disable datepicker dynamically

### ISSUE THREAD

**Issue by karangarg45** [kekeh/mydatepicker#299]
Currently i can disable the datepicker by passing the componentDisabled true in datepicker config.But once the datepicker has been initialized now i want to disable the datepicker on some flag.updating the datepicker config now wont work(may be because it has been initalized) is it possible to pass disable property as a property binding so if the value of the disable flag updates the property binding is updated automatically

**Comment by kekeh** [comment]
You need to create fresh copy of options in order the date picker detect the change of option. You can set any option dynamically. Example below:
```html
<my-date-picker [options]="myOptions" 
                (dateChanged)="onDateChanged($event)"></my-date-picker>
```

```ts
import {Component} from '@angular/core';
import {IMyOptions, IMyDateModel} from 'mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        componentDisabled: false
    }

    constructor() {}

    onDateChanged(event: IMyDateModel) {
        // date selected
    }

    // Calling this function disable component
    disableComponent() {
        let copy = this.getCopyOfOptions();
        copy.componentDisabled = true;
        this.myOptions = copy;
    }

    // Returns copy of myOptions
    getCopyOfOptions(): IMyOptions {
        return JSON.parse(JSON.stringify(this.myOptions));
    }
}
```
