### ISSUE TITLE
binding with Angular 2.0

### ISSUE THREAD

**Issue by khoanguyenlio** [kekeh/mydatepicker#3]
How can i binding with Model, seem like is not support?

**Comment by kekeh** [comment]
Here is Angular2 NgModel documentation: https://angular.io/docs/ts/latest/api/common/NgModel-directive.html

It is not yet fully documented.

**Comment by khoanguyenlio** [comment]
no no not that mean cuz I need to binding with your component. How can i work with your component

**Comment by kekeh** [comment]
This is example app: https://github.com/kekeh/mydatepicker/blob/master/src/app/sampleapp.ts

right?

**Comment by khoanguyenlio** [comment]
I know but how to set the date. You just bind one way....

**Comment by kekeh** [comment]
Hello, you can now set date using selDate attribute. Please update to the latest version. Check example from here: https://github.com/kekeh/mydatepicker/blob/master/src/app/sampleapp.ts

**Comment by khoanguyenlio** [comment]
That's exactly what i want. Keke. Thank you :3
