### ISSUE TITLE
 Uncaught Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by ThomasP1988** [kekeh/mydatepicker#30]
Hi,

First of all, thank you for the datepicker which seems nice,

But I have a bug when I try to use it 

>  Uncaught Error: Expected 'styles' to be an array of strings.

Webpack has difficulties to get styles, any ideas of where it comes from ?

**Comment by kekeh** [comment]
Have you added the following rows to the **webpack.js** and the **package.json** files?

**webpack.js**
=========
`module: {
    loaders: [
       {test: /\.css$/, include: [path.resolve(__dirname, 'src')], loader: 'raw'}
       ....
`

**package.json**
==========
`  "devDependencies": {
       "css-loader": "~0.23.1",
       "postcss-loader": "~0.9.1",
       "raw-loader": "~0.5.1",
       ...
}`
