### ISSUE TITLE
width and height options are useless in inline mode / the width and height of the calendarview are not adjustable via the IMyOptions

### ISSUE THREAD

**Issue by WalnussPower** [kekeh/mydatepicker#300]
i would like to use this datepicker in inline mode, but cannot adapt it's width or height via the datepickers own options. To do this I have to override it's stylings which i would like to avoid.

It would be nice if there were options for this in IMyOptions.

**Comment by kekeh** [comment]
I added selectorHeight and selectorWidth options. Value of them can be in pixels or percents. Read more from README: https://github.com/kekeh/mydatepicker#options-attribute

This change is in version 2.0.4
