### ISSUE TITLE
IMyDpOptions discrepancy and options attributes not working

### ISSUE THREAD

**Issue by elbaumpj** [kekeh/mydatepicker#301]
I'm attempting to use the date picker to pick a date range. I'm adding the options attribute enableDays as suggested in the documentation, however I'm not able to pick a range, only a day. 

In addition, it appears there's a discrepancy about how to call options with ngModel binding. In the source code, options are IMyOptions, but in the documentation _IMyDpOptions__. As such, my live reload breaks when trying to use IMyDpOptions because it does not exist. Please review screenshots and advise. 
![imyoptions](https://cloud.githubusercontent.com/assets/16855624/26067444/4ad7d99c-3968-11e7-8f7b-30f63b7f61c9.png)
![mydatepicker-code](https://cloud.githubusercontent.com/assets/16855624/26067445/4ade0600-3968-11e7-942b-9c6bcc9a84a5.png)
![mydatepicker-calendar](https://cloud.githubusercontent.com/assets/16855624/26067446/4b0d75d4-3968-11e7-99b5-b38aadac20b6.png)

**Comment by kekeh** [comment]
**IMyDpOptions** interface is added today. You have to update mydatepicker package to the latest version (2.0.6). Check end of this file: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-options.interface.ts there is **IMyDpOptions** interface.

With mydatepicker you cannot select a range. If you need a range you have to add two date pickers. But there is also similar date range picker. Here is repository: https://github.com/kekeh/mydaterangepicker and demo is here: https://kekeh.github.io/mydaterangepicker

**enableDays** is an option which can be used to enable dates if they are disabled. Normal use case is to disable date range and enable days in a range. After that enabled dates are selectable. For example disable November of 2016 and enable 10th and 11th dates of that disable range:
```javascript
private option: IMyDpOptions = {
    dateFormat: 'mm-dd-yyyy', 
    disableDateRanges: [{begin: {year: 2016, month: 11, day: 1}, end: {year: 2016, month: 11, day: 30}}],
    enableDays: [{year: 2016, month: 11, day: 10}, {year: 2016, month: 11, day: 11}]
}
```
