### ISSUE TITLE
writeValue method on datepicker has no value === null check and thus is not resettable

### ISSUE THREAD

**Issue by seawave23** [kekeh/mydatepicker#302]
Hello, in contrast to your date-range-picker is your write-value method on this date-picker not checking for null:  

**writeValue method on date-picker:**
```
else if (value === null || value === "") {
            this.clearRangeValues();
            this.inputFieldChanged.emit({ value: "", dateRangeFormat: this.dateRangeFormat, valid: false });
        }
        this.invalidDateRange = false;
```

**writeValue method on date-range-picker:**
```
else if (value === "") {
            this.updateDateValue({ year: 0, month: 0, day: 0 }, true);
        }
```

Thus, when the date-picker is in a formGroup, it doesn't get reset on reset() because the value is null on custom inputs when using objects.

Please add this check to make reset() work.

**Comment by kekeh** [comment]
This is **mydatepicker** writeValue method: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.ts#L330

as you can see there is null check and resetting form clears the selected date. I have tested it.

This is **mydaterangepicker** writeValue method: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.ts#L289

as you can see there is null check and resetting form clears the selected date. I have tested it.

Please update both components to the latest versions. It is possible that you are using old version which do not contain null check. I have added it recently.

- mydatepicker version 2.0.6
- mydaterangepicker version 4.1.2
