### ISSUE TITLE
Add an option to prevent the user from deselecting a date in inline=false mode

### ISSUE THREAD

**Issue by marcusvetter** [kekeh/mydatepicker#305]
When using inline=false mode, a date can be select, and then deselected again. In some use cases we would like to prevent the user from having a "null" date. 
Therefore it would be very useful to have an option to prevent the user from deselecting the date. If the user clicks on a already selected date, the datepicker closes and does not change the date.

**Comment by kekeh** [comment]
Now in version **2.0.8** there is option **allowDeselectDate**. The default value is **true**.

**Comment by marcusvetter** [comment]
Wow that was fast... thank you very very much!!!
