### ISSUE TITLE
openSelectorTopOfInput not working?

### ISSUE THREAD

**Issue by penrique** [kekeh/mydatepicker#306]
openSelectorTopOfInput option is not working for me, are there any requirements for it to work?

My current Options:
private myDatePickerOptions: IMyDpOptions = {
    dateFormat: 'dd/mm/yyyy',
    openSelectorTopOfInput: true
  };

**Comment by kekeh** [comment]
There is a bug in the mydatepicker. I will fix it tomorrow.

**Comment by kekeh** [comment]
I have fixed this bug in version **2.0.9**. Please update to this version.
