### ISSUE TITLE
 To edit live disableUntil and disableSince

### ISSUE THREAD

**Issue by GitHubish** [kekeh/mydatepicker#31]
I think it would be great to add the ability to edit live disableSince and disableUntil .
Today datepicker options can be changed once the datepicker the edited even if it could be very handy and a real bonus.

thank you again for your plugin, it 's great!
I remade the style of it for me to grant it to my project.

I hope you can maintain over the long term .

**Comment by kekeh** [comment]
Now if the date picker options are modified during runtime the date picker UI is updated instantly and it uses updated options. Check the sample app (inline mode).
