### ISSUE TITLE
Day not highlight.

### ISSUE THREAD

**Issue by HtetWaiYanLin** [kekeh/mydatepicker#310]
When I assign date to date_object , day not highlight.
Here is My Code.

`     <form #myForm="ngForm" novalidate>
                  <my-date-picker name="mydate" [options]="myDatePickerOptions"
                    [(ngModel)]="model" required></my-date-picker>
    </form>
    <input type = "text" [(ngModel)] = sdate>
     <button type = "button" (click) = "submit();">Ok</button>`

`     private myDatePickerOptions: IMyDpOptions = {
          // other options...
          dateFormat: 'dd.mm.yyyy',
          showWeekNumbers: true
      }; `
`     // Initialized to specific date (09.10.2018).
      private model: Object = { date: { year: 2018, month: 10, day: 9 } };
      private sdate : string;`
    
  `  submit(){
        this.model = this.changestringtodateobject(this.sdate);
    }
    changestringtodateobject(dt:any){
           return { date: { year: dt.slice(0,4), month: dt.slice(5,7), day: dt.slice(8,10) } };
     } `

**Comment by kekeh** [comment]
Value of year, month and day must be number. Change this function to:
```javascript
changestringtodateobject(dt:any){ 
    return { date: { 
        year: Number(dt.slice(0,4)), 
        month: Number(dt.slice(5,7)), 
        day: Number(dt.slice(8,10)) 
        } }; 
}
```

otherwise it seems to be ok.

**Comment by HtetWaiYanLin** [comment]
@kekeh , it is work well. Thank you.
