### ISSUE TITLE
404 (Not Found) Failed to load resource and Error:(SystemJS) XHR error 

### ISSUE THREAD

**Issue by animishas** [kekeh/mydatepicker#312]
*I have a big list of errors displayed when I add mydatepicker module to the app.module.ts file. I have the mydatepicker directive. i have checked in ng-modules folder. not sure why i get this error and unable to resolve it. please help!
Here's the picture.
![errorinmydatepicker](https://cloud.githubusercontent.com/assets/25496038/26375496/7965d408-3fc6-11e7-87cd-e8bfec10d517.PNG)
``

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { ChartsModule } from 'ng2-charts/ng2-charts';
import { MyDatePickerModule } from 'mydatepicker';

import { AppComponent } from './app.component';
import { DashboardComponent } from './home/dashboard.component';
import { DoughnutChartComponent } from './charts/doughnutChartComponent';
import { PieChartComponent } from './charts/piechart.component';
import { CreateNewQComponent } from './Q/NewQ.component';
import { AgencyComponent } from './Agency/Agency.component';
@NgModule({
    imports: [
        BrowserModule,
        ReactiveFormsModule,
        HttpModule,
        ChartsModule,
        MyDatePickerModule,
        RouterModule.forRoot([
            { path: 'dashboard', component: DashboardComponent },
            { path: 'a', component: CreateAComponent },
            { path: 'b', component: BComponent},
            { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
            { path: '**', redirectTo: 'dashboard', pathMatch: 'full' }
        ])
    ],
    declarations: [
        AppComponent,
        DashboardComponent,
        CreateAComponent,
        BComponent,
        DoughnutChartComponent,
        PieChartComponent
    ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

```

**Comment by kekeh** [comment]
Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

I have one angular-cli project here: https://github.com/kekeh/mydatepicker/tree/gh-pages

and it works well

**Comment by kekeh** [comment]
Did you solve this issue?

**Comment by animishas** [comment]
I was unable to resolve my issues and got distracted on some other work. I will try it again today sometime. Will let you know if I run into issues. Thanks for your reply! I appreciate it.

**Comment by animishas** [comment]
Hi Kekeh, I still get the same message and couldnt get it working. I am using Reactive forms in my template. I will post some code if you could help me. I really need this working, I appreciate your help. Thank a ton

q.module.ts

```
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ReactiveFormsModule } from '@angular/forms';

// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
import { QListComponent } from '../Q/qlist.component';
import { SharedModule } from '../Shared/shared.module';
import { QListService } from '../Q/qlist.service';
import { CreateNewQComponent } from '../Q/NewQ.component';
import { AgencyListComponent } from '../Q/agencylist.component';
import { AgencyListService } from '../Q/agencylist.service';
//import { QDetailComponent } from '../Q/qdetail.component';
import { MyDatePickerModule } from 'mydatepicker';
import { AuthGuard } from '../Shared/Guards/auth.guard';

@NgModule({
    imports: [
        SharedModule,
        ReactiveFormsModule,
        MyDatePickerModule,
        RouterModule.forChild([
            { path: 'qlist', component: QListComponent, canActivate: [AuthGuard] },
            //{ path: 'qdetail', component: QDetailComponent },
            { path: 'newQ/:id', component: CreateNewQComponent, canActivate: [AuthGuard] },
            { path: 'agencylist', component: AgencyListComponent, canActivate: [AuthGuard] }
        ])
    ],
    declarations: [
        QListComponent,
        CreateNewQComponent,
        AgencyListComponent
        //QDetailComponent
    ],
    providers: [
        QListService,
	AgencyListService,
        AuthGuard
    ]
})

export class QModule {}

SystemJS.Config.js

```
/**
* System configuration for Angular samples
* Adjust as necessary for your application needs.
*/
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': '/node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            'mydatepicker': 'npm:mydatepicker/bundles/mydatepicker.umd.min.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'ng2-charts': 'node_modules/ng2-charts',

            'angular2-modal': 'npm:angular2-modal',
            'angular2-modal/plugins/bootstrap': 'npm:angular2-modal/plugins/bootstrap'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'

                    }
                }
            },

            rxjs: {
                defaultExtension: 'js'
            },
            'ng2-charts': {
                defaultExtension: 'js'
            },
            mydatepicker: {
                main: './index.js'
            },

            'angular2-modal': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'angular2-modal/plugins/bootstrap': {
                main: './index.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);

Component.ts file
```

import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, FormBuilder, Validators, FormArray } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Subscription';
import { NewQ } from './NewQ';
import { IMyDpOptions } from 'mydatepicker';
//import { IMultiSelectOption } from 'angular-2-dropdown-multiselect';

@Component({
    templateUrl: './newq.component.html'
})
export class CreateNewQComponent implements OnInit{
    private myDatePickerOptions: IMyDpOptions = {
        dateFormat: 'dd.mm.yyyy',
    };
    pageTitle: string;
    newQForm: FormGroup;
    agencyForm: FormGroup;
    newq: NewQ = new NewQ();
     model: number[];
    private sub: Subscription;
    //get nqCoordinators(): FormArray {
    //    return <FormArray>this.agencyForm.get('nqCoordinators');
    //}

    constructor(private route: ActivatedRoute, private fb: FormBuilder, private router: Router) { }
    //myOptions: IMultiSelectOption[] = [{ id: 1, name: 'Bob' }, { id: 2, name: 'Nick' },];

    ngOnInit(): void
    {
        this.newQForm = this.fb.group({
            firstName: ['', Validators.required],
            middleName: '',
            lastName: '',
            status: ['', Validators.required],
            role: ['', Validators.required],
            phone: ['', Validators.required],
            email: ['', [Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+'), Validators.required]],
            nqCapacity: '',
            address1: '',
            address2: '',
            city: ['', Validators.required],
            state: ['', Validators.required],
            country: '',
            zip: '',
            agencyAssociation: ['', Validators.required],
            emdCertification: '',
            emdExpiryDate: '',
            efdCertification: '',
            efdExpiryDate: '',
            epdCertification: '',
            epdExpiryDate: '',
            regionalImplementer: '',
            academyInstructor: '',
            testScores: '',
            timesTestTaken: '',
            startDate: ['', Validators.required],
            contractSigned: '',
            contractDate: ['', Validators.required],
            approvalletter: '',
            teamViewerId: '',
            teamViewerPwd: '',
            notes: ''
        });

        this.agencyForm = this.fb.group({
            agencyID: '',
            agencyName: ['', Validators.required],
            agencyCity: ['', Validators.required],
            agencyState: ['', Validators.required],
            agencyPhoneNumber: ['', Validators.required],
            salesRep: [''],
            contractTerm: ['', Validators.required],
            renewalDate: '',
            qStatus: ['', Validators.required],
            isNewCustomer: true,
            priority: ['', Validators.required],
            discipline: ['', Validators.required],
            nqCoordinators: this.fb.array([this.initNqCoordinators()]),
            qAdvisors: this.fb.array([this.initQAdvisors()]),
            nq1: '',
            nq2: '',
            nq3: '',
            nq4: '',
            nqStartDate: '',
            followUpDate: '',
            consultant: '',
            primerClassPerson: '',
            primerClassDate: '',
            itContactName: '',
            itContactPhone: '',
            itContactEmail: ['', Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+')],
            edqContactName: '',
            edqContactPhone: '',
            edqContactEmail: ['', Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+')],
            vpnType: ['', Validators.required],
            recorder: '',
            version: '',
            isAce: true,
            callLoad: '',
            goLive: ''
        });

        this.agencyForm.controls['salesRep'].valueChanges
            .subscribe((selectedOptions) => {
                // changes
            });
        this.sub = this.route.params.subscribe(
            params => {
                let id = +params['id'];
                if (id === 0)
                    this.pageTitle = 'Add Q';
                else
                    this.pageTitle = 'Edit Q';
            }
        );
        
    }
    initNqCoordinators() {
        return this.fb.group({
            nqCoordinators: ''
        })
    }
    initQAdvisors() {
        return this.fb.group({
            qAdvisors: ''
        })
    }

    setDate(): void {
        // Set today date using the setValue function
        let date = new Date();
        this.newQForm.setValue({
            startDate: {
                date: {
                    year: date.getFullYear(),
                    month: date.getMonth() + 1,
                    day: date.getDate()
                }
            }
        });
    }

    clearDate(): void {
        // Clear the date using the setValue function
        this.newQForm.setValue({ startDate: null });
    }

    addNqCoordinators() {
        const control = <FormArray>this.agencyForm.controls['nqCoordinators'];
        control.push(this.initNqCoordinators())

    }
    addAdvisors() {
        const control = <FormArray>this.agencyForm.controls['qAdvisors'];
        control.push(this.initQAdvisors())

    }

    add() {
        console.log(this.newQForm);
        console.log('Saved: ' + JSON.stringify(this.newQForm));
    }

    addAgency() {
        console.log(this.newQForm);
        console.log('Saved: ' + JSON.stringify(this.newQForm));
    }

    backBtnClick() {
        this.router.navigate(['/newq']);
    }
}

component.html file

 ```
 <div class="form-group">
                                    <div class="col-md-3 ">
                                        <label for="datetimepicker1">NQ StartDate<span class="compulsary">*</span></label><br>
                                        
                                        <my-date-picker name="startDate" [options]="myDatePickerOptions"
                                                        formControlName="startDate"></my-date-picker>
                                    </div>
                                </div>
```

**Comment by kekeh** [comment]
In systemjs.config.js replace mydatepicker.umd.min.js with mydatepicker.umd.js

Remove from the same file:
mydatepicker:{
    main: "index.js"
}

**Comment by animishas** [comment]
I did that same error message appears. FYI I have two module.ts files. one for the the product I am working on q.module.ts and one in the app.module.ts.
![datepick2](https://user-images.githubusercontent.com/25496038/26982128-a0fa80c8-4cf4-11e7-9717-2f57d492f56c.PNG)

and I have imported mydatepicker in the q.module.ts file but not the app.module. Do you think that might cause some issues?

**Comment by animishas** [comment]
Okay, I guess my Chrome browser has some issues. No matter what I change it seems to throw some errors at me. I switched to Internet Explorer and it seems to be working man! Thank you so much!! I really appreciate your help!. Thanks for your post and the support you're giving to the people.

**Comment by kekeh** [comment]
I have tested only one app module and it worked Ok, but it was few week ago.

Error message indicates that mydapicker did not found. Can you check under node_modules folder that there is mydatepicker folder. In the mydatepicker there must be index.d.ts and index.js files.

You can also try to reinstall package.

**Comment by animishas** [comment]
Sorry, If you didn't saw my prev message. Its working on the Internet Explorer but Chrome seems to throw the same errors at me. Thanks a lot for your help Kekeh, I appreciate your help. You're awesome!!!

**Comment by d-damien** [comment]
Error is still present :/
