### ISSUE TITLE
Custom text in input label 

### ISSUE THREAD

**Issue by rejmank** [kekeh/mydatepicker#314]
Hi,
is there any way to set custom text of <input> instead of just date?

**Comment by kekeh** [comment]
You can put **mmm** to date format and it shows month as a text. For example set format to **dd mmm yyyy** which shows the selected date for example **27 May 2017**.

You can try it here: http://kekeh.github.io/mydatepicker

If you mean a placeholder text of the input box you can use the **placeholder** attribute. For example:
```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)" 
    [placeholder]="placeholder"></my-date-picker>
```

```javascript
private placeholder: string = 'select a date';
```

**Comment by rejmank** [comment]
I use datepicker as 'range'. User select a date and i count range and highlight it. And i neeed to display range instead of date. So i need fully custom text in input box. Is i possible? Thank's

**Comment by kekeh** [comment]
If you want custom input box you have to create own version of the component. You can start here: https://github.com/kekeh/mydatepicker#development-of-this-component

But I have also done similar **date range picker** if you want a range probably you can use it:
- repository: https://github.com/kekeh/mydaterangepicker
- demo: https://kekeh.github.io/mydaterangepicker

**Comment by rejmank** [comment]
and in nxg-mydatepicker? Is there any difference from mydatepicker?

**Comment by kekeh** [comment]
It is almost similar as mydatepicker but input box and buttons of it are your code so you can easily set own styles to them. There is not locale attribute in the ngx-mydatepicker.

In mydatepicker the input box is inside the component so it is difficult to set styles to it from the host application.
