### ISSUE TITLE
How To Add Arabic locale 'ar' 

### ISSUE THREAD

**Issue by Mohamed-Gamal2015** [kekeh/mydatepicker#315]
I tried to add 
"ar": {
                dayLabels: { su: "الأحد", mo: "الاثنين", tu: "الثلاثاء", we: "الاربعاء", th: "الخميس", fr: "الجمعة", sa: "السبت"},
    monthLabels: {  1: "يناير", 2: "فبراير", 3: "مارس", 4: "ابريل", 5: "مايو", 6: "يونيو", 7: "يوليو", 8: "أغسطس", 9: "سبتمبر", 10: "أكتوبر", 11: "نوفمبر", 12: "ديسمبر" },
                dateFormat: "yyyy-mm-dd",
                todayBtnTxt: "اليوم",
                firstDayOfWeek: "sa",
                sunHighlight: true,
            }
in this.locales and changed the default to ar , but nothing changed

**Comment by kekeh** [comment]
Can you create a pull request and add your locale to this file: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/services/my-date-picker.locale.service.ts

More info: https://github.com/kekeh/mydatepicker#locale-attribute

Do you mean that first day of the week is **sa** = Saturday?

After you have created a pull request I will add your locale to npm package.

**Comment by Mohamed-Gamal2015** [comment]
Yes i mean Saturday

**Comment by kekeh** [comment]
Pull request merged.
