### ISSUE TITLE
read only mode (reactive forms)

### ISSUE THREAD

**Issue by AndiiAlbu** [kekeh/mydatepicker#317]
I've created own component which is a wrapper for your component. All options I set up in onInit method
```
ngOnInit() {
    this.setUpPicker();
  }
```

```
public setUpPicker() : void {
    this.options.minYear = !!this.minYear ? this.minYear : CONFIG.defaultYearValues.min;
    this.options.maxYear = !!this.maxYear ? this.maxYear : CONFIG.defaultYearValues.max;
    this.options.inline = this.inline;
    this.options.indicateInvalidDate = true;
    this.picker.locale = CONFIG.locale;
    this.picker.setLocaleOptions();
  }
```
And implemented ControlValueAccessor interface in which methods I called implementation of your component methods

```
writeValue(obj: any): void {
    this.picker.writeValue(obj);
  }
  registerOnChange(fn: any): void {
    this.picker.registerOnChange(fn);
  }
  registerOnTouched(fn: any): void {
    this.picker.registerOnTouched(fn);
  }
  setDisabledState(isDisabled: boolean): void {
    this.picker.writeValue(isDisabled);
  }
```

Then in third component I created form using form  builder. Now I want to use read only mode.
I set up form control in next way:

`'birthDate': [{ value: bDate, disabled: this.readOnly }, [this.validateBirthDate]].`

In my template it looks like
`<date-picker id="birthDate" name="birthDate" formControlName="birthDate" [placeholder]="'Birth Date'"></date-picker>`

but datepicker isn't disabled. Can set disable mode only when use attribute 
`[disabled]="readOnly"`.

How to disable component in right way (when use reactive form) ?

I tried to disable control in next way
```
if (this.readOnly)
    this.form.get('birthDate').disable();
```
But this doesn't work.

**Comment by kekeh** [comment]
You can disable component for example in the ngOnInit() function or calling the disableComponent() function:
```html
<my-date-picker name="myDate" [options]="myOptions" 
    formControlName="myDate"></my-date-picker>
```

```javascript
ngOnInit() {
    // Set initial date 09.10.2018 and disables component
    this.myForm = this.formBuilder.group({
        myDate: [{value:{date: {year: 2018, month: 10, day: 9}}, disabled: true}] 
    });
}

disableComponent(): void {
    // Calling this disables the component
    this.myForm.controls["myDate"].disable();
}
```

**Comment by AndiiAlbu** [comment]
Thanks for quick answer. But this way doesn't work for me. I've solved this problem by another implementation setDisabledState method in my component

```
setDisabledState(isDisabled: boolean): void {
    this.options.componentDisabled = isDisabled;
    this.options = Object.assign({}, this.razorDatePickerOptions);
  }
```

**Comment by kekeh** [comment]
Update the latest version. It works then. I have recently added this functinality.
