### ISSUE TITLE
Update to RC6

### ISSUE THREAD

**Issue by Tgure** [kekeh/mydatepicker#32]
Hello,

Could you update this to RC6?

**Comment by kekeh** [comment]
Updated to Angular 2 RC 6.

**Comment by Tgure** [comment]
@kekeh Thanks for updating it, I am getting a few errors in terminal when I start the project.

- node_modules/mydatepicker/src/my-date-picker/my-date-picker.component.ts:14:5 
    An object literal cannot have multiple properties with the same name in strict mode.

- node_modules/mydatepicker/src/my-date-picker/my-date-picker.component.ts:14:5 
    Duplicate identifier 'template'.

Also those same errors are reported on line 10 of sample-date-picker-inline.ts and sample-date-picker-normal.ts

**Comment by kekeh** [comment]
I am not able to reproduce the error but I did some changes. Retest with the laster version.

**Comment by Tgure** [comment]
@kekeh That fixed the errors.  Thank you.
