### ISSUE TITLE
i want to dynamic tagging one day each month

### ISSUE THREAD

**Issue by ZzzzzZXxxxxX** [kekeh/mydatepicker#320]
i want to mark one day when month change。
` public myDatePickerOptions: IMyDpOptions = {`
    `  dateFormat: 'dd.mm.yyyy',`
    `  inline: true,`
  `};`
`onCalendarViewChanged(event: IMyCalendarViewChanged){`
    `let that = this;`
    `setTimeout(function () {`
      `let x = that.getCopyOfOptions();`
`      x.markDates = [{dates: [{year: 2017, month: event.month, day: 18}], color: 'red'}];`
`      that.myDatePickerOptions = x;`
`    },1000);`
  `}`
 ` getCopyOfOptions(): IMyOptions {`
`    return JSON.parse(JSON.stringify(this.myDatePickerOptions));`
`  }` 
`<my-date-picker [options]="myDatePickerOptions" [defaultMonth]='defaultMonth' (calendarViewChanged)="onCalendarViewChanged($event)" (dateChanged)="onDateChanged($event)" required></my-date-picker>`
this was don't work.but if inline was false it success. why?
when inline was true, `onCalendarViewChanged()` will endless loop...

**Comment by kekeh** [comment]
I did one fix. Try version **2.0.16**.
