### ISSUE TITLE
Datepicker doesn't display epoch time

### ISSUE THREAD

**Issue by tomasznastaly** [kekeh/mydatepicker#321]
Hello, seems i found a bug. I want to set initial value in formBuilder:

  private buildVersionForm() : FormGroup {
    return this.formBuilder.group({
      revisionDate: [{ epoc: 1497564000 }],
    });
  }

it doesn't work:
revisionDate: [{ epoc: .1497564000 }],
it also doesn't work:
revisionDate: [{ formatted: "10-02-2017" }],

but it works:
revisionDate: [{ date: { day: 1, month: 6, year: 2017 } }],
and date is displayed in the datepicker.

seems it's bug. Any idea how i can pass the epoch time?

best regards

**Comment by kekeh** [comment]
It is not a bug. You can bind only **date** or **jsdate** properties. The **date** is **IMyDate** object like your example above and the **jsdate** is javascript date object. See examples below:
```javascript
revisionDate: [{ date: { day: 1, month: 6, year: 2017 } }],
```
```javascript
let mydate: Date = new Date(2017, 5, 1, 0, 0, 0, 0);
revisionDate: [{ jsdate: mydate }],
```

If you have epoc time you can do as follows:
```javascript
let mydate: Date = new Date(epoctime * 1000);
revisionDate: [{ jsdate: mydate }],
```
