### ISSUE TITLE
Potential bug: selecting current date produces null date

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#323]
### Steps to reproduce

1. Browse to demo http://kekeh.github.io/mydatepicker/ 
1. Scroll down to *Inline mode* example
1. Click on a some date A: the clicked date shows up on the right in some text format
1. Click again on same date A

### Expected output

* The same formatted text should be visible on the right, there should be no visible change

### Actual output

* Formatted text field disappears

### Additional info

* Under the covers, by debugging one of our applications, it seems like emitted date value is null.
* Not sure which version is now running on demo site, but we are using 2.0.1 and problem is there

**Comment by kekeh** [comment]
There is option allowDeselectDate. Set it to false to prevent above situation. The option is added recently so update the latest version at first.

**Comment by BrainCrumbz** [comment]
Thanks a lot for your feedback. Will try the latest version!

**Comment by clement911** [comment]
Was that released?
I can see that it is in the source at https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.ts#L563
however when I pull the latest package v2.0.24 the option is not being used, as if the node module contained an old version of the component.
Strangely, in the mydatepicker.und.js file, it does seem to be used.

**Comment by kekeh** [comment]
I installed latest version from the npm and the **mydatepicker.umd.js** file contained the **allowDeselectDate** option. No problem.

In some users npm retuns old version of the component. Try again:
  - **npm remove mydatepicker**
  - **npm install mydatepicker --save**

**Comment by clement911** [comment]
Yes but it is not in the individual component file

**Comment by kekeh** [comment]
What do you mean by component file?

**Comment by clement911** [comment]
I mean the my-date-picker.component.js. sorry i reinstalled the package and it worked! I had a weird scenario where the umd js file was the latest but the component was old...
