### ISSUE TITLE
Do you have plan for add Buddhist Calendar ?

### ISSUE THREAD

**Issue by Aofhero** [kekeh/mydatepicker#324]
**Hi kekeh**

Do you have plan for add **Buddhist Calendar**, I like your calendar so much, And need
use it with real work.

Please tell me for my question. 
Best regard, Thanks.

<img width="700" alt="screen shot 2560-06-02 at 11 11 04 am" src="https://cloud.githubusercontent.com/assets/23328546/26710566/f8ea6462-4784-11e7-9008-74eaf746b245.png">

**Comment by kekeh** [comment]
Hello @Aofhero 

I don't have this kind of plan.
