### ISSUE TITLE
Default selected date not working after updating to 2.0.8

### ISSUE THREAD

**Issue by jmat992** [kekeh/mydatepicker#325]
Previously I was able to set a default value on page load. But since I updated the plugin to 2.0.8, the datepicker is not showing the default set value. Please help!

**Comment by kekeh** [comment]
At first update the latest version 2.0.17. If it doesn't help let me know how you try to set initial date.

**Comment by kekeh** [comment]
Closing this because no answer. You can reopen the issue if you have still same problem.
