### ISSUE TITLE
Error from formGroup example

### ISSUE THREAD

**Issue by TeodorKolev** [kekeh/mydatepicker#326]
I am trying to implement formGroup example 2 and I get next error:
`Can't bind to 'formGroup' since it isn't a known property of 'form'.`
Any ideas how to fix it?

**Comment by kekeh** [comment]
You have to import the ReactiveFormsModule in your @NgModule.

Like here: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-module.ts#L13
