### ISSUE TITLE
Unable to get epoc from manual setDate

### ISSUE THREAD

**Issue by TeodorKolev** [kekeh/mydatepicker#327]
I am unable to get proper object when I set date manually. Code used from example:
`private model: Object = { date: { year: 2018, month: 10, day: 9 } };`
produce
`Object {date: Object}`]
while click on datepicker produce
`Object {date: Object, jsdate: Sat Jun 24 2017 00:00:00 GMT+0300 (FLE Daylight Time), formatted: "24-Jun-2017", epoc: 1498251600}`
how can I get first object to work properly? Is that possible? My target is to take epoc from set date.

**Comment by kekeh** [comment]
It is not possible. Epoc time is available after the user selects the date. You have to calculate epoc in first phase. Something like below:
```javascript
let initdate: Date = new Date(2018, 9, 9, 0, 0, 0, 0);
private model: any = { jsdate: initdate };
let epoc: number = initdate.getTime() / 1000;
```

You can use **jsdate** property to set initial date. It is javascript date object.
