### ISSUE TITLE
Pre Populate from BAck end

### ISSUE THREAD

**Issue by desbond** [kekeh/mydatepicker#328]
If I am editing a user with a date field and receive the date in the object from the webapi how can I pre populate the date picker with the date and submit a date object back to the webapi on submit ?

**Comment by kekeh** [comment]
- If you are using ngModel binding read this: https://github.com/kekeh/mydatepicker#1-ngmodel-binding
- If you are using reactive forms read this: https://github.com/kekeh/mydatepicker#2-reactive-forms

**Comment by desbond** [comment]
What I actually did was create a java POJO using the same struct {year,day,month} and pass that from the webapi. Seems to work nicely. So conversion to date all happebns on the jersey side.
