### ISSUE TITLE
Does not work with angular-cli/1.1.0

### ISSUE THREAD

**Issue by markusapfler** [kekeh/mydatepicker#329]
When running a production build, this error-message appears:
```
 ERROR` in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'myDpStyles'. Consider exporting the symbol (position 9:7 in the original .ts file), resolving symbol `MyDatePicker
```
A workaround is to disable AOT, but it would be nice if I could let it turned on.

**Comment by kekeh** [comment]
Did you install module from the npm and follow instructions from here: https://github.com/kekeh/mydatepicker#installation

In the npm package there should not be symbol named **myDpStyles**. It is only source code in git repository: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.ts#L9

but building the npm package removes the line.

**Comment by markusapfler** [comment]
I have now looked again through the open Issues and found out that I have the exact same problem as mentioned in Issue #281 .
There is no index.d.ts file in the root directory of mydatepicker after `npm install`

**Comment by kekeh** [comment]
I tried to install from the npm and installed package of mydatepcker (2.0.17) was ok. You can try again:
- npm remove mydatepicker
- npm install mydatepicker --save

**Comment by markusapfler** [comment]
I don't know why, but it works now.

I tried npm install/remove a few times and after the 4th try suddenly the correct files were loaded.
Very strange behavior.

Thanks for your help!

**Comment by Sai-Maha** [comment]
Hi , Did you find any solution for that we too face the same problem. 
I have tried remove, clean and install.
![image](https://user-images.githubusercontent.com/30037073/58409915-b90f2680-808e-11e9-80d3-4ebf7e05cd91.png)
