### ISSUE TITLE
[Clarification] How to move picker back to default month

### ISSUE THREAD

**Issue by GiuseppePiscopo** [kekeh/mydatepicker#330]
Scenario:

1. In a component, `this.myDefaultMonth` is bound to some my-date-picker `defaultMonth` attribute. Datepicker has `inline` option set to *true*.
1. In component constructor or in *ngOnInit*, `this.myDefaultMonth` is set to some proper value, say `"2017-06"`
1. User moves by a couple of years in the future, say up to June 2022
1. After some event, application has to programmatically "move picker back" to show the aforementioned default month, June 2017. 

How do you obtain that? Is it enough to set again `this.myDefaultMonth` to a **new instance** of a string containing `"2017-06"`?

Thanks

**Comment by kekeh** [comment]
At first you have to update the latest version (**2.0.18**) in order the following work.

This https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.ts#L369 function is detecting changes. Every time when the value of **defaultMonth** is changed it is called with a new value.

In step 4 you have set calendar back to June 2017. In step 2 the value of defaultMonth is already **2017-06**. For example in step 4 setting value to **2017/06** is change and the default month of the calendar is set back to June 2017.

In step 4 you change only delimiter of the value. So if you want to refresh the value of defaultMonth, change only delimiter.

Delimiter can be any special character.

**Comment by GiuseppePiscopo** [comment]
Hi there.

Thanks for your update. Sadly this approach is not really doable for us. Imagine everytime program has to revert back to default month: should you store somewhere that last time you "wrote" `2017/06`, so next you should write `2017-06`, and then again ...

If you'd like, I can suggest to more viable approaches, one of which works for sure:

1. (*this works for sure*) Create some interface like

    ```ts
    public interface DefaultMonthCommand {
      month: string;
    }
    ```

    and turn `defaultMonth` option to this type, instead of string. Everytime client code wants to set a value, it will create a new instance, which will be successfully detected by `ngOnChanges`:

    ```ts
    myDefaultMonthCmd: DefaultMonthCommand;
    // ...
    this.myDefaultMonthCmd = {
      month: "2017-06",
    };
    ```

1. (*this one, I don't know*) Leave `defaultMonth` as a string as is now. Then verify if the following is detected by `ngOnChanges`:

    ```ts
    myDefaultMonth: string;
    // ...
    this.myDefaultMonth = "2017-06".slice(0);
    ```

   If that works, leave code as it was and just update docs to highlight this particular detail.

What do you think of it? 
Cheers

**Comment by kekeh** [comment]
Yes it better to pass object. I added a new interface. More info from here: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

This change is in version 2.0.19
