### ISSUE TITLE
Header Buttons with bootstrap-rtl

### ISSUE THREAD

**Issue by Mohamed-Gamal2015** [kekeh/mydatepicker#332]
![untitled](https://user-images.githubusercontent.com/11632297/26845193-fac300f4-4af5-11e7-9100-687e7d3e5848.png)

The header buttons doesn't show in appropriate way when using bootstrap-rtl

**Comment by ahmedalattar** [comment]
you can add this class my-date-picker .selector.selectorarrow  .header tbody tr{direction: ltr }

it will work correctly
