### ISSUE TITLE
Can I change the config of the picker after the component is initialized?

### ISSUE THREAD

**Issue by Liranius** [kekeh/mydatepicker#336]
Sorry to bother you again. I need to dynamicly change the picker's disableUntil and disableSince properties. I know that change values of properties of binded option will not trigger ngOnChange, so I temporarily set the option to {} and then to the modified option, but still nothing changed. So I want to ask you if there is a way to do so?

**Comment by Liranius** [comment]
Never mind, I find that redeclare a option object and copy properties of existing one to the new one and then modify the new one's properties and bind it to the picker works. This is no longer an issue. Sorry again.

**Comment by kekeh** [comment]
Example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option
