### ISSUE TITLE
Value of the date is going as one day less while saving. I mean, when i give the date as 06-12-2017 in ISO format, then the value is going as 06-11-2017 in ISO format. So need help on this.

### ISSUE THREAD

**Issue by praveenaccion** [kekeh/mydatepicker#340]
Value of the date is going as one day less while saving. I mean, when i give the date as 06-12-2017 in ISO format, then the value is going as 06-11-2017 in ISO format. So need help on this.

**Comment by kekeh** [comment]
If you use **jsdate** property it is javascript date object and month numbering is starting from zero. If it is not a case write step by step instructions how to reproduce this issue.

**Comment by kekeh** [comment]
I close this because no answer. You can reopen the issue if you still have the same problem.
