### ISSUE TITLE
Feature request: Year selection only

### ISSUE THREAD

**Issue by experionakash** [kekeh/mydatepicker#341]
Hi, is there exist any configuration to choose only dates using this component?
I tried the following configuration, but it is not changing the UI of the date picker component.

private yearPickerOptions: IMyDpOptions = {
        dateFormat: 'yyyy',
        yearSelector: true,
        editableDateField: false
    };

**Comment by kekeh** [comment]
You can choose only dates. Date format option have to contain **dd**, **mm** or **mmm**, **yyyy**. For example: dd.mm.yyyy

**Comment by experionakash** [comment]
Sorry kekeh , There is a mistake from my side. Actually, I need to only select the year by using this component. Is that possible?

Thanks.

![11 - subscription renewal web portal](https://user-images.githubusercontent.com/23092972/27125178-0f25b0de-5111-11e7-871c-c5d1dfed58ca.png)

**Comment by kekeh** [comment]
Not possible. This is date picker not year picker.
