### ISSUE TITLE
Value accessor directly on component

### ISSUE THREAD

**Issue by codefactorydevelopment** [kekeh/mydatepicker#343]
If datepicker is a part of the bigger form and user changes some other fields but doesn't touch datepicker, then onChange callback never gets fired.
Is there a way to access value of the datepicker directly and not only through callback?

thanks

**Comment by kekeh** [comment]
You can use:
- ngModel binding: https://github.com/kekeh/mydatepicker#1-ngmodel-binding
- reactive forms: https://github.com/kekeh/mydatepicker#2-reactive-forms

The **dateChanged** callback is optional. If you set initial date with ngModel or reactive forms you can use its value if user change or don't change the date.
