### ISSUE TITLE
minYear option is not handled properly

### ISSUE THREAD

**Issue by omidsakhi** [kekeh/mydatepicker#344]
Setting the minYear does disable some of the buttons in setHeaderBtnDisabledState. However, the following steps breaks the logic.

1. Select a minYear. Let's say 1/1/1970.
2. Click on the date picker and then click on the year to see the list of years.
3. Navigate up to select year 1970.
4. Verify that previous month and previous year buttons are disabled.
5. Click on any of the days (29, 30, 31) of December 1969 which are visible on the date picker.
6. From this point on, previous month is not disabled and any date prior to minYear can be selected.

The bug was uncovered in our PQA department.

**Comment by kekeh** [comment]
I fixed this bug in version **2.0.21**. Update mydatepicker to this version.
