### ISSUE TITLE
Display datepicker outside container

### ISSUE THREAD

**Issue by dangviettuan** [kekeh/mydatepicker#345]
![image](https://user-images.githubusercontent.com/11323132/27170500-54f90062-51d8-11e7-89ee-978095d2bf9e.png)

**Comment by kekeh** [comment]
Probably your container has **overflow: hidden** style.

**Comment by udoga** [comment]
My outside container should be scrollable, so it has "overflow-x: auto" property.
But date selection should pop out from that div.
Is there any solution for this?
