### ISSUE TITLE
Calendar caret/selector points to the wrong field

### ISSUE THREAD

**Issue by aysha-williams-develop** [kekeh/mydatepicker#348]
![image](https://user-images.githubusercontent.com/1369688/27343500-5ad97248-55a0-11e7-9229-b22c291579f1.png)

**Comment by kekeh** [comment]
You can disable selector arrow by setting **showSelectorArrow** option to **false**. It is not possible to show it in the bottom of calendar.

**Comment by aysha-williams-develop** [comment]
I set showSelectorArrow  to false, but the caret still shows up. I was able to use css to hide it though.
