### ISSUE TITLE
How to add tabindex Attribute to .btnpicker and .btnclear

### ISSUE THREAD

**Issue by mgrn0** [kekeh/mydatepicker#349]
We have a project in which the client wants to step from input fields to the next with the keyboard (tab key) and wants to skip the datepicker input / have a different tab order set. We tried to add the attribute in the template markup but however it does not show up in production builds. It DOES show up in local dev setup (just "ng serve"), though.

Any advice / best practice how I can get that attribute added to those two buttons? 

![screen shot 2017-06-21 at 13 47 46](https://user-images.githubusercontent.com/3019226/27382737-6db51820-5688-11e7-9740-0baaefd4bd25.png)

**Comment by kekeh** [comment]
If you want to edit the HTML template you can create own version of the component. Here are instructions (Build a local npm installation package): https://github.com/kekeh/mydatepicker#development-of-this-component
