### ISSUE TITLE
How to Clear Value Without formControll

### ISSUE THREAD

**Issue by Aofhero** [kekeh/mydatepicker#353]
I can't clear value by ngModel binding and i not use formControll ng2

Sample I use 
```
<my-date-picker (dateChanged)="onDateChanged($event)"
         [(ngModel)]="model"></my-date-picker>
```

In TS file 
```
 onDateChanged(event){
   if(event.date.year < 2014){
       this.model = null
   }
 }
```

But can't clear value in textbox

**Comment by kekeh** [comment]
Try to set timeout as follows:

In TS file 
```javascript
onDateChanged(event) {
    setTimeout(() => {
        if(event.date.year < 2014){
            this.model = null;
        }
    });
}
```

**Comment by kekeh** [comment]
You can also use minYear or disableUntil option to prevent user to select dates lower than 2014. It would be better way.

**Comment by kekeh** [comment]
You can also use **minYear** or **disableUntil** option to prevent user to select dates lower than 2014. It would be better way.

For example:
```javascript
myOptions: IMyDpOptions {
    // other options here...
    minYear: 2014
}
```

or 
```javascript
myOptions: IMyDpOptions {
    // other options here...
    disableUntil: {year: 2013, month: 12, day: 31}
}
```
