### ISSUE TITLE
on date selection gets InvalidPipeArgument: '[object Object]' for pipe 'DatePipe' error

### ISSUE THREAD

**Issue by AmitGera007** [kekeh/mydatepicker#355]
I gets below error when I pass date like "07-07-2016" , this not gets bound to datepicker
after that when I try to select date from datepicker gets below error:
on date selection gets InvalidPipeArgument: '[object Object]' for pipe 'DatePipe' error

Datepicker works only when I pass date as :
 private model: Object = { date: { year: 2016, month: 07, day: 07 } };

**Comment by kekeh** [comment]
In the latest version you can pass also date string to the model. For example:

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions"
    [ngModel]="dateObj" required>
```

```javascript
class MyComponent implements AfterViewInit {
    private dateObj: any = null;

    constructor() {}

    ngAfterViewInit() {
        this.dateObj = {formatted: '07-07-2016'};
    }
}
```

You have to update the latest version **2.0.22** in order the above works.
