### ISSUE TITLE
Datepicker not working in firefox

### ISSUE THREAD

**Issue by Googlyyash** [kekeh/mydatepicker#357]
![datepicker](https://user-images.githubusercontent.com/14040780/27627192-7fc5098c-5c08-11e7-9a69-b8e359a01495.PNG)

only calender icon is shown
![_datepicker](https://user-images.githubusercontent.com/14040780/27627295-e8a8ad46-5c08-11e7-94ba-668c6f632979.PNG)

**Comment by kekeh** [comment]
It is working with Firefox. You can test here: http://kekeh.github.io/mydatepicker

propably you have **showInputField** option **false**. Set it to **true** and input field is shown

**Comment by JaroslavPrt** [comment]
same issue

**Comment by alissonssz** [comment]
I'm having the same issue, and I wrap the datepicker like @JaroslavPrt did, but it doesnt work as well. 

Firefox v59.
