### ISSUE TITLE
datepicker not binding model date, shows given placeholder

### ISSUE THREAD

**Issue by AmitGera007** [kekeh/mydatepicker#358]
Hi ,
I have modelDate like below:
myModel.StartDate = new Date("07/07/2016");

and my HTML like this:

<my-date-picker  placeholder="Select a date" 
(dateChanged)="onDateChanged($event)" 
[options]="myDatePickerOptions" 
[(ngModel)]="myModel.StartDate" required>
</my-date-picker>

Datepicker is not binding provided myModel.StartDate.  Instead it is showing given placeholder.
I am getting this myModel.StartDate from API call.

**Comment by kekeh** [comment]
You can do:

myModel.StartDate = {formatted: '07/07/2016'};

At first update the latest version: 2.0.22
