### ISSUE TITLE
Improvement: UI indicator for invalid date

### ISSUE THREAD

**Issue by rjbazan** [kekeh/mydatepicker#36]
First of all, thanks for creating/mantaining this great component.

I was wondering if there is a way to indicate the user he is entering and invalid date and that the `selectDate` API is not triggering.
One option can be a placeholder displaying `options.dateFormat `property, another one could be displaying a red border until the date validation succeeds. What do you think?

**Comment by kekeh** [comment]
I have done service https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/services/my-date-picker.date.validator.service.ts which validates the user input. If the user input is valid date, parent is notified normal way (dateChanged callback).

Date format could be optional placeholder to input field. Also red border in case of invalid date is good idea.

Thanks.

Thanks.

**Comment by kekeh** [comment]
I added **indicateInvalidDate** and **showDateFormatPlaceholder** options.
