### ISSUE TITLE
disableuntil not working for me

### ISSUE THREAD

**Issue by AmitGera007** [kekeh/mydatepicker#362]
Here is my code:
When I select start date, disable until not working for end date.

<my-date-picker  name="startDate" 
#startDate="ngModel"
 (dateChanged)="onStartDateChanged($event)"
 [options]="myDatePickerOptions" 
[(ngModel)]="currentStartDate" 
required></my-date-picker>

  <my-date-picker   
name="endDate"
 #endDate="ngModel"
 [options]="endDate"
 [(ngModel)]="currentEndDate" 
required><
/my-date-picker>

 onStartDateChanged(event: IMyDateModel) {
        let d: Date = event.jsdate;
        //// set previous date
        d.setDate(d.getDate() - 1);
        let copy: IMyOptions = this.getCopyOfEndDateOptions();
        copy.disableUntil = { year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate() };
        this.endDate = copy;
    }

    onEndDateChanged(event: IMyDateModel) {
        // end date changed...
    }
    getCopyOfEndDateOptions(): IMyOptions {
        return JSON.parse(JSON.stringify(this.endDate));
    }
    private startDate: IMyDpOptions = {};

    private endDate: IMyOptions = {
        disableUntil: { year: 0, month: 0, day: 0 }
};

**Comment by kekeh** [comment]
Here is example: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

**Comment by AmitGera007** [comment]
thanks this has worked
