### ISSUE TITLE
clear date selection

### ISSUE THREAD

**Issue by shankmr** [kekeh/mydatepicker#366]
Hi, I want to clear all dates selection on a button click. I am not able to find anything related to that.

**Comment by kekeh** [comment]
If you are using **ngModel** set model value to **null** as follows:
```javascript
clearDate(): void {
    this.model = null;
}
```
or reactive forms:
```javascript
clearDate(): void {
    // Clear the date using the setValue function (use null or empty string)
    this.myForm.setValue({myDate: null});
}
```

**Comment by shankmr** [comment]
Hi I am using ngModel. If I use normal model object it works fine and I was doing the same. But problem is I have a date in string format so I am using pipe to convert it to IMyDate now I am not able to set a null date. Here is my code 

<my-date-picker #mytestDate [options]="myDatePickerOptions"
                      [placeholder]="placeholder" [ngModel]="model|stringToDate" required
      (ngModelChange)="convertDateToString($event)"></my-date-picker>

I tried to use selDate attribute as well but it works fine for first time but if I select any date again the it does not work. Please check.

**Comment by kekeh** [comment]
You can set string format also to model so you don't need a pipe. For example:

  model: string = {formatted: "04.07.2017"};

This is in the latest version of mydatepicker. Then you can set null to model.

**Comment by bugaevski** [comment]
Hi.
I am using ngModel. When user types "not numeric blah-blah" - I want to clear the user input at [Clean] button click. When I set [this.model = null;] at [Clean] - blah-blah remains.
Other than that - mydatepicker works perfectly.
![image](https://user-images.githubusercontent.com/31212708/63537228-48d43d80-c4e3-11e9-893c-a5b13ac316fd.png)

**Comment by bugaevski** [comment]
Basically, there are two issues at/during User's input:
1. [X] button to clear input is not visible. It becomes visible only when you click outside.
2. Any external button/click with attempt to set [this.model = null;] - does not clear user input. The [model] is already null, until the valid date is picked or entered.

**Comment by shubhamsuryavanshi** [comment]
hi i am using date picker want to re initialize the date on month change but i am unable to find any such event because on month change i am calling api for updated dates list for month but in ui it already loads the month and on receiving updated list from api i am not able to update ui for month api responded for.
