### ISSUE TITLE
en locale displays date in yyyy-mm-dd format

### ISSUE THREAD

**Issue by picosam** [kekeh/mydatepicker#368]
Hello, is this format the correct one for the `en` locale?

**Comment by kekeh** [comment]
I don't know is it the right format to **en** locale. If you know right format let me know.

You can still override the date format of locale with the date format of options.

**Comment by picosam** [comment]
Sure, I can also maybe do a pull request. Sorry for not being clear, my question should have rather been: is the default `en` equivalent to `en-US`? If this is the case then the format should be changed, yes.
