### ISSUE TITLE
Issue with getting selected value and paasing it to API

### ISSUE THREAD

**Issue by geetharamu** [kekeh/mydatepicker#371]
https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options.
<my-date-picker [options]="startDate"   formControlName="Start_Date"
                (dateChanged)="onStartDateChanged($event)"></my-date-picker>

<my-date-picker [options]="endDate"   formControlName="End_Date"
                (dateChanged)="onEndDateChanged($event)"></my-date-picker>

I am setting +30 days to end date on start date change to disable the form. When i tried to get the start date  this.myForm.Start_Date, it is printing selected date + 30 days date. But i want to pass only the selected date as start date. Only for disabling end date, i need to set +30 days.
steps followed :
selected start date as 2017-07-11.
Disabled End date = startDate+30 => 2017-08-20, it is happening.
Getting the start date  this.myFrom.Start_Date => it is displaying 2017-08-20. But i wanted the original selected date to pass it to API. Please help me.

**Comment by kekeh** [comment]
Difficult to say without seeing your code.

This should return start date in your case: 
```javascript
this.myForm.controls['Start_Date'].value
```
and this end date:
```javascript
this.myForm.controls['End_Date'].value
```

value is type of **IMyDateModel**

**Comment by geetharamu** [comment]
this.myForm.controls['Start_Date'].value returns selected date as formatted date. But jsdate is adding +30 days. Please help me to get selected date in jsdate object.

one more question - How to get HH:MM:SS in jsdate object? Presently it is displaying 00:00:00

**Comment by geetharamu** [comment]
<form [formGroup]="myForm" (ngSubmit)="submitForm(myForm.value)">
<my-date-picker [options]="startDate" formControlName="Start_Date"
(dateChanged)="onStartDateChanged($event)">

<my-date-picker [options]="endDate" formControlName="End_Date"
(dateChanged)="onEndDateChanged($event)">
</form>

onStartDateChanged(event: IMyDateModel) {
    let d = event.jsdate;
     let copy: IMyOptions = this.getCopyOfOptions();
     d.setDate(d.getDate() + 30);
     copy.disableSince = { 
     year: d.getFullYear(), 
       month: d.getMonth() + 1, 
      day: d.getDate() };
     this.endDate = copy;
  }

submitForm(myForm) {

console.log(myForm.Start_Date);
/** selected Date 14-07-2017. But displayed 
formatted : "2017-07-14"
jsdate: Sun Aug 13 2017 00:00:00 GMT-0500 (Central Daylight Time); */

console.log(myForm.End_Date); 
}


Formatted date is displaying selected date correctly. But jsdate is added +30 days on submission of form. 
I want to disable only end date based on 30 days condition and while getting start date, i want to get selected original date in jsdate. Please help.

**Comment by kekeh** [comment]
In the **onStartDateChanged()** function try create ne Date object as follows:
```javascript
onStartDateChanged(event: IMyDateModel) {
    // let d = event.jsdate;  // remove this
    let d: Date = new Date(event.jsdate.getTime());  // add this
    let copy: IMyOptions = this.getCopyOfOptions();
    d.setDate(d.getDate() + 30);
    copy.disableSince = {
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate() };
    this.endDate = copy;
}

```
