### ISSUE TITLE
Documentation for setting values in reactive forms should use patchValue

### ISSUE THREAD

**Issue by samrantmedia** [kekeh/mydatepicker#372]
Currently the documentation reads like this: 

    setDate(): void {
        // Set today date using the setValue function
        let date = new Date();
        this.myForm.setValue({myDate: {
        date: {
            year: date.getFullYear(),
            month: date.getMonth() + 1,
            day: date.getDate()}
        }});
    }

But this would only work if the form has a single value. It should read patchValue instead of setValue. To use setValue, you must provide all the form values. 

    setDate(): void {
        // Set today date using the setValue function
        let date = new Date();
        this.myForm.patchValue ({myDate: {
        date: {
            year: date.getFullYear(),
            month: date.getMonth() + 1,
            day: date.getDate()}
        }});
    }

**Comment by kekeh** [comment]
Thanks. I fixed it.

**Comment by samrantmedia** [comment]
Thanks, this is the third angular datepicker that I have tried and it definitely works a lot better than the others. Thanks for this

**Comment by samrantmedia** [comment]
ps. i like your parrot
