### ISSUE TITLE
Initialise datepicker with null or empty string with required field

### ISSUE THREAD

**Issue by AmitGera007** [kekeh/mydatepicker#373]
I have used required attribute with date picker control.
On form load as I am using empty date, required attribute message gets displayed.
How to initialise date picker so user will not see required message.

```
 <my-date-picker  placeholder="Select a date" name="endDate"
   [options]="endDateOptions" (dateChanged)="onEndDateChanged($event)" [(ngModel)]="currentEndDate" required ></my-date-picker>

this.currentEndDate = "";
```

**Comment by kekeh** [comment]
You can try the following. When date picker input box lost focus the **Date is required!** message is show. Message is not shown on page load.

Add **#mydp="ngModel"** to the **my-date-picker** tag. Then you can use the **mydp.touched**.
```html
<my-date-picker  placeholder="Select a date" name="endDate" #mydp="ngModel" 
    [options]="endDateOptions" (dateChanged)="onEndDateChanged($event)  
    [(ngModel)]="currentEndDate" required ></my-date-picker>

<p class="error" *ngIf="mydp.touched">Date is required!</p>
```

**Comment by AmitGera007** [comment]
above works on page load.
but when users select any date, still that message remains there

**Comment by kekeh** [comment]
Add mydp.valid to the condition
