### ISSUE TITLE
Feature Request: Disable days (e.g. every Wednesday)

### ISSUE THREAD

**Issue by marcusvetter** [kekeh/mydatepicker#377]
Hi :)

I really like mydatepicker -- it's so awesome to use, but I miss the functionality to disable reoccurring weekdays, like disable every Wednesday and Sunday.
Would it be possible to implement such an option?

Thanks a lot and best regards
Marcus

**Comment by kekeh** [comment]
I added option **disableWeekdays**. For example disable Sundays set option value to:
```javascript
disableWeekdays: ['su']
```
disable Tuesdays and Thursdays set option to:
```javascript
disableWeekdays: ['tu', 'th']
```

This option is in version **2.0.25**

**Comment by marcusvetter** [comment]
Very very nice, thanks a lot!!! :) 👍
