### ISSUE TITLE
Disable all sundays in a datepicker, get selected jsdate object along with timings.

### ISSUE THREAD

**Issue by geetharamu** [kekeh/mydatepicker#379]
I am not able to disable sundays alone. Jsdate is dispalying in the below format. HH:MM:SS as 00:00:00. Please help me to get selected timings as well.
Fri Aug 18 2017 00:00:00 GMT-0500 (Central Daylight Time)

**Comment by kekeh** [comment]
I added option **disableWeekdays**. For example disable Sundays bset option value to:
```javascript
disableWeekdays: ['su']
```

Time values in the **jsdate** object is always zero.

**Comment by gangfang** [comment]
@kekeh Thanks for your awesome work!

For this issue guess you may better modify the doc since people may think **disableWeekdays** is for Mon to Fri excluding Sat and Sun.
