### ISSUE TITLE
My Date Picker fails on Mac but not on Windows

### ISSUE THREAD

**Issue by daddyschmack** [kekeh/mydatepicker#38]
I receive the following errors in the browser (Chrome) when I use this in an angular-2 cli project:
metadata_resolver.js:230Uncaught Error: Unexpected value 'MyDatePickerModule' imported by the module 'AppModule'

Installation results:

xxx-MacBook-Pro:faclient xxxx$ npm install mydatepicker --save

>   \> mydatepicker@0.0.29 postinstall /Users/xxxx/Sites/faclient/node_modules/mydatepicker
>   \> typings install
> 
> typings WARN deprecated 9/19/2016: "registry:dt/node#4.0.0+20160423143914" is deprecated (updated, replaced or removed)
> typings WARN deprecated 6/13/2016: "registry:dt/es6-promise#0.0.0+20160423074304" is deprecated (updated, replaced or removed)
> 
> ├── es6-collections (global)
> ├── es6-promise (global)
> └── node (global)
> 
> forward-air-site@0.0.0 /Users/xxx/Sites/faclient
> └─┬ mydatepicker@0.0.29 
>   ├── @angular/common@2.0.0 
>   ├── @angular/compiler@2.0.0 
>   ├── @angular/core@2.0.0 
>   ├── @angular/platform-browser@2.0.0 
>   ├── @angular/platform-browser-dynamic@2.0.0 
>   ├── es6-shim@0.35.1 
>   ├── reflect-metadata@0.1.3 
>   ├─┬ rxjs@5.0.0-beta.12 
>   │ └── symbol-observable@1.0.2 
>   └── zone.js@0.6.25 

xxx-MacBook-Pro:faclient xxx$ ng serve

> Could not start watchman; falling back to NodeWatcher for file system events.
> Visit http://ember-cli.com/user-guide/#watchman for more info.
> ** NG Live Development Server is running on http://localhost:4200. **
> 11740ms building modules                         30ms ad02798ms2080ms asset72ms emittinggHash: 2e66b3e756f6fc5bbd45
> Version: webpack 2.1.0-beta.22
> Time: 17419ms
>            Asset     Size  Chunks             Chunk Names
>   main.bundle.js  4.65 MB    0, 2  [emitted]  main
> styles.bundle.js  10.2 kB    1, 2  [emitted]  styles
>        inline.js  5.53 kB       2  [emitted]  inline
>         main.map  4.93 MB    0, 2  [emitted]  main
>       styles.map    14 kB    1, 2  [emitted]  styles
>       inline.map  5.59 kB       2  [emitted]  inline
>       index.html  1.05 kB          [emitted]  
> Child html-webpack-plugin for "index.html":
>          Asset     Size  Chunks       Chunk Names
>     index.html  3.42 kB       0       
> webpack: bundle is now VALID.

AppModule (relevant part):

```
import { MyDatePickerModule } from 'mydatepicker/src/my-date-picker/my-date-picker.module';

@NgModule({
    //declarations: [AppComponent],
    imports: [BrowserModule,FormsModule, HttpModule, ReactiveFormsModule, routing, MyDatePickerModule],

```

![image](https://cloud.githubusercontent.com/assets/2753635/18688108/81d14f3a-7f48-11e6-81ce-a4d320c720b9.png)

**Comment by jordanow** [comment]
Don't know if it's related but I'm on Mac too and got this error at `typings install`
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mydatepicker" "--save"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mydatepicker@0.0.29 postinstall: `typings install`
npm ERR! spawn ENOENT
```

**Comment by kekeh** [comment]
@jordanow you can try to add:

`
  "devDependencies": {
    "typings": "^1.3.3"
  }
`

to **package.json** file of you own project and the exute the following commands:
**npm install**
**npm install mydatepicker --save**

you can also try to update node version.

**Comment by kekeh** [comment]
@daddyschmack you can also try **gh-pages** branch of the project. It is sample app and it is running here: http://kekeh.github.io/mydatepicker/

It is webpack project and it is working. **npm run build** command produces the app and the app files are located in **/dist** folder.

Otherwise it is difficult to say why it is working on Windows but not Mac. Maybe there are some version differencies of packages in your Windows and Mac systems?

**Comment by daddyschmack** [comment]
I upgraded to the latest version of clients and everything worked.

On Sep 20, 2016 11:26 PM, "Shailendra Pal" <notifications@github.com> wrote:

Don't know if it's related but I'm on Mac too and got this error at typings
install

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
"mydatepicker" "--save"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mydatepicker@0.0.29 postinstall: `typings install`
npm ERR! spawn ENOENT

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kekeh/mydatepicker/issues/38#issuecomment-248508466>,
or mute the thread
