### ISSUE TITLE
disableDateRange + enableDays shows all dates disabled until month/year change

### ISSUE THREAD

**Issue by nowned** [kekeh/mydatepicker#380]
MyDatePicker Version: 2.0.25

DatePickerOptions
```
private startDatePickerOptions = {
      customPlaceholderTxt: 'Start Date',
      disableDateRanges: [{begin: {year: 2000, month: 1, day: 1}, end: {year: 2030, month: 12, day: 31}}],
      minYear: 2000,
      maxYear: 2030,
      enableDays: []
    };
```

We are programmatically setting the enableDays via a suggestion on the Github Issues
```
let startDateCopy = JSON.parse(JSON.stringify(this.startDatePickerOptions));
startDateCopy.enableDays = availableDates;
this.startDatePickerOptions = startDateCopy;
```

When you first open the datepicker everything displays as disabled
![screen shot 2017-07-16 at 9 31 17 am](https://user-images.githubusercontent.com/1230091/28249386-9057b39e-6a09-11e7-9905-5e3e9ee8717f.jpg)

but if you toggle forward/back the month/year it displays properly
![screen shot 2017-07-16 at 9 31 21 am](https://user-images.githubusercontent.com/1230091/28249394-a0046800-6a09-11e7-9fd5-88cf959e6b32.jpg)

**Comment by kekeh** [comment]
Can you try to set both options dynamically as follows:

```javascript
private startDatePickerOptions = {
      customPlaceholderTxt: 'Start Date',
      disableDateRanges: [],
      minYear: 2000,
      maxYear: 2030,
      enableDays: []
};

ngOnInit(): void {
    this.setDisabledAndEnabled();
}

setDisabledAndEnabled(): void {
    let startDateCopy = JSON.parse(JSON.stringify(this.startDatePickerOptions));
    startDateCopy.disableDateRanges: [{begin: {year: 2000, month: 1, day: 1}, end: {year: 2030, month: 12, day: 31}}],
    startDateCopy.enableDays = availableDates;
    this.startDatePickerOptions = startDateCopy;
}
```

**Comment by nowned** [comment]
@kekeh I just tried that now, sadly no luck, the exact same issue

**Comment by kekeh** [comment]
I tested options and both codes below worked ok.
```javascript
myDatePickerOptions: IMyDpOptions = {
    disableDateRanges: [
        {
            begin: {year: 2000, month: 1, day: 1}, 
            end: {year: 2030, month: 12, day: 31}
        }],
    minYear: 2000,
    maxYear: 2030,
    enableDays: [
        {year: 2017, month: 7, day: 21}, 
        {year: 2017, month: 7, day: 22}, 
        {year: 2017, month: 7, day: 22}
        ]
};
```

```javascript
myDatePickerOptions: IMyDpOptions = {
    disableDateRanges: [],
    minYear: 2000,
    maxYear: 2030,
    enableDays: []
};

onDisableEnable() {
    let copy = this.getCopyOfOptions();
    copy.disableDateRanges = [
        {
            begin: {year: 2000, month: 1, day: 1}, 
            end: {year: 2030, month: 12, day: 31}
        }];
    copy.enableDays =  [
        {year: 2017, month: 7, day: 21}, 
        {year: 2017, month: 7, day: 22}, 
        {year: 2017, month: 7, day: 22}
    ];
    this.myDatePickerOptions = copy;
}
```

There isn't option **customPlaceholderTxt**. You can remove it. There is **placeholder** attribute. More info and example from here: https://github.com/kekeh/mydatepicker#placeholder-attribute

**Comment by nowned** [comment]
@kekeh What is in the `getCopyOfOptions`  function? I've tried without that, and just pre-loading something in both `enableDays` and `disableDateRanges`, then overwriting it, but no luck

**Comment by kekeh** [comment]
It returns copy of options:
```javascript
getCopyOfOptions(): IMyDpOptions {
    return JSON.parse(JSON.stringify(this.myDatePickerOptions));
}
```

**Comment by nowned** [comment]
@kekeh Still no luck I am sad to say. This is what our config is looking like, and we are updated to MyDatePicker version 2.0.26
```    private startDatePickerOptions : IMyDpOptions = {
      disableDateRanges: [{
        begin: {year: 2000, month: 1, day: 1},
        end: {year: 2030, month: 12, day: 31}
      }],
      dateFormat: 'yyyy-mmm-dd',
      minYear: 2000,
      maxYear: 2030,
      enableDays: [
        {year: 2000, month: 1, day: 1}
      ]
    };

    private endDatePickerOptions : IMyDpOptions  = {
      disableDateRanges: [{
        begin: {year: 2000, month: 1, day: 1},
        end: {year: 2030, month: 12, day: 31}
      }],
      dateFormat: 'yyyy-mmm-dd',
      minYear: 2000,
      maxYear: 2030,
      enableDays: [
        {year: 2000, month: 1, day: 1}
      ]
    };```

And then later down in a function we do
```
        let startDateCopy = JSON.parse(JSON.stringify(this.startDatePickerOptions));
        let endDateCopy = JSON.parse(JSON.stringify(this.endDatePickerOptions));
        startDateCopy.enableDays = availableDates;
        endDateCopy.enableDays = availableDates;
        startDateCopy.disableDateRanges = [{begin: {year: 2000, month: 1, day: 1}, end: {year: 2030, month: 12, day: 31}}];
        endDateCopy.disableDateRanges = [{begin: {year: 2000, month: 1, day: 1}, end: {year: 2030, month: 12, day: 31}}];
        this.startDatePickerOptions = startDateCopy;
        this.endDatePickerOptions = endDateCopy;
```

Functionality wise it looks identical. Any ideas?

**Comment by kekeh** [comment]
Try this:
```javascript
myDatePickerOptions: IMyDpOptions = {
    disableDateRanges: [
        {
            begin: {year: 2000, month: 1, day: 1}, 
            end: {year: 2030, month: 12, day: 31}
        }],
    minYear: 2000,
    maxYear: 2030,
    enableDays: [
        {year: 2017, month: 7, day: 21}, 
        {year: 2017, month: 7, day: 22}, 
        {year: 2017, month: 7, day: 22}
        ]
};
```
or this:
```javascript
myDatePickerOptions: IMyDpOptions = {
    disableDateRanges: [],
    minYear: 2000,
    maxYear: 2030,
    enableDays: []
};

onDisableEnable() {
    let copy = this.getCopyOfOptions();
    copy.disableDateRanges = [
        {
            begin: {year: 2000, month: 1, day: 1}, 
            end: {year: 2030, month: 12, day: 31}
        }];
    copy.enableDays =  [
        {year: 2017, month: 7, day: 21}, 
        {year: 2017, month: 7, day: 22}, 
        {year: 2017, month: 7, day: 22}
    ];
    this.myDatePickerOptions = copy;
}
```

Then you can be sure disable/enable is working and you probably have problems in your own code.

**Comment by nowned** [comment]
@kekeh The Disable/Enable is working, if you look in the original post it's working fine, it's just that on first open it shows everything as disabled. Once I toggle forward a month and then toggle back a month it properly updates and shows the enabled/disabled days. The same thing happens with your example for me

**Comment by Niashr** [comment]
Hi @nowned : did the above issue work for u or did u get a work around ? am facing simillar issue.

**Comment by nowned** [comment]
@Niashr No, it did not, we gave up and switched to a different library

**Comment by Niashr** [comment]
Can u plz tell me which library did u switch to ?

**Comment by nowned** [comment]
@Niashr Sorry, no longer working on that project, I don't remember

**Comment by Niashr** [comment]
Np .. appreciate ur help .. thanks again :)

**Comment by lachlanwp** [comment]
I'm experiencing the same issue.  I've disabled a date range and enabled particular days.  When I first open the date picker, all days are red.  If I then press ">" or "<" on the month, the enabled days show up.  If I think press "<" or ">" to go back to the original month, the enabled days now show.  This is the final requirement I need so it would be great if it works!

**Comment by lachlanwp** [comment]
I was also setting the `disableDateRanges` and `enableDays` dynamically.  But I just tested by the setting the options only once.  It does the same thing.

**Comment by kekeh** [comment]
You can use **onCalendarViewChanged()** method like here https://github.com/kekeh/mydatepicker/issues/598#issuecomment-511444047

You can also use a new version of the component if your Angular version is >=7.2

- Repository: https://github.com/kekeh/angular-mydatepicker

- Demo: https://kekeh.github.io/angular-mydatepicker/

**Comment by lachlanwp** [comment]
Thanks @kekeh 

I was able to find the real issue here.  I had been setting some of the `enabledDays` of type `IMyDate` using strings for year/month/day.  In some other places I had set them as `number`.

I went through and made sure all `IMyDate` instances were using `number` only in year/month/day such as:

```
    {
        year: number,
        month: number,
        day: number
    } as IMyDate
```

After I did this, everything started working as expected.  @Niashr can you try this?
