### ISSUE TITLE
IE11: Can't leave focus from mydatepicker element

### ISSUE THREAD

**Issue by hankhsutw** [kekeh/mydatepicker#382]
Hi,
   I tried the mydatepicker on http://kekeh.github.io/mydatepicker/ with IE and got a focus issue.
step:
1. click mydatepicker textbox to set focus
2. click selector size dropdown
3. mydatepicker keep focused and dropdown items can't be displayed

**Comment by sneharghya** [comment]
I faced the same issue. In my case problem seemed to appear with wrong use of the placeholder attribute. The following steps worked for me.
1. Declare a variable in the componenet =>
 `datepickerPlaceholder = 'mm/dd/yyyy'`
2. Used the above variable in the template 
`<my-date-picker [placeholder]="datepickerPlaceholder"></my-date-picker>`

**Comment by kekeh** [comment]
I fixed this bug in version **2.0.26**. Update to this version.

Now it works also here: http://kekeh.github.io/mydatepicker
