### ISSUE TITLE
Date Options Globally?

### ISSUE THREAD

**Issue by robinkedia** [kekeh/mydatepicker#384]
Hi - Can date option be configured in modules rather than at component level? Or can I specify dateformat and other options in html?

**Comment by kekeh** [comment]
I don't know it is possible to access to module from the component, but you can specify the options to HTML as follows:

```html
<my-date-picker [options]="{dateFormat: 'dd.mm.yyyy, minYear: 2010', maxYear: 2019}" 
                (dateChanged)="onDateChanged($event)"></my-date-picker>
```
