### ISSUE TITLE
Multiple date select?

### ISSUE THREAD

**Issue by lakhvir1994** [kekeh/mydatepicker#387]
I am working in angular2 application and I have requirement of multiple date selection and storing dates into  array. Is it possible with this rating, If yes then please guide me.

**Comment by kekeh** [comment]
You can select only one date at a time. But in the dateChanged callback you can store each selected date to array. Not optimal solution but could work.

Here is an example on how to implement the **dateChanged** callback: https://github.com/kekeh/mydatepicker/wiki/Calling-date-picker-function
