### ISSUE TITLE
Issue using onDateChanged event on Reactive Forms

### ISSUE THREAD

**Issue by animishas** [kekeh/mydatepicker#388]
Hi Everyone,

I am using reactive forms and when I call the event onDateChanged along with FormControlName attribute it doesn't work. The event doesn't work. Is there a way to use the methods listed here for Reactive Forms?Please check the below image. That is what I am talking about.

![issue](https://user-images.githubusercontent.com/25496038/28642656-603dea7a-7210-11e7-8505-c2218c396409.PNG)

Thanks for all your help

**Comment by kekeh** [comment]
You can use **dateChanged** callback with reactive forms. Callback is automatically called when a date is selected. 

What do you mean "The event doesn't work"? Callback works ok. I have tested it.

**Comment by animishas** [comment]
The problem I was having was when i was trying to edit the form I have. I was unable to view the datevalue in the date field. Here's what I have. 

component.ts
` getAgency(id: number): void {
        this.agencyService.getAgency(id)
            .subscribe(
            (agency: IAgencyProfile) => this.onAgencyRetrieved(agency),
            (error: any) => this.errorMessage = <any>error
            );
    }

    onAgencyRetrieved(agency: IAgencyProfile): void {
       
        if (this.agencyForm) {
            this.agencyForm.reset();
        }
        this.agency = agency;

        if (this.agency.AgencyId === 0) {
            this.pageTitle = 'Add Agency Profile';
        } else {
            this.pageTitle = `Edit Agency: ${this.agency.AgencyName}`;
        }

        var x = this.agency.RenewalDate;
        var splitdate = x.split("-");
        
        this.agencyForm.patchValue({
            AgencyProfileId: this.agency.AgencyProfileId,
            AgencyId: this.agency.AgencyId,
            AgencyName: this.agency.AgencyName,
            RenewalDate: {
                date: {
                    year: splitdate[0],
                    month: splitdate[2],
                    day: splitdate[1]
                }
            },

        })
    }`
![date](https://user-images.githubusercontent.com/25496038/28683580-51c81dc2-72be-11e7-998e-31a98884a466.PNG)

in the picture above you can see the other fields auto populate but not the date field. 
component.html
` <div class="col-md-4">
                        <label for="renewalDateId" id="renewalDateId" name="agencyProfile-label-renewalDateId">Renewal Date<span class="compulsary">*</span></label><br>
                        <my-date-picker id="renewalDateTextId" FormControlName="RenewalDate" [options]="myDatePickerOptions" (dateChanged)="onRenewalDateChanged($event)"></my-date-picker>
                    </div>`

Can you tell me where I am doing wrong?
Thanks In Advance

**Comment by kekeh** [comment]
Value of year, month and day must be number. Try this:
```javascript
this.agencyForm.patchValue({
    AgencyProfileId: this.agency.AgencyProfileId,
    AgencyId: this.agency.AgencyId,
    AgencyName: this.agency.AgencyName,
    RenewalDate: {
        date: {
            year: Number(splitdate[0]),
            month: Number(splitdate[2]),
            day: Number(splitdate[1])
        }
    },
})
```

**Comment by animishas** [comment]
It didn't work. Do you have any other suggestions?

**Comment by kekeh** [comment]
Is splitdate valid value? Test the following code to see it is working:
```javascript
this.agencyForm.patchValue({
    AgencyProfileId: this.agency.AgencyProfileId,
    AgencyId: this.agency.AgencyId,
    AgencyName: this.agency.AgencyName,
    RenewalDate: {
        date: {
            year: 2017,
            month: 8,
            day: 2
        }
    },
})
```
Instead of **patchValue** you can also try **setValue**.

**Comment by kekeh** [comment]
Here is working example using **patchValue**: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-access-modifier/sample-date-picker-access-modifier.ts
