### ISSUE TITLE
can I use it with Angular 2 non-beta?

### ISSUE THREAD

**Issue by armache** [kekeh/mydatepicker#39]
I tried to use the datepicker in Angular 2 project (non beta). Installation steps doesn't say anything about adding code in system.config.js file.  Please see the snippet below:

(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs':                       'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
      'mydatepicker': 'npm:mydatepicker'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      },
      'mydatepicker': {
          main: './index.js',
          defaultExtension: 'js'
      }
    }
  });
})(this);

After adding 'mydatepicker' relevant code in system.congig.js I am getting following error:
XHR error (404 Not Found) loading http://localhost:65422/node_modules/mydatepicker/src/my-date-picker/my-date-picker.component.css.js

**Comment by kekeh** [comment]
I think this is not currently possible, because there is not javascript bundle in the mydatepicker component. It contains only typescript code.

**Comment by Irrelevant** [comment]
I needed to complete 2 fixes in order to use with angular 2.0 (non beta) using system.js

**1 - Specify relative template urls, and specify a module.id parameter** (explained here: https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html)
- require wouldn't load the html and css if I had a default extension set, so I've replaced with angular templates instead.

from: 
const myDpStyles: string = require('./my-date-picker.component.css');
const myDpTpl: string = require('./my-date-picker.component.html');

@Component({
    selector: 'my-date-picker',
    styles: [myDpStyles],
    template: myDpTpl,
    ...

to this 
@Component({
            moduleId: module.id,
            selector: 'my-date-picker',
            styleUrls: ['my-date-picker.component.css'],
            templateUrl: 'my-date-picker.component.html',
            ...

2 - Created my-date-picker.module.js file as it seemed to be missing from the node package, (the typescript is their but not the js file)

**Comment by edimitchel** [comment]
Please, listen to @Irrelevant, he's right !

**Comment by kekeh** [comment]
I added better support to systemjs package loader. Install the latest version from npm and try again. 

// If you are using systemjs package loader import the MyDatePickerModule from here:
import { MyDatePickerModule } from 'mydatepicker/dist/my-date-picker.module';

// Set the following mydatepicker System.config properties:
(function (global) {
    System.config({
        paths: {
            'npm:': 'node_modules/'
        },
        map: {
            // Other components are here...

            'mydatepicker': 'npm:mydatepicker',
        },
        packages: {
            // Other components are here...

            mydatepicker: {
                main: './dist/index.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);

Let me know if this is not something you wanted.

**Comment by edimitchel** [comment]
It's alright ! version 0.0.32 solved my problem !

Thank's !
