### ISSUE TITLE
Retaining date in date picker 

### ISSUE THREAD

**Issue by RoopaJain** [kekeh/mydatepicker#392]
I am unable to display the selected date in the datemodel , as i am navigating back from next page.
Ex: I am in home page where i have used datepicker, here I will choose a date,  upon this page will navigate to another page by calling service. Now I need to display my selected date when I naviagte back to home page.
I have tried assigning to the date models, but it fails to display in the input text box field.

ThankYou

**Comment by kekeh** [comment]
If you are using ngModel binding you can try to initialize one of the following ways:
```javascript
 // initialize today with jsdate property
private model: any = {jsdate: new Date()};  
// initialize today with date property
private model: any = {date: {year: 2017, month: 7, day: 27}};  
// initialize today with formatted property, notice date format option
private model: any = {formatted: '27.07.2017'};  
```
If you are using reactive forms you can intialilize one of the following ways:
```javascript
setDate(): void {
    let date: Date = new Date();
    this.myForm.patchValue({myDate: {
        date: {
            year: date.getFullYear(), 
            month: date.getMonth() + 1, 
            day: date.getDate()}
        }});
}

setDate(): void {
    this.myForm.patchValue({myDate: {jsdate: new Date()}});
}

setDate(): void {
    this.myForm.patchValue({myDate: {formatted: '27.07.2017'}});
}
```

**Comment by kekeh** [comment]
If above does not help try to wrap it in set timeout. For example:
```javascript
setTimeout(() => {
    this.model = {date: {year: 2017, month: 7, day: 27}}; 
});
```

**Comment by RoopaJain** [comment]
Thank You
👍 
 @kekeh 

Used this type and it worked 
// initialize today with date property
private model: any = {date: {year: 2017, month: 7, day: 27}};
