### ISSUE TITLE
Blockout dates

### ISSUE THREAD

**Issue by kindrajeet** [kekeh/mydatepicker#393]
private myDatePickerOptions = { todayBtnTxt: 'Today',  dateFormat: 'yyyy-mm-dd', firstDayOfWeek: 'mo',
        sunHighlight: true, markCurrentDay: true, height: '34px', width: '260px',  inline: false,disableSince:  {year: 2010, month: 7, day: 22},  disableUntil: {year: 2020, month: 7, day: 1},  minYear : 2017,      maxYear : 2019,  enableDays: [{year: 2017, month: 8, day: 28}, {year: 2017, month: 8, day: 31},{year: 2017, month: 8, day: 21}],  disableTodayBtn: true };

I want to enable only Month of july 28, 31 and Aug 21 rest of others date should not disabled 
and also start date should be auto selected for example 28 July because in this array only first item is 28 uly

**Comment by kekeh** [comment]
You can try the following options to disable all but enable only dates added to enableDays option:
```javascript
myDatePickerOptions = { 
    dateFormat: 'yyyy-mm-dd', 
    firstDayOfWeek: 'mo',
    sunHighlight: true, 
    markCurrentDay: true, 
    height: '34px', 
    width: '260px', 
    inline: false,
    minYear : 2017, 
    maxYear : 2019, 
    disableDateRanges: [{begin: {year: 2017, month: 1, day: 1}, end: {year: 2019, month: 12, day: 31}}]
    enableDays: [{year: 2017, month: 8, day: 28}, {year: 2017, month: 8, day: 31},{year: 2017, month: 8, day: 21}]
};
```
Here is an example how to se intial date with ngModel: https://github.com/kekeh/mydatepicker/wiki/Use-ngModel

**Comment by kindrajeet** [comment]
How to make read only or disable input area of datepikcer, On Button click we are opening picker can we do same thin on text area if disabled or readonly ?

Can we add little more styling like selected in circle and enable dates in Green background ?

**Comment by kekeh** [comment]
Set **editableDateField** option to **false** and **openSelectorOnInputClick** option to **true**.

Styling of the component may be difficult. Here is something: https://github.com/kekeh/mydatepicker/issues/118

You can also implement own version with own styles. You can start here: https://github.com/kekeh/mydatepicker#development-of-this-component
