### ISSUE TITLE
how to fire inputFieldChanged event in case of last character removed(When We are putting the invalid date by keyboard.)

### ISSUE THREAD

**Issue by nimishgoel56** [kekeh/mydatepicker#395]
I am using this inputFieldChanged event. It gets called when input(selected by datepicker ) is changed.
inputFieldChanged event do not get fired when I put some invalid date by keyboard in the text box and now remove all the text one by one using backbutton and when last character is removed from textbox it should fire the inputFieldChanged event, but no event gets fired. You can check in the screenshot also, When I removed last character also 0, this event was supposed to fire and we should get the blank value in the console. Any possiblity to find how to fire that event(or any other event) in case of last character removed(When We are putting the invalid date by keyboard.)

[https://user-images.githubusercontent.com/30027827/29168515-d5032914-7dec-11e7-8f25-75cea1f08ddd.png](https://user-images.githubusercontent.com/30027827/29168515-d5032914-7dec-11e7-8f25-75cea1f08ddd.png)

**Comment by kekeh** [comment]
I fixed this in version 2.0.27.

**Comment by nimishgoel56** [comment]
How can I get the latest version in my angular project
