### ISSUE TITLE
1/06/2017 is invalid date?

### ISSUE THREAD

**Issue by nimishgoel56** [kekeh/mydatepicker#397]
When I am putting "1/06/2017" date from keyboard then  is showing it as invalid date? 01/06/2017 is valid date ? why so ?
![screenshot 12](https://user-images.githubusercontent.com/30027827/29202217-8c4cdd0e-7e83-11e7-8682-35b2aad08633.png)

**Comment by politoxela** [comment]
I think it is a problem with the format, you entered 1/06/2017 but the correct thing is 06/01/2017, according to what I have tried.

**Comment by chriscode824** [comment]
Would it be possible to have a one digit day and month options?

    public myDatePickerOptions: IMyDpOptions = {
        dateFormat: 'm/d/yyyy',
    };

and get the formatted date something like: 2/3/2017
?

**Comment by ckvnahsik** [comment]
I think you have to get double digit fro date first and then set it with your ([ngModel])

**Comment by kekeh** [comment]
I added support to short formats. You can now for example set **dateFormat** option to **'m/d/yyyy'**.

Examples: d.m.yyyy, dd.mm.yyyy, yyyy-m-d, yyyy-mm-dd, d mmm yyyy, dd mmm yyyy **(d = Day not leading zero, dd = Day with leading zero, m = Month not leading zero, mm = Month with leading zero, mmm = Month as a text, yyyy = Year four digit)**

This change is in version 2.3.0

**Comment by chriscode824** [comment]
Thank You.
