### ISSUE TITLE
can i use epoc to set date?

### ISSUE THREAD

**Issue by arisbro8** [kekeh/mydatepicker#398]
can i change a 
`private model: Object = { date: { year: 2018, month: 10, day: 9 } };`
to epoc format?

**Comment by kekeh** [comment]
You can use the following properties to set initial date:
```javascript
private model: any = {jsdate: new Date()}; 
private model: any = {date: {year: 2018, month: 10, day: 9}}; 
private model: any = {formatted: '24.09.2018'};
```

with epoc it is not possible.

**Comment by kekeh** [comment]
You can create javascript date object from the epoc timestamp and use **jsdate** property as follows:
```javascript
let date: Date = new Date(YOUR_EPOC_TIMESTAMP * 1000);

private model: any = {jsdate: date}; 

```

**Comment by arisbro8** [comment]
I can't use **jsdate**. It's not work
