### ISSUE TITLE
How to use form validation to check required field?

### ISSUE THREAD

**Issue by jusfeel** [kekeh/mydatepicker#399]
I have tried to bind a template variable for validation (template based form) like this, but the template shows error when render.

```
<my-date-picker id="eventDataStartDate" name="eventDataStartDate" [options]="myDatePickerOptions" [selDate]="selStartDate" 
                (dateChanged)="eventData.event.start_date=$event.formatted" required #startDateField="ngModel"></my-date-picker>
```

**Comment by kekeh** [comment]
Check this example: https://github.com/kekeh/mydatepicker#1-ngmodel-binding

it initializes to specific date but it is optional. You can set value of the model as follows if you don't want to set initial date:
```javascript
private model: any= null;
```
