### ISSUE TITLE
How to validate Input date is valid or not  using onInputFieldChanged   event

### ISSUE THREAD

**Issue by NmaheshR** [kekeh/mydatepicker#403]
when i am having both the following call back it if throwing exception
onDateChanged,
onInputFieldChanged  

**Error :RangeError: Maximum call stack size exceeded**

**Comment by kekeh** [comment]
It is possible use both callbacks at the same time. Check example how to use them from here: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal
