### ISSUE TITLE
Karma Testing issue - Uncaught TypeError: Cannot read property 'core' of undefined

### ISSUE THREAD

**Issue by BagelTheKid** [kekeh/mydatepicker#404]
Hi, I'm trying to test a component that is using the date-picker component through Karma+Jasmine. Honestly, I'm not too sure if this is an issue with Karma or an issue with MyDatePicker. Either way, when I run karma, both the Chrome and PhantomJS instances are throwing the following:

Chrome
> Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
>  Uncaught TypeError: Cannot read property 'core' of undefined
>  at node_modules/mydatepicker/bundles/mydatepicker.umd.js:4

PhantomJS
> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
>  TypeError: undefined is not an object (evaluating 'global.ng.core')
>  at node_modules/mydatepicker/bundles/mydatepicker.umd.js:4

All the Jasmine test is doing is seeing if the component is defined.

Let me know if I need to move this to Karma or not. Thanks for any assistance.

**Comment by kekeh** [comment]
I think you don't need to test mydatepicker if you try to test your own component. I have already run mydatepicker karma test.

Maybe you have to exclude **node_modules** folder from your karma test and test only your own component code.
