### ISSUE TITLE
Provides style customization points

### ISSUE THREAD

**Issue by yuanfeiz** [kekeh/mydatepicker#41]
Is there any way to customize the appearance of the widget? 

It seems currently the only way is to use `!important` to overwrite the predefined styles which doesn't look like a good way to go. Furthermore, when the ViewEncapsulation is set to use the real shadow DOM, this workaround would become invalid.

Thanks!

**Comment by kekeh** [comment]
If you don't want to use the !important I think the only way is to modify the **node_modules/mydatepicker/src/my-date-picker/my-date-picker.component.css** file and build the project after modification.

But if you are using webpack build is not problem.

**Comment by kekeh** [comment]
I set teh followin encapsulation value:
@Component({
    ....
    encapsulation: ViewEncapsulation.None
})

Now you can override styles of component from the parent for example:
    <style>
        .mydp .selection  {
            background-color: yellow;
        }
    </style>
which set selection background to yellow.

**Comment by yuanfeiz** [comment]
Great, this would be really helpful. Thank you!
