### ISSUE TITLE
Change date picker options 

### ISSUE THREAD

**Issue by Gafilipoie** [kekeh/mydatepicker#411]
Hi,

On init, I set the myDatePickerOptions = { disableSince: {year: 2017, month: 8, day: 20} }

How do I change the options of date picker after init, for example, upon clicking a date (01.09.2017) update  myDatePickerOptions.disableSince = {year: 2017, month: 9, day: 1}. Also I tried this and didn't work.

**Comment by kekeh** [comment]
You have to create copy of options and then change value of option. This is needed in order the date picker detect change of option. Here is an example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option
