### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by Senthe** [kekeh/mydatepicker#416]
This error fires on line 558 in /mydatepicker/dist/my-date-picker.component.js:

```
  MyDatePicker.prototype.setFocusToInputBox = function () {
        var _this = this;
        if (!this.opts.inline) {
            setTimeout(function () {
                _this.inputBoxEl.nativeElement.focus(); // inputBoxEl is undefined
            }, 10);
        }
    };
```

I suppose sometimes this timeout isn't enough. Can it be changed to something more reliable, like some afterRender hook or something?

**Comment by kekeh** [comment]
Hi @Senthe 

I increased timeout value to 100 milliseconds. This change is in version **2.0.30**.

**Comment by DavidMaza** [comment]
I'm also getting this issue, but only when showInputField is false.

**Comment by kekeh** [comment]
Now it doesn't try to set focus to the input field if the **showInputField** is **false**.

This is in version 2.0.31.

**Comment by Senthe** [comment]
@kekeh That's great news, thank you. : )
