### ISSUE TITLE
Date format is changing in windows system?

### ISSUE THREAD

**Issue by bhavyamanu** [kekeh/mydatepicker#418]
Hi,
   I am using mydatepicker and given the date format as dd/mm/yy in the code but on submit the date format is changing to mm/dd/yy in windows system(google chrome). is there any solution for that?

**Comment by kekeh** [comment]
Mydapicker supports only full year format. For example: "dd/mm/yyyy"

**Comment by bhavyamanu** [comment]
@kekeh I am using full year format only kekeh but when i run my code on windows system date format is changing what is the solution for that?? 
In linux the format is working fine but in windows it is not.
in linux format is dd/mm/yyyy
but in windows it is showing mm/dd/yyyy

please help and alteast tell me what to change.

**Comment by kekeh** [comment]
Interesting. Options should not to do anything with OS or date format of OS.

**Comment by bhavyamanu** [comment]
@kekeh But the date format is changing. so plz give the solution.
