### ISSUE TITLE
Once submit button is clicked date is displayed correctly , 2nd time submit, date is null

### ISSUE THREAD

**Issue by ketanbgm** [kekeh/mydatepicker#423]
Once submit button is clicked date is displayed correctly , without changing the date if submit button is clicker date is null.

                        <my-date-picker class="form-control"  name="visit_date" formControlName="visit_date" [options]="myDatePickerOptions" placeholder="MM/DD/YYYY"></my-date-picker>

    this.req['visit_date'] =  this.form.value.visit_date.formatted;

**Comment by kekeh** [comment]
Is this error valid any more?

**Comment by kekeh** [comment]
Closed because no answer.
