### ISSUE TITLE
Setting default date is too complex

### ISSUE THREAD

**Issue by pptyasar** [kekeh/mydatepicker#424]
When making default date value need to initialize with separate object date and formatted.

`this.created_date = {date:this.created_date,formatted:this.created_date};`

After submitting form need to change exact value as 
`this.created_date = formatted:this.created_date;`

This is too complex when I have more date input box in form.

And after submitting the form I want to re-initialize again like 

`this.created_date = {date:this.created_date,formatted:this.created_date};`

So tired.

**Comment by kekeh** [comment]
Only one property of **date**, **formatted** or **jsdate** is needed when you are setting default date. You can do for example:
```javascript
this.created_date = {date: {year: 2017, month: 9, day: 23}};
```
or
```javascript
this.created_date = {formatted: '23.09.2017'};
```
or
```javascript
this.created_date = {jsdate: new Date()};
```
