### ISSUE TITLE
onDateChanged not working for  datepickers in every grid row

### ISSUE THREAD

**Issue by vandanachadha** [kekeh/mydatepicker#425]
There is a grid and every row has to have a datepicker. The display of pickers is ok when the icon is clicked, however the onDateChanged callback event is not called. 

Following is the inclusion in the form inside the foreach:
<my-date-picker name="agreementExpiryDate" [options]="myDatePickerOptions" 					(dateChanged)="onDateChanged($event)" >
</my-date-picker>

Do I need to add unique ids in this directive?

**Comment by kekeh** [comment]
You can do as follows if you have date pickers inside the **ngFor**:
```html
<div *ngFor="let x of rows; let i = index">
    <my-date-picker [options]="myOptions"  (dateChanged)="onDateChanged($event, i)">
        </my-date-picker>
</div>
```

```javascript
onDateChanged(event: IMyDateModel, idx: number) {
    // idx indicates which date picker date is selected
}
```

above code worked ok. The **dateChanged** callback is called every time when the date is selected.

The **name** attribute in the **my-date-picker** tag is needed only if you are using **ngModel** or **formControlName**.

**Comment by vandanachadha** [comment]
Thank you so much for your prompt reply. I should have mentioned that the problem in calling the datechanged function is faced when I also have the [sel] option since I need the earlier value to be preselected. If I remove the [sel] option, the dateChanges is called correctly.

<my-date-picker name="taskDateField" [(ngModel)]="taskDateField" [options]="myDatePickerOptions" [selDate]="taskDateField"	
						(dateChanged)="onDateChanged($event,ind)" >
</my-date-picker>

**Comment by kekeh** [comment]
You can set initial date using ngModel. here is an example: https://github.com/kekeh/mydatepicker#1-ngmodel-binding
