### ISSUE TITLE
Validation on selection of past date it will throught hilights and error popup message 

### ISSUE THREAD

**Issue by pratiksha-chandel** [kekeh/mydatepicker#429]
Hello there,
    I want to apply validation on on each date picker value.
if I select past date or wrong date format ,it will call error class.and display error popup message over there .
help please .

          <span class="content-title">My Date</span>
          <p *ngIf="!isEditable" class="no-margin padding-5"> {{orderCustomProperties.changeOrCancelDate | date:'MM/dd/yyyy' || '-'}}</p>
          <my-date-picker *ngIf="!!isEditable" #changeOrCancelDate formControlName="changeOrCancelDate" [options]="myDatePickerOptions"  [defaultMonth]="defaultMonth"
                          [placeholder]="utilService.placeholder" [ngModel]="orderCustomProperties.changeOrCancelDate | stringToDate"
                          (ngModelChange)="orderCustomProperties.changeOrCancelDate = utilService.convertDateToString($event)" required ></my-date-picker>
          <hr class="no-margin-top margin-bottom-5">

**Comment by kekeh** [comment]
You can disable past dates If you want. Then they are not selectable. Check option disableUntil from dokumentaation. 

You can implemt inputFieldChanged callback. Then you know is user typen date valid or not. Here is dokumentaation of inputFieldChanged callback: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

**Comment by pratiksha-chandel** [comment]
Thank you .I will check that .

**Comment by pratiksha-chandel** [comment]
Hello ,

Can you please add custom class for input feild  for required option ,
I want " required " option i have tried but not sccess .
 [ngClass]="{'input-box-red': !mandatoryDateFormat || isInvalidDateFormat}"

**Comment by kekeh** [comment]
There is already class for that: **invaliddate**

You have to set option **indicateInvalidDate** to **true**. This class set background color to red if date is invalid.

**Comment by pratiksha-chandel** [comment]
Thank you very much . 
I have one more question ,I want to add tooltip along with red color ,so user can more clear about the change .
I have tried this ,work for me but not able to add tooltip on datepicker .
:host >>> my-date-picker >>> .mydp .invaliddate {
  border: 1px solid red !important;
  .tooltip{

   }
}

Another way : 
 <my-date-picker>
 </my-date-picker> // Added new span and try to check 
  <span *ngIf="!indicateInvalidDate"><a href="#" data-tooltip="I’m the tooltip text."></a></span>
 do you have better option to allow tooltip on datepicker . 
Please help.

**Comment by praveenbn** [comment]
You can write a custom css like which will have a look and fell like toolip

td.daycell.disabled:hover:after {
 content : 'Date disabled due to...';
 position : absolute;
 color: black;
 backgroung: lightgray;
 border-radius : 3px;
 padding : 3px;
 cursor : help;
}
