### ISSUE TITLE
How to set date picker value to a default value. 

### ISSUE THREAD

**Issue by Atul4593** [kekeh/mydatepicker#438]
When i enter a date from input, if it is past date i want it to reset to previous value. After validation i am setting date value if its past date. But on view its still the same date.

<my-date-picker name="expiryDate" [(ngModel)]="expiryDate" [options]="dtoptions" (dateChanged)="onExpiryDateChanged($event)" [disabled]="dateFlag"></my-date-picker>

onExpiryDateChanged(event) {
    if (Utils.compare_dates(Utils.getTodayDate(), event.formatted)) {
        expiryDate = expiryCopyDate);       
      }

If user enter input as past date then  expiryDate  should assign to expiryCopyDate but it hold same value which user enter. 
Eg: expiryDate = 12/10/2017
expiryCopyDate holds default value 
if user enter past date suppose 11/10/2017 
  then expiryDate  should get set to expiryCopyDate but it is still the value user enter.

**Comment by kekeh** [comment]
You can prevent user to select or type past dates by using option **disableUntil**. Here is an example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

If you want to set initial date you can do it as follows in case of ngModel:
```html
<my-date-picker name="expiryDate" [(ngModel)]="expiryDate" [options]="dtoptions" 
    (dateChanged)="onExpiryDateChanged($event)" [disabled]="dateFlag">
```

```javascript
// using IMyDate
expiryDate = {date: {year: 2017, month: 10, day: 15}};

// using javascript date
expiryDate = {jsdate: new Date()};

// using string
expiryDate = {formatted: '15.10.2017'};
```
