### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by fahadhaq** [kekeh/mydatepicker#443]
Hi, i am new to angular 2 and trying to get this code working. I have a form that generates max 4 date field, depending on the user input from previous screen. I have the validation for required working with this control but I cant seem to get the min and max age restriction working. The page shows error for all the controls rather then the one that is failing. Here is my code

```
const control = <FormArray>this.myGroup.controls['userdetails'];
        for (var i = 0; i < control.value.length; i++) {
            //Date validation
            if (this.skuItemGlobal)
            {
                var skuItemRace = this.skuItemGlobal[i].skuItemRaces[0];

                this.minAge = skuItemRace.minimumAge == null ? 0 : +skuItemRace.minimumAge;
                this.maxAge = skuItemRace.maximumAge == null ? 0 : +skuItemRace.maximumAge;
                console.log("minAge ", this.minAge);
                console.log("maxAge", this.maxAge);

                var formValues = JSON.stringify(control.value[i]);
                console.log(formValues);
                var participant = new ParticipantDto();
                let jsonData = JSON.parse(formValues);
                if (this.minAge > 0 && this.maxAge > 0) //isrequired toc check if the minimumAge is set 
                {
                    if (!moment(new Date(jsonData.myDate.jsdate).toLocaleDateString()).isBetween(moment().add(this.maxAge, 'y').format("YYYY-MM-DD"), moment().add(this.minAge, 'y').format("YYYY-MM-DD"))) {
                        this.isDateNotBefore = true;

                        isDateValid = false;
                    }
                }
                else if (this.minAge > 0) {
                    if (!moment(new Date(jsonData.myDate.jsdate).toLocaleDateString()).isBefore(moment().add(this.minAge, 'y').format("YYYY-MM-DD"))) {
                        this.isDateNotBefore = true;
                        isDateValid = false;
                    }
                }
            }
        }
```

How do i only show error for the control that is not valid? The above code is called when the form is submitted. Thanks in advance

**Comment by kekeh** [comment]
You can set options **disableUntil** and **disableSince**. It prevents user to select or type 'wrong' date. Then you can implement **inputFieldChanged** callback. Documentation of the **inputFieldChanged** callback: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

Example: https://github.com/kekeh/mydatepicker/wiki/inputFieldChanged-callback

The **inputFieldChanged** callback indicates is date valid or not.

You can test it here: http://kekeh.github.io/mydatepicker

open console of the browser to see the **inputFieldChanged** messages.

**Comment by fahadhaq** [comment]
Sorry but not sure if that would solve my problem given each date field would have different validation. for example date field one would be for a user who is 20 years or older, date field 2 would be for user who is 18 or younger and so on. this is going to be used to validate the users age as different event would have different age restrictions.

**Comment by kekeh** [comment]
You can set own options and callbacks to each date picker.
