### ISSUE TITLE
How to make date picker accept both formats: m/d/yyyy and mm/dd/yyyy

### ISSUE THREAD

**Issue by EinsamerHirte** [kekeh/mydatepicker#444]
When we pick the date from the panel, it's OK to display it as: 01/02/1990
But when we take the input from keyboard, the users want to accept the format like 1/2/1990
Do we have some configuration to accept both formats above?

Thank you.

**Comment by kekeh** [comment]
Short format is not an option. You have to type always long format.

**Comment by kekeh** [comment]
I added support to short formats. You can now for example set **dateFormat** option to **'m/d/yyyy'**.

Examples: d.m.yyyy, dd.mm.yyyy, yyyy-m-d, yyyy-mm-dd, d mmm yyyy, dd mmm yyyy **(d = Day not leading zero, dd = Day with leading zero, m = Month not leading zero, mm = Month with leading zero, mmm = Month as a text, yyyy = Year four digit)**

This change is in version 2.3.0

**Comment by EinsamerHirte** [comment]
I'm appreciated your support.
If I understand it right, currently, we accept either full format (mm) or short format(m), not both. But I think the user wants to type in short format and display in full format. For e.g.: I input 7/8/2017 and after I press enter, the format in the input field is 07/08/2017.
It's just a suggestion, and you may do it before I make this comment.
Once again, thank you for your support.
