### ISSUE TITLE
To determine whether the entered date is invalid

### ISSUE THREAD

**Issue by sukhminderx** [kekeh/mydatepicker#445]
Hi
The invalid date is indicated by the red background, but if we want to know in the component, such as set up a Boolean flag for it, how can that be done? Is there an event callback?
Thanks.

**Comment by guneetsinghbhatia** [comment]
We can use following event

onInputFieldChanged(event: IMyInputFieldChanged) {
  console.log('onInputFieldChanged(): Value: ', event.value, ' - dateFormat: ', event.dateFormat, ' - valid: ', event.valid);
}

**Comment by kekeh** [comment]
Here is documentation: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback
