### ISSUE TITLE
make start date depenedent on another calendar on same page

### ISSUE THREAD

**Issue by 02harleen** [kekeh/mydatepicker#449]
Hi,
I have two calendars on a page where the first calendar is used as start date and the second one for the end date. when I select a date in the first calendar the dates before selected one should be disabled in the second calendar.
Ex: if I choose 10 Nov in the first calendar then the minimum date in the second calendar should be 11 nov 

How can I do it?

**Comment by kekeh** [comment]
It is possible. here is an example: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options
