### ISSUE TITLE
Date format like 2017/11/03 FRI

### ISSUE THREAD

**Issue by soetani** [kekeh/mydatepicker#451]
Is there any way to format date `yyyy/mm/dd EEE` ?
e.g. 2017/11/03 FRI

I've tried to update `event.formatted` on `onDateChanged(event: IMyDateModel)`, but failed to change text in a text form.

Thank you

**Comment by kekeh** [comment]
This is not supported format. Supported format contain only day, month and year. You can try to update ngModel inside onDateChanged function but I am not sure is it working or not.

**Comment by soetani** [comment]
Thank you!
