### ISSUE TITLE
[(ngModel)]="date" does not fire change event when date is changed

### ISSUE THREAD

**Issue by windmaomao** [kekeh/mydatepicker#452]
if I setup inline mode and wrote the following line 

```
    <my-date-picker name="myDate" 
         [options]="opts" [(ngModel)]="date" (dateChanged)="onDateChanged($event)"
    ></my-date-picker>
```

if I change the date manually,

```
  today() {
    const d = new Date();
    this.date = { date: {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    }};
  }
```

the `onDateChange` is not fired. Please help.

**Comment by kekeh** [comment]
dateChanged is not fired If you change ngModel like above. It is fired only when you select a date  from the calendar or type a valid date to the input box.

**Comment by windmaomao** [comment]
Thank you, but how do I manually set a day at runtime?

**Comment by kekeh** [comment]
You can set It like above but It does not fire onDateChange function, but If you set date manually you can call onDateChange function from your own code.
