### ISSUE TITLE
How to manually set a date at inline mode ?

### ISSUE THREAD

**Issue by windmaomao** [kekeh/mydatepicker#453]
Thank you for your previous answer. 

But I need to figure out a way to set the date manually. I thought you can do with the following code if I bind the date with `[(ngModel)]="date"`

```
  today() {
    const d = new Date();
    this.date = { date: {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    }};
  }
```

but unfortunately, no event is fired? Please advise which event handle I should use to perform manual date assignment.

**Comment by windmaomao** [comment]
I also tried to split `ngModel` into two pieces so that I can grab the standard `ngModelChange`, but I still can't get any event. 

```
        <my-date-picker name="myDate" 
         [options]="opts" [ngModel]="date" (ngModelChange)="onChange($event)" (dateChanged)="onDateChanged($event)"
        ></my-date-picker>

```

Am I missing something here? thank you for your time.

**Comment by windmaomao** [comment]
If i select any date on the UI, both `onChange` and `onDateChanged` is fired. But if I call `today()`, none of the event is fired. 

```
  // set today
  today() {
    console.log('today');
    const d = new Date();
    this.date = { date: {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    }};
  }

  // on date change
  onChange(event) {
    console.log('event');
  }

  // on my date changed
  onDateChanged(event: IMyDateModel) {
    console.log('my-event');
    this.title = event.formatted;
  }

```

Please let me know if this is actually what's going on right now ? or if this is a bug. Either way, could you please advise a way to allow me to assign date programmatically?

**Comment by kekeh** [comment]
Hi @windmaomao 

When I click **Set today** button the **onChange()** and the **onDateChanged()** functions are called. I tested this code. See below.
```html
<my-date-picker name="ngModelDate" [options]="myDatePickerOptions" [(ngModel)]="model" 
    (ngModelChange)="onChange($event)" (dateChanged)="onDateChanged($event)">
    </my-date-picker>
<div>
    <button class="button" type="button" (click)="today()">Set today</button>
</div>
```

```javascript
private model: any = null;

today() {
    console.log('today');
    const d = new Date();
    this.model = { date: {
        year: d.getFullYear(),
        month: d.getMonth() + 1,
        day: d.getDate()
    }};
}

onChange(event: any): void {
    console.log('onChange(): ', event);
}

onDateChanged(event: any): void {
    console.log('onDateChanged(): ', event)
}
```

![screenshot_2017-11-04_15-48-57](https://user-images.githubusercontent.com/11028839/32405947-b0de288a-c177-11e7-8aac-b64948f888d0.png)

I tested this with the sampleapp included into this repository.

**Comment by kekeh** [comment]
Question was inline mode and I tested in normal mode. I think there is bug in inline mode. I will fix that.

**Comment by kekeh** [comment]
Yes it was inline mode issue. I made a fix. You can now try version 2.2.0.
