### ISSUE TITLE
datepicker disabling when any dates in the display are disabled

### ISSUE THREAD

**Issue by andycwk** [kekeh/mydatepicker#454]
Hi!

Struggling with this one and wondering if you have any diagnostics pointers!

I added two date pickers and configured them so selecting dates in either creates a date range - so far so good!

However If I select a date in the first - say 5th October and then select the 3rd November in the second picker the first pickers display disables (no hover effects or anything) as soon as I pick a date not displayed in the first box... say the 10th November (in the second picker) then the first picker enables again - at least until I move into November!

I tried to replicate using http://plnkr.co/edit/DhYXZhCUFLPhsfVNPI9u?p=info but alas it works as expected :(

**Comment by kekeh** [comment]
You plunker demo is working ok. At first select Today button from both of the calendars and then select dates from both calendars. You see that disabling works ok.

**Comment by kekeh** [comment]
You can also use defaultMonth attribute to select right month from the calendar: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

**Comment by andycwk** [comment]
Hi thanks for the quick response!

Sorry if I've caused confusion... as mentioned in the last sentence for my plea of help, the plunker demo is working correctly, I merely included it to demonstrate that I can get it working!

I've not been able to replicate the issue reported using Plunker and was looking for some next steps to follow in diagnosing my issue...

As the author of the component, I was hoping that from my description of the issue, you would be able to say - ha ha... you need to take a look in this area!

**Comment by andycwk** [comment]
Hey guys...

So it turns out there was nothing wrong with how I was implementing the datepicker!

Way back (over a year ago) I created a global class rule (I know) `.disabled` in  my css code that drops a near invisible div over a content region - the aim -> to disable the content behind it in one nasty swoop.

Looks like my rule was seeing the `disabled` class rule on the day cell and doing it's thing :(

**Comment by kekeh** [comment]
In the beginning of time I added **encapsulation: ViewEncapsulation.None** property to component of datepicker because I wanted that it should be as easy as possible to override styles of component from the host component. That is why the datepicker now detect your disabled rule and do thing based on that rule.

**Comment by andycwk** [comment]
No problem... I've told my rule off and it's working like a dream now!

Really loving the picker.. excellent work thanks for sharing with the world :)
