### ISSUE TITLE
Placeholder font-family problem

### ISSUE THREAD

**Issue by Leyli698** [kekeh/mydatepicker#455]
I cannot change font-family of placeholder in datepicker. Do you have any solutions for this?

**Comment by kekeh** [comment]
It may be difficult to change it, but can you consider to use **ngx-mydatepicker**: https://github.com/kekeh/ngx-mydatepicker

Demo: https://kekeh.github.io/ngx-mydatepicker/

It is like **mydatepicker**, but you have full control to input box and you can easily set styles to it.
