### ISSUE TITLE
Configure Datepicker return value

### ISSUE THREAD

**Issue by Manish2005** [kekeh/mydatepicker#457]
By default the datepicker returns and object of type
 {
    date: IMyDate;
    jsdate: Date;
    formatted: string;
    epoc: number; 
}

Is there a way to configure it to return something like 
{
   day: 11, 
   month:11,
   year:2017
}

The reason I am asking for it is the current output contains redundant data formatted in 4 different ways. I am only interested in one of these values.

**Comment by kekeh** [comment]
This is not configurable. It is always [IMyDateModel](https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date-model.interface.ts)
