### ISSUE TITLE
I cannot change the year in the datepicker 

### ISSUE THREAD

**Issue by luisbirchenz** [kekeh/mydatepicker#458]
I have a new feature where I need to open a form where I use the date picker, but I need to load data for the next year. So, for example, I'm trying to set 2018 as minYear which works fine but when I open the selector it shows the current year. Is there a way to force the date picker to show the minYear defined? Because there is no way to select a date before to that year, at least that is the idea. Based on the example I mentioned before, can I open the date picker in 2018? How can I do that? I want the user to be able to open the datepicker in the following year, and I'm talking about date picker without any initial value.

I look forward to receiving your comments.

Thanks in advance,

Luis.

**Comment by kekeh** [comment]
You can use **defaultMonth** attribute. With it you can define default **month** and **year** when you open calendar.

README: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

**Comment by luisbirchenz** [comment]
Sorry for the delay in my answer. I finally did that. 

Thanks.
