### ISSUE TITLE
Error When Clone/fork this library

### ISSUE THREAD

**Issue by ChenReuven** [kekeh/mydatepicker#46]
Hey, 
After i clone/fork, run npm install, npm start.
i get this issue:
info: 
ERROR in C:\Users\reuvec\Desktop\MM\mydatepicker\node_modules\@types\node\index.
d.ts
(283,40): error TS1110: Type expected.

ERROR in C:\Users\reuvec\Desktop\MM\mydatepicker\node_modules\@types\node\index.
d.ts
(283,21): error TS2371: A parameter initializer is only allowed in a function or
 constructor implementation.

what can be the issue?
i have node v5.1.1
tsc version 2.0.3

Thanks

**Comment by kekeh** [comment]
Try to update typescript:

**Comment by ChenReuven** [comment]
Thanks

**Comment by kekeh** [comment]
typescript package updated to package.json file of mydatepicker.
