### ISSUE TITLE
Date picker popup on focus in input

### ISSUE THREAD

**Issue by ramadurgarao** [kekeh/mydatepicker#460]
Date picker popup is not getting opened when user clicks on text box . Popup is getting opened when user clicks on calendar icon only.

**Comment by kekeh** [comment]
It is configurable. Set **openSelectorOnInputClick** option to **true** and **editableDateField** option to **false**.

You can test it here: http://kekeh.github.io/mydatepicker/

uncheck **Editable date field** check box.
