### ISSUE TITLE
Datepicker z-index problem

### ISSUE THREAD

**Issue by danielfnz** [kekeh/mydatepicker#461]
Hello, I'm having a problem with the calendar, it's getting underneath all the elements on my page, I think it's z-index. How to correct this error?

![zindex](https://user-images.githubusercontent.com/6144301/32550772-830466e4-c475-11e7-812c-eb64711b2423.png)

**Comment by kekeh** [comment]
Calendar **z-index** is **100**. It can be also **overflow: hidden** property which hides the calendar.

You have to right click the element which hides the calendar and select inspect element in the browser. Then uncheck styles one by one to see which causes the issue.

You can easily change styles of your own application than external component.
