### ISSUE TITLE
On form rerender the datepicker is not back to pristine

### ISSUE THREAD

**Issue by dev-mfm** [kekeh/mydatepicker#462]
I'm using template driven and when I rerender the form the datepicker is still dirty not like the other inputs.
`<form #editCustomerForm="ngForm" *ngIf="formActive">`

```

this.formActive = false;
setTimeout(() => {
      this.formActive = true;
      var exdate = new Date(this.editCustomer.expireDate);
      this.selectedDate = { date: { year: exdate.getFullYear(), month: exdate.getMonth() + 1, day: exdate.getDate() } };
                }, 0);
```

All inputs after this code are back to pristine except mydatepicker is still dirty

Is there any work around for this problem?

**Comment by kekeh** [comment]
Hi @dev-mfm 

there was a bug. Try version 2.5.0. You can also call reset function of Angular to reset value of form control.
