### ISSUE TITLE
my Date picker takes year as string instead of Number

### ISSUE THREAD

**Issue by MohitaSaxena** [kekeh/mydatepicker#467]
While incorporating the my date picker in angular 2 application, i came across an issue, when my input box with my date picker is pre filled and i try to select year from the datepicker then the whole application hangs. I try to debug the code and found the following 
![image](https://user-images.githubusercontent.com/30036611/32936140-0e275d74-cb99-11e7-9fe6-bbd6bf66aa31.png)

Could you please check and convert to number
Thanks in advance

**Comment by kekeh** [comment]
I did one fix. Now year parameter should be number. You can try version 2.5.1.
