### ISSUE TITLE
Detached DOM Nodes with MyDatePicker

### ISSUE THREAD

**Issue by saurav1005** [kekeh/mydatepicker#469]
While profiling an Angular 4 application I could find detached DOM nodes even though the component has been destroyed.
MyDatePicker version : "2.0.29"
The reference point for the detached DOM nodes looks to be MyDatePicker as seen below.
![mydatepicker -2](https://user-images.githubusercontent.com/14871430/33057433-0f4d2820-cedf-11e7-8e39-06be40678e09.png)

On comparing the heap snapshots for the application it seems the MyDatePicker instances live in the memory even if the invoking component is destroyed. 
![mydatepicker -1](https://user-images.githubusercontent.com/14871430/33057457-336e1566-cedf-11e7-8c46-1bb5638c118e.png)

On commenting the below code these detached DOM nodes are not present.
`<form #myForm="ngForm" novalidate>
       <my-date-picker [(ngModel)]="interim_review_date" 
                         [formControl]="creditDetailsForm.controls['interim_date']"
                        [options]="dtoptions" [disabled]="datedisable"></my-date-picker>
</form>`
Is there is a way to destroy these instances onDestroy of the invoking component.?
Since this has not been reported yet thus can anyone suggest if anything else to be looked at or followed to correct this.

**Comment by saurav1005** [comment]
Is anyone experiencing this issue as well in their applications?

**Comment by chiragdarji** [comment]
@saurav1005 I am also facing similar issue in my application. In my observation the there are still memory references available after moving from _mydatepicker_ component. We have used this component extensively through out our application. The memory gets multiply as the number of _mydatepicker_ instances used in one screen.

**Comment by kekeh** [comment]
I merged PR #475  which fixes this bug.

New version of the component is 2.5.3
