### ISSUE TITLE
the  callback ChangedDate called when initialized data

### ISSUE THREAD

**Issue by abaazzi** [kekeh/mydatepicker#471]
Hello,
the  callback ChangedDate called when initialized data,reproducible in last version.

Thank you.

**Comment by ZawilecxD** [comment]
Confirmed, have same issue in newest version. In my app it leads too inifinite loop of callbacks :(. Had do downgrade version of mydatepicker

**Comment by kekeh** [comment]
Hi, I did one fix. Now the **dateChanged** callback is not called on init. You can try version 2.6.0. 

Thanks a lot.
