### ISSUE TITLE
Getting yesterday jsdate in mozila browser. 

### ISSUE THREAD

**Issue by lakhvir1994** [kekeh/mydatepicker#472]
Hello every one, I am working on angular 4 application. I am using this date picker my application but getting one issue.  

When I am consoling jsdate coming on date select it will show current jsdate in chrome browser but when I am seeing it in mozila it displaya yesterday date. 

Any one know why it was happening and how to solve it.

**Comment by kekeh** [comment]
You can try to convert it to a local date: 

new Date(event.jsdate).toLocaleDateString()
