### ISSUE TITLE
Difference between formated date and jsdate object 

### ISSUE THREAD

**Issue by Vikram-ksingh** [kekeh/mydatepicker#473]
I have integrated it on my angular 4 app where I have a calendar integrated on a page, when I select a date call a REST api with post method sending timestamp of chosen date to get the result from API

API is working fine but it returns previous day data so I checked the date and timestamp in console and found that jsdate object return previous date from selected , following is my object logged on date selecte

date: Object { year: 2017, month: 11, day: 25 }
epoc: 1511548200
formatted: "25.11.2017"
jsdate: Date 2017-11-24T18:30:00.000Z
__proto__: Object { … }

How do it correct this ? is there any configuration to control it or if its correct way then how can I handle this issue ?

Any help is appreciable.

**Comment by kekeh** [comment]
You can try to convert to a local date:

new Date(event.jsdate).toLocaleDateString()

**Comment by kestutisj** [comment]
Hi, I am facing the same issue here.

date: Object { year: 2017, month: 11, day: 24 }
epoc: 1511474400
formatted: "2017-11-24"
jsdate: Date 2017-11-23T22:00:00.000Z

**Comment by kekeh** [comment]
Can you see any difference between Firefox and Chrome browser.
