### ISSUE TITLE
Reactive form date value is taking previous value

### ISSUE THREAD

**Issue by goutame** [kekeh/mydatepicker#474]
I am using mydatepicker version 2.5.2 with reactive form.

 <my-date-picker (dateChanged)="onDateChanged($event)" [options]="myDatePickerOptions" formControlName="singleDate"></my-date-picker>

onDateChanged method call the value of singleDate is setting previous value.

Please let me know where I am going wrong

**Comment by kekeh** [comment]
Is this problem only with **jsdate** property of **IMyDateModel**? Or all properties of **IMyDateModel**?

Can you see any difference if you are using Firefox or Chrome browser? Have you tried to convert jsdate value to local date?

**Comment by goutame** [comment]
In the $event it is setting correctly but in the formControlName it sets the previous selected value.
I didn't convert any values.I just followed as mentioned in the docs.
It behaves same in chrome and firefox

**Comment by kekeh** [comment]
Difficult to say anything without seeing you code.

Can you try to reproduce the issue? You can fork plunk from here: https://plnkr.co/edit/qBcVn6?p=preview

**Comment by kekeh** [comment]
It is because date picker call first the **dateChanged** callback and after that updates the model. The model is not yet updated with the new selected date when you print the value of model and that is why it prints the previous selected date.

If you set timeout like below it prints the right selected date.
```javascript
public onDateChanged(event: IMyDateModel) {
    console.log('onDateChanged(): ', event);
    if(event.jsdate) {
      let d: Date = new Date(event.jsdate.getTime());
    }
    this.dateChanged = JSON.stringify(event);
    setTimeout(()=> {
      this.myDate = this.filterForm.controls["singleDate"].value.formatted
      console.log("form value------->",this.filterForm.controls["singleDate"].value)
    });
}
```

but why you are reading **model** value in the **dateChanged** callback? Same data comes as event parameter to this callback.

**Comment by kekeh** [comment]
You can do as follows:

```javascript
public onDateChanged(event: IMyDateModel) {
    console.log('onDateChanged(): ', event);
    if(event.jsdate) {
      let d: Date = new Date(event.jsdate.getTime());
    }
    this.dateChanged = JSON.stringify(event);
    this.myDate = event.formatted
}
```

**Comment by goutame** [comment]
Based on the model value i need to enable and disable drop downs.
inputFieldChange works for me.
Thanks
