### ISSUE TITLE
Angular 5 AoT build issue

### ISSUE THREAD

**Issue by Manumeld** [kekeh/mydatepicker#476]
I know you say it is compatible only with Angular 2 and 4. What about Angular 5? Are you planning to support it sometime soon?

I got the following error while compiling with webpack after ngc:
_ERROR in ./aot/node_modules/mydatepicker/dist/my-date-picker.component.ngfactory.js
Module not found: Error: Can't resolve './directives/my-date-picker.focus.directive' in '.\aot\node_modules\mydatepicker\dist'
 @ ./aot/node_modules/mydatepicker/dist/my-date-picker.component.ngfactory.js 4:0-66_

It seems that the problem is, that ngc had't created the './directives/my-date-picker.focus.directive.ngfactory.js' file. In the './directives' directory, there are generated only 'my-date-picker.focus.directive.ngfactory.js.map' and 'my-date-picker.focus.directive.ngsummary.json'.

I have angular version 5.0.3 and webpack 3.8.1.

**Comment by kekeh** [comment]
Are you using Angular cli and If yes which version? I have not testeissä with Angular 5, but I think It should work also with It.

You can try to reinstall module. Sometimes some of the files are missing from the node_modules/mydatepicker folder.
- npm remove mydatepicker
- npm install mydatepicker

If you not using Angular cli Probably you have to exclude node_modules folder from the build.

**Comment by kekeh** [comment]
This project uses Angular 5 and mydatepicker: https://github.com/kekeh/mydatepicker/tree/gh-pages

The project is running here: http://kekeh.github.io/mydatepicker/

it is angular/cli project

Have you already solved the problem?

**Comment by Manumeld** [comment]
I wasn't using Angular cli and now I tried to restructure my project with it and it works. Thanks :)

**Comment by rajesha-xpanxion** [comment]
Hi,

I'm getting below error when I try to rollup after successful ngc command. Below is error details:
[!] Error: Could not resolve './directives/my-date-picker.focus.directive' from aot\node_modules\mydatepicker\dist\my-date-picker.component.ngfactory.js
Error: Could not resolve './directives/my-date-picker.focus.directive' from aot\node_modules\mydatepicker\dist\my-date-picker.component.ngfactory.js
    at error (D:\Projects\SCT\SVN\ClientSideFrameworks-COE-master\ClientSideFrameworks-COE-master\Source Code\StarterKits\Angular4\xpanxion.angular.web\node_modules\rollup\dist\rollup.js:185:14)
    at then.resolvedId (D:\Projects\SCT\SVN\ClientSideFrameworks-COE-master\ClientSideFrameworks-COE-master\Source Code\StarterKits\Angular4\xpanxion.angular.web\node_modules\rollup\dist\rollup.js:10062:8)
    at <anonymous>

In my case, I'm not using Angular CLI based. Do we have any solution in such case?
Below is my package.json:

`{
  "name": "",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "ngc": "ngc -p tsconfig-aot.json && ngc -p public-tsconfig-aot.json",
    "rollup": "rollup -c rollup-config.js && rollup -c public-rollup-config.js",
    "build:aot": "ngc -p tsconfig-aot.json && ngc -p public-tsconfig-aot.json && rollup -c rollup-config.js && rollup -c public-rollup-config.js",
    "cleancss": "cd assets/styles  && cleancss --output sitestyle.min.css --keep-line-breaks --skip-advanced app.component.css spinner.component.css public.component.css toastr.component.css product-dialog.component.css ng2-select.css"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/animations": "5.2.4",
    "@angular/common": "5.2.4",
    "@angular/compiler": "5.2.4",
    "@angular/core": "5.2.4",
    "@angular/forms": "5.2.4",
    "@angular/http": "5.2.4",
    "@angular/platform-browser": "5.2.4",
    "@angular/platform-browser-dynamic": "5.2.4",
    "@angular/router": "5.2.4",
    "@ng-bootstrap/ng-bootstrap": "1.0.0",
    "angular2-logger": "0.6.0",
    "bootstrap": "4.0.0",
    "core-js": "2.5.3",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.6.1",
    "intl": "1.2.5",
    "jquery": "3.2.1",
    "moment": "2.20.1",
    "mydatepicker": "^2.6.3",
    "ng-fullcalendar": "1.3.1",
    "ng2-bs3-modal": "0.10.4",
    "ng2-cookies": "1.0.12",
    "ng2-select": "1.2.0",
    "ng2-translate": "5.0.0",
    "primeng": "5.2.3",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.6",
    "systemjs": "0.21.0",
    "tether": "1.4.3",
    "tslib": "1.8.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "5.2.4",
    "@angular/language-service": "5.2.0",
    "@types/core-js": "0.9.35",
    "@types/fullcalendar": "3.8.0",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/jquery": "3.2.17",
    "@types/node": "6.0.60",
    "clean-css": "3.4.23",
    "codelyzer": "4.0.1",
    "concurrently": "3.5.0",
    "lite-server": "2.3.0",
    "rollup": "0.50.0",
    "rollup-plugin-commonjs": "8.2.1",
    "rollup-plugin-includepaths": "0.2.2",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-uglify": "2.0.1",
    "source-map-explorer": "1.5.0",
    "tslint": "5.7.0",
    "typescript": "2.5.3"
  }
}
`

When I checked in aot folder, I'm not able to find "my-date-picker.focus.directive.ngfactory.js" file in "~\aot\node_modules\mydatepicker\dist\directives" folder.

Please let me know if you have any solution for this issue.
