### ISSUE TITLE
running test faild

### ISSUE THREAD

**Issue by ChenReuven** [kekeh/mydatepicker#48]
Hey,
i try to run: npm test 

and i get this exception:
[1] Chrome 53.0.2785 (Windows 7 0.0.0) ERROR
[1]   Uncaught SyntaxError: Unexpected token import
[1]   at test/my-date-picker.module.spec.ts:3

note: i didnt run the gulp-all command cause it also faild :( [do i need to run it?]

**Comment by kekeh** [comment]
Tests can be started by **npm run test** command. But as you can see from the link below I haven't created any test case yet. I just added testing staff some days ago to this project. 

https://github.com/kekeh/mydatepicker/blob/master/test/my-date-picker.module.spec.ts

You need to run **gulp all** command only if you change the code under the **src/my-date-picker** folder.

**Comment by kekeh** [comment]
Now there are unit tests. Not all covered but I will add later more.
