### ISSUE TITLE
HighlightDates attribute is not working.

### ISSUE THREAD

**Issue by ankitakukreti** [kekeh/mydatepicker#482]
I am finding this error while trying to highlight a week.

ERROR in /mnt/ebsdir/..../../.. - ... .component.ts (63,5): Type '{ inline: true; showSelectorArrow: false; highlightDates: any[]; sunHighlight: false; }' is not assignable to type 'IMyOptions'.
 Object literal may only specify known properties, and 'highlightDates' does not exist in type 'IMyOptions'.)
/mnt/ebsdir/..../../.. - ... .component.ts.component.ts (181,7): Type '{ inline: true; showSelectorArrow: false; highlightDates: any[]; sunHighlight: false; }' is not assignable to type 'IMyOptions'.
 Object literal may only specify known properties, and 'highlightDates' does not exist in type 'IMyOptions'.)

**Comment by kekeh** [comment]
What kind of value you try to put to the highlightDates option?

**Comment by ankitakukreti** [comment]
I am puting an array of IMyDate type object in highlighDates.
Like:- 

weekArray: IMyDate[ ] = [ ];
  weekObj: IMyDate = {
    year: 0,
    month: 0,
    day: 0
  };

 private myDatePickerOptions: IMyOptions = {
   highlightDates: this.weekArray,
}

**Comment by kekeh** [comment]
Here https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-normal/sample-date-picker-normal.ts#L189

is an example on how to dynamically set the **highlightDates** option.

**Comment by ankitakukreti** [comment]
Thanks for the reply. But when I tried to write IMyDpOption then it's
showing an error that IMyDpOption is not available in my date picker.

**Comment by kekeh** [comment]
Is it working if you try the code below?

```javascript

import {IMyDpOptions} from 'mydatepicker';
// other code

myDatePickerOptions: IMyDpOptions = {
    highlightDates: [{year: 2017, month: 12, day: 14}, {year: 2017, month: 12, day: 15}]
}
```

use **IMyDpOptions** instead of **IMyOptions**. It is working ok in my sample application and here: http://kekeh.github.io/mydatepicker/
