### ISSUE TITLE
Confusing docs about locale

### ISSUE THREAD

**Issue by tavuntu** [kekeh/mydatepicker#484]
In the README file there's not enough information on how we should se the locale, it just says we can add or modify the file with the locales, but it doesn't have an example of something like this:

`this.myDatePickerOptions.setLocale('es')`

am I missing something?

**Comment by kekeh** [comment]
There is **locale** attribute. Use it as follows:
```html
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)" 
    [locale]="locale"></my-date-picker>
```

```javascript
// default locale for example es
locale: string = 'es';

// You can change locale dynamically
changeLocale(locale: string): void {
    this.locale = locale;
}
```

Supported locales are listed here: https://github.com/kekeh/mydatepicker#locale-attribute

**Comment by tavuntu** [comment]
I see, sorry, I think the problem was visual studio code, it was throwing an error when trying to use that attribute (or maybe it's missing on the TS definition? I don't know). Anyway, thanks!
