### ISSUE TITLE
value is not removed if enter the text 

### ISSUE THREAD

**Issue by Mean563** [kekeh/mydatepicker#485]
When user trying to enter text, it is showing red colour, if I am trying to remove the text using backspace still one character is remaining, if it is empty I need to show Some Validation Message.
 Any one faces this issues please comment. 

Thanks In advance !!!

**Comment by kekeh** [comment]
You can implement **inputFieldChanged** callback. Then you know when the input box is empty. Here is documentation of the callback: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

You can test callback here: http://kekeh.github.io/mydatepicker/

open console of the browser to see messages of the callback.

**Comment by Mean563** [comment]
Hi @kekeh , sorry.. I was facing issue for range date picker. I was doing same doing same thing like below code :+1: 

```
 e.prototype.onInputFieldChanged = function(e) {
                console.log("onInputFieldChanged(): Value: ", e.value, " - dateFormat: ", e.dateFormat, " - valid: ", e.valid)
            }
         
```

But if suppose I am trying below example:

`I was trying to enter "AAAAAAAAAA"`
Event is not firing for last removed value, i was checked in `console.log()`
