### ISSUE TITLE
How to bind the value

### ISSUE THREAD

**Issue by pushkar4you** [kekeh/mydatepicker#486]
Hi,
Following code is written for the mydatepicker in HTML file.

<my-date-picker [options]="activation"
                                        name="activationDate" 
                                        id="activationDate"
                                        [(ngModel)]="notificationData.activationDate" 
                                        #activeDate="ngModel"                                     
                                        title="Activation Date"
                                        (inputFocusBlur)="onInputFocusBlurActive($event,this.modalForm)"                                        
                                        required>
When I try to open the record in edit mode I am not able to bind my datasource value to mydatepicker control. It showing blank.

notificationData.activationDate In this field I bind the value from datasource and it's like ''01/04/2018"(mm/dd/yyyy) format but in the form it showing blank.

Solution should work in IE and FIREFOX not require in chrome.

Please advise how to bind the value to mydatapicker.

Thank you,
Pushkar

**Comment by kekeh** [comment]
You can use ngModel binding. Here is an example: https://github.com/kekeh/mydatepicker#1-ngmodel-binding

You can use **jsdate**, **date** or **formatted** property as follows to set initial date:
```html
<my-date-picker name="activationDate" [options]="activation" [(ngModel)]="model"></my-date-picker>
```
```javascript
private model: any = {jsdate: new Date(2018, 0, 4)};  
// or
private model: any = {date: {year: 2018, month: 1, day: 4}};  
// or
private model: any = {formatted: '01/04/2018'};   
```
