### ISSUE TITLE
I Want input field date and calender view different dates when updating

### ISSUE THREAD

**Issue by faridaanjum** [kekeh/mydatepicker#488]
when I want to update a record i will pass the existed date to the picker. then it is showing same date in inputfield and calender. but i want to show the given time in the input field and today date view in the calender. how can i acheive this.

**Comment by kekeh** [comment]
You can use the defaultMonth attribute to open calendat to specific month. Here is an example how to the defaultMonth attribute: https://github.com/kekeh/mydatepicker/wiki/Initialize-with-defaultMonth-attribute
