### ISSUE TITLE
Reactive Forms

### ISSUE THREAD

**Issue by DominicSachs** [kekeh/mydatepicker#49]
Is there way to use mydatepicker with reactive forms and validation like this: 

```
this.form = this._formBuilder.group({
    startDate: ["", Validators.compose([CustomValidators.required, CustomValidators.cutomDate])],
})
```

**Comment by duki994** [comment]
Well it doesn't have value accessor (ControlValueAccessor if I'm not mistaken) so you can't use directive with formControlName or bind [formControl].

There's simple workaround which works for me.

```
<my-date-picker [options]="myDatePickerOptions"
                                                        (dateChanged)="this.signupForm.controls['bdate'].setValue($event.formatted)"></my-date-picker>
```

$event.formatted will return formated date as string in format you specified in myDatePickerOptions.
For example 'dd-mm-yyyy' will give you string '28-11-2016'.

When user inputs date then form control will be updated and custom validators will be run upon it.

Hope I helped :)

**Comment by BrainCrumbz** [comment]
It might be useful to add this info in readme, as a section dedicated to Reactive Forms.

**Comment by kekeh** [comment]
I added value accessor to my-date-picker. Now **ngModel** and **formControlName** attributes are supported. Check more info from the README file.

Here is an example (run sampleapp): https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

New version of the component is: 1.2.0

**Comment by BrainCrumbz** [comment]
Great, looking forward to try it!

**Comment by BrainCrumbz** [comment]
Reactive form version of this component looks good, thank you. 

One issue while working with it, though: we're trying to set value programmatically with something like myForm.controls['myDatePickerField'].setValue(....). We tried passing several types of input arguments, but with no luck, generally the input seems unaffected and keeps its former value. Of course also the example you gave before has been tried: `...setValue('20/02/2017')`.

Have you an idea, what are we doing wrong?

**Comment by duki994** [comment]
@BrainCrumbz 

Check console log if it shows errors. setValue() is really extreme method. it literally places/replaces object of form with one you set it in arguments.

Also setValue() doesn't propagate change event, so no elements update, as Angular 2 didn't register change event. Use patchValue() for your example. It'll propagate change event and Angular 2 will update element values and show new value :)

**Comment by BrainCrumbz** [comment]
Thanks for quick reply. Usually we go with `setValue` when we want to replace **all** form fields, as Angular will complain if anyone of them is missing its corresponding value to set. Instead we go with `patchValue` if one wants to partially update the form, just on some of its fields, but not all.

Of course I can try with `patchValue` as well, actually we also tried with setting value at the single `Control` level, without luck. Right now I don't have the runtime error ready at hand, I'll post it later. 

What I'm missing is what type of data should we pass for the datepicker. Not sure wheter it could be:

1. date formatted as string, in the same format specified by options + locale. E.g.: `'28/03/2017'`
1. a "shorthand" date object has used somewhere else in component: `{ day: number, month: number, year: number }`
1. the same type as the one received by `dateChanged` event, `{ date: Object; jsdate: Date; formatted: string; epoc: number; }`, or maybe just some of those properties
1. a JS `Date` object

We tried I think all of those, with no luck

**Comment by kekeh** [comment]
### Initialization value

If you leave value uninitialized set empty string like below:
```javascript
this.myForm = this.formBuilder.group({
  myDate: ['', Validators.required]
  // other controls are here...
});

```
If you want to initialize value set object which contain date part from the **IMyDateModel**. For example: **{date: {year: 2018, month: 10, day: 9}**. IMyDateModel: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/interfaces/my-date-model.interface.ts
```javascript
this.myForm = this.formBuilder.group({
  myDate: [{date: {year: 2018, month: 10, day: 9}}, Validators.required]
  // other controls are here...
});
```

ngModel takes similar initialization value.

**Comment by BrainCrumbz** [comment]
@kekeh thanks for info, I've also noticed those on the readme, although the scenario I was trying to explain is different, my bad. I'm not trying to initialize form fields. I'm trying to alter form fields programmatically when something happens, apart from the user typing.

E.g. my form holds a plain text input and one datepicker, and it part of a custom component. This component has a settable `@Input` property shaped as `{ myText: string; myDate: Date /* or whatever other shape makes sense to hold a date */ }`.

When that input property is set from the outside, such component should set form values accordingly. What we normally do is invoke `this.myForm.setValue({ ... })` with a properly shaped input that matches its field. This last part is not working here: we cannot figure out yet what to pass as input for the datepicker field.

**Comment by kekeh** [comment]
In some cases you need to run NgZone.run() to update UI. Check this: https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html

**Comment by BrainCrumbz** [comment]
@kekeh could you please show how to invoke `form.setValue()` or `control.setValue()` when mydatepicker is involved? Continuing same example, say you have:

```ts
this.myForm = this.formBuilder.group({
  'myText': [''],
  'myDate': [''],
});

this.myDateControl = this.myForm.controls['myDate'];
```

How would you invoke `this.myForm.setValue({ ... })` or `this.myDateControl.setValue({ ... })` in order to set e.g. date to March 20th 2017?

**Comment by kekeh** [comment]
If you set value to the **myText** and the **myDate** you can try something like this:
```ts
this.myDateControl.setValue({myText: 'This is my text', myDate: {date: {year: 2018, month: 10, day: 9}}});
```

**Comment by BrainCrumbz** [comment]
Ok, thanks a lot for hint. I tried just on the single control with:

```ts
this.myDateControl.setValue({ date: { day: 20, month: 3, year: 2017 } });
```

then on the whole form with:

```ts
this.myForm.setValue({
  myText: 'abc',
  myDate: {
    date: {
      day: 20,
      month: 4,
      year: 2017,
    },
  },
});
```

and in both cases it works now.

What value should we pass to mean "empty", if we want to clear that field? I tried with `null` and empty string but apparently it did not work.

Also, would you consider a PR adding this info to readme? Actually, we could integrate the PR already in place for readme.

**Comment by kekeh** [comment]
There was a bug. Now **empty string** clears the date if it is used with **setValue** function. I added code example also to the README file.

New version of the component is 1.2.3.

**Comment by BrainCrumbz** [comment]
Wow, that is really a quick turnaround! Thanks a lot for being supportive. Confirmed that v1.2.3 works great also clearing field

**Comment by ankur09** [comment]
Hi,
am having two input fields  fromdate and todate , i want to use datepicker for both fields . am able to use datepicker for one field not for other one. I also want to set condition in todate on basis of fromdate.
I hv tried different fromControlName for each other and also tried to set value in setDate() method but still not working

**Comment by robinkedia** [comment]
duki994 - You (datechanged) event suggestion solves the problem of setting formatted value. But now how do we reset control? Generally model reset should have solved the problem, now its like explicit code required to clear textbox
