### ISSUE TITLE
Month and year label not showing 

### ISSUE THREAD

**Issue by AtoMaso** [kekeh/mydatepicker#490]
Issue: month and year label not visible dues to sass issues.
Fix: 
The current component's sass needs to be overwritten with the following code:
:host /deep/ 
.mydp .headermonthtxt, 
.mydp .headeryeartxt {   
    text-align: center;
    width: 40px;
    max-width: 40px;   
}
:host /deep/
.mydp .headerlabelbtn {
    font-size: 14px;
    outline: 0;
    cursor: default;
     width: 40px;
    max-width: 40px;   
to be able to see the month and year label properly.

**Comment by AtoMaso** [comment]
The issues was caused by the local button's css class extending the button length to 150 px. The label on the button of the date picker was in the centre and with not visible.
There is nothing wrong with the original style sheet.

**Comment by kalai092** [comment]
i have added the mentioned css code, but now its only appearing while mouse over, otherwise the text is not appearing.
