### ISSUE TITLE
inputFieldChanged event.valid returns incorrect result

### ISSUE THREAD

**Issue by rmpp19** [kekeh/mydatepicker#491]
Incorrect value for event.valid

Sample logs:
onInputFieldChanged(): Value:  01/01/2006  - dateFormat:  mm/dd/yyyy  - valid:  false
onInputFieldChanged(): Value:  01/01/2005  - dateFormat:  mm/dd/yyyy  - valid:  false

For some value it works fine:
onInputFieldChanged(): Value:  01/01/2007  - dateFormat:  mm/dd/yyyy  - valid:  true
onInputFieldChanged(): Value:  01/01/2004  - dateFormat:  mm/dd/yyyy  - valid:  true

**Comment by kekeh** [comment]
Difficult say anything without seeing your configuration of datepicker. Have you disabled some dates or set min or max years.

Can you fork this plunk and try reproduce issue: https://plnkr.co/edit/qBcVn6?p=info

**Comment by rmpp19** [comment]
Forked plunkr: https://plnkr.co/edit/KST2P6PNCsH48rTlk4mk?p=preview

datepicker configuration:

myDateOptions: IMyDpOptions = {
      dateFormat: 'mm/dd/yyyy',
      disableWeekends: true,
      firstDayOfWeek: 'su'
  };

To replicate put 01/01/2005 in the textbox.

**Comment by kekeh** [comment]
It is invalid date because you have option **disableWeekends** set to **true**. Date 01/01/2005 is Saturday so it is invalid date because it is weekend date.

All disabled dates are handled as invalid dates. I think it is working as expected.

**Comment by rmpp19** [comment]
Ohhh okay! Thanks for the explanation :)
