### ISSUE TITLE
Support of full name of month

### ISSUE THREAD

**Issue by Kangaro97** [kekeh/mydatepicker#493]
Is it allowed to get such date format: 21 January, 2018?
As I understood, if change **monthLabels** from Jan to January, I get necessary result, however, this action also change month labels in inline calendar and they may not fit fully.
Or there are other ways to convert **IMyDate** which binded with input. 
I tried to use pipe. And date.formatted was changed as I wish, but was not displayed in browser.

HTML

    <input type="text" name="date"
    ngx-mydatepicker 
    [ngModel]="date | dateFormat" 
    (dateChanged)="date=$event" 
    [options]="options"
    #dp="ngx-mydatepicker">     

Pipe

    import { Pipe, PipeTransform } from '@angular/core';

    @Pipe({
      name: 'dateFormat'
    })

    export class DateFormatPipe implements PipeTransform {
      transform(date: any): any {
        if (!date) { return {}; }
        const monthNames = [
          'January', 'February', 'March',
          'April', 'May', 'June', 'July',
          'August', 'September', 'October',
          'November', 'December'
        ];
        date.formatted = date.jsdate.getDate() + ' ' + monthNames[date.jsdate.getMonth()] + ', ' + date.jsdate.getFullYear();
        return date;
      }
    }

**Comment by kekeh** [comment]
Full name of month are supported. You have give date format For example dd mmm, yyyy and pass month names to options.
