### ISSUE TITLE
Spanish dateFormat

### ISSUE THREAD

**Issue by JimmySpicy** [kekeh/mydatepicker#496]
Hello,

I am using your datepicker and for the Spanish locale there is an issue.
Currently it is implemented like this:
'es': {
                dayLabels: { su: 'Do', mo: 'Lu', tu: 'Ma', we: 'Mi', th: 'Ju', fr: 'Vi', sa: 'Sa' },
                monthLabels: { 1: 'Ene', 2: 'Feb', 3: 'Mar', 4: 'Abr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Ago', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dic' },
                **dateFormat: 'dd.mm.yyyy',**
                todayBtnTxt: 'Hoy',
                firstDayOfWeek: 'mo',
                sunHighlight: true,
            },

But the dateFormat shoud be **'dd/mm/yyyy'.**

Is it possible to have this change request ?

Please advise
Thanks
Best Regards

**Comment by kekeh** [comment]
You can create a pull request from this change if the date format is not valid.

**Comment by kekeh** [comment]
You can also set the Spanish locale and set right date format in options. The date format of options overrides the date format of locale.
