### ISSUE TITLE
Setting disableSince/disableUntil to Tomorrow(next day) or Yesterday

### ISSUE THREAD

**Issue by rishijoshi** [kekeh/mydatepicker#497]
Is there a way to disable "from next day" or "from tomorrow" or "until yesterday"? Looks like there is a disableUntil and disableSince which takes a object of year, month and day but you need to explicitly set the year, month and day. 
Should there be a way where you can set the disableUntil/disableSince date based on which timezone you are in.

**Comment by kekeh** [comment]
Here is example how to didableUntil to yesterday: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

Same way you can disableSince from tomorrow.

let d: Date = new Date();

// yesrerday
d.setDate(d.getDate() - 1);

// tomorrow
d.setDate(d.getDate() + 1);
