### ISSUE TITLE
Is there any way to add time in epoc

### ISSUE THREAD

**Issue by kirandas82** [kekeh/mydatepicker#498]
My application need time to send along with the date. How can I do that? Epoc is always coming one day before because of it is not adding the time i guess; suppose I select 01/24/2018 the epoc will be 1516732200 and if I convert it the result will be 
GMT: Tuesday, January 23, 2018 6:30:00 PM
Your time zone: Wednesday, January 24, 2018 12:00:00 AM GMT+05:30, instead of 12:00:00 I need the actual time

**Comment by kekeh** [comment]
Not possible to get time. IT Works different way with different browsers. Are YouTube isin Firefox?

On dateChanged callback YouTube can create a new Date object from value of jsdate property.
