### ISSUE TITLE
Set disableSince using functions 

### ISSUE THREAD

**Issue by Vikram-ksingh** [kekeh/mydatepicker#500]
I am trying to implement disableSince with following functions but its not working 

```
public options: IMyDpOptions = {
      dateFormat               : 'mm/dd/yyyy',
      firstDayOfWeek           : 'su',
      height                   : '40px',
      editableDateField        : false,
      showClearDateBtn         : false,
      openSelectorOnInputClick : true,
      disableSince : {
         year  : 2018,
         month : 3,
         day   : 15
      }
   };

disableSince() {
      let copy = this.getCopyOfOptions();
      copy.disableSince = { year  : 2018,
                            month : 5,
                            day   : 15
                          };
      this.options = copy;
    }

    // Returns copy of myOptions
    getCopyOfOptions(): IMyDpOptions {
      return JSON.parse(JSON.stringify(this.options));
    }
```

is there a way to reset the disable since with other function if its depending upon runtime values

**Comment by kekeh** [comment]
Here IS example on how to Set disableUntil value dynamically: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

You can implement disableSince using Similä method.

You said IT IS not working. Whatsapp is The problem? 

You can try IT here with The online mode date picker: http://kekeh.github.io/mydatepicker/

**Comment by Vikram-ksingh** [comment]
Not sure what is the issue because its not showing any error and not even blocking the date based on parameters.

**Comment by kekeh** [comment]
Can you fork this https://plnkr.co/edit/qBcVn6?p=info plunk and try to reproduce this issue with the plunk.

**Comment by Vikram-ksingh** [comment]
Done 
https://plnkr.co/edit/P3sjOmyNCmeivNvKOnXK

**Comment by kekeh** [comment]
Hello @Vikram-ksingh 

You have to call the **disableSince()** function for example from the constructor or somewhere else. Then it is working.
```javascript
constructor() {
   this.disableSince();
}
```

**Comment by Vikram-ksingh** [comment]
Thanks kekeh,
I should have thought of it. Done
