### ISSUE TITLE
Override CSS

### ISSUE THREAD

**Issue by Manikandan-CloudevTech** [kekeh/mydatepicker#503]
Hi,

How can i change the default style. I don't want to have border and border-radius for the date picker. How can i do that..?

**Comment by kekeh** [comment]
You can check out this issue: https://github.com/kekeh/mydatepicker/issues/118

but overriding styles may be difficult.

One option is to create own version of the component and edit styles and then build. If you are willing to create own version you can start from here: https://github.com/kekeh/mydatepicker#development-of-this-component
