### ISSUE TITLE
how to define the same color of current month to the next days of next month?

### ISSUE THREAD

**Issue by RubensTen** [kekeh/mydatepicker#504]
I implemented a mydatepicker and I need that the next days of month take the same color of current month.

What is the config option to get this result ?

Attachment screen.
![datepicker](https://user-images.githubusercontent.com/13072050/35960673-33d56e7c-0c70-11e8-961a-1aaacde82942.png)

Thanks!!

**Comment by kekeh** [comment]
It is not configurable, but if you are implementing own version of component you can set background color as follows:
```css
.mydp table td {
    background-color: #F6F6F6;
}
```
