### ISSUE TITLE
pattern error catch

### ISSUE THREAD

**Issue by ikishor99** [kekeh/mydatepicker#505]
Dear team,

I want to handle invalid pattern error on my-date-picker.
if use enters wrong format date then it want to display message. I tried to use pattern in tag but it doesn't show pattern error, only required error is there.

{ "required": true }

Request your help 

Thank You

**Comment by kekeh** [comment]
You can implement The inputFieldChanged callback. Dokumentation: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback

There is valid flag which indicates IS date value valid or not in The input box when user type a date.

You can see IT in action here: http://kekeh.github.io/mydatepicker/

Open console of The browser to see all messages. Then type date to The input box.

**Comment by kekeh** [comment]
Here https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal IS example on how to usein inputFieldChanged callback.

**Comment by kekeh** [comment]
Here Also: https://github.com/kekeh/mydatepicker/wiki/inputFieldChanged-callback

**Comment by ikishor99** [comment]
Yes, I managed to use this. Thanks for reply
