### ISSUE TITLE
Getting the calendar to appear in div's with display block

### ISSUE THREAD

**Issue by yanshuf0** [kekeh/mydatepicker#507]
The calendar is covered when display is set to block for the parent divs unless you provide a height for the date picker. Any way to change this?

**Comment by kekeh** [comment]
Instead you can try this: https://github.com/kekeh/ngx-mydatepicker

there is an option append calendar to body element. In mydatepicker there is not this kind of option.

**Comment by yanshuf0** [comment]
Ok sounds good but that datepicker does not have the option to open selector on input click or to make input field non-editable which were two options I intended on using with this date picker. Any advice?

**Comment by kekeh** [comment]
In ngx-mydatepicker the input box is your own code and you can do it whatever you want.

**Comment by kekeh** [comment]
I close this issue. You can do both things with the ngx-mydatepicker.
