### ISSUE TITLE
how to style mydatepicker for bootstrap

### ISSUE THREAD

**Issue by ganqqwerty** [kekeh/mydatepicker#509]
are there quick recipes on how to style mydatepicker so that it looks like any other FormGroup in bootstrap?

**Comment by kekeh** [comment]
Setting styles to component from outside may be difficult. Probably easiest way is to create own version of the component and set styles. If you are willing to create own version of the component you can start from here: https://github.com/kekeh/mydatepicker#development-of-this-component
