### ISSUE TITLE
Masking date 

### ISSUE THREAD

**Issue by ikishor99** [kekeh/mydatepicker#511]
Dear @kekeh ,

I want to Mask date in DD/MM/YYYY format, 

https://igorescobar.github.io/jQuery-Mask-Plugin/ check for Mask placeholder option. 

How do I enable this for mydatepicker. I tried to use data-mask but is not working.

Thank You

**Comment by kekeh** [comment]
Hi @ikishor99 

Probably It does not work with the mydapicker. But you can try It with the ngx-mydatepicker. It may work better because you have access to input box and you can easily set the mask. 

Check out this: https://github.com/kekeh/ngx-mydatepicker
