### ISSUE TITLE
How to set Min and Max Date

### ISSUE THREAD

**Issue by pathmanabhankv** [kekeh/mydatepicker#514]
I need to show only between date of given min and max date example i want to display From 20 March2018 to 20 May 2018 between dates only. Please share Sample Code

**Comment by kekeh** [comment]
You can use **disableUntil** and **disableSince** options.

**disableUntil** : Disable dates backward starting from the given date. For example: {year: 2016, month: 6, day: 26}. To reset existing disableUntil value set: {year: 0, month: 0, day: 0}

**disableSince**: Disable dates forward starting from the given date. For example: {year: 2016, month: 7, day: 22}. To reset existing disableSince value set: {year: 0, month: 0, day: 0}

```javascript
myDatePickerOptions: IMyDpOptions = {
    // other options
    disableUntil: {year: 2018, month: 3, day: 19},
    disableSince: {year: 2018, month: 5, day: 21}
};
```

Above example disable dates statically. Here is an examle on how to disable dates dynamically: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option
