### ISSUE TITLE
Compability with Angular5

### ISSUE THREAD

**Issue by mikol4j** [kekeh/mydatepicker#516]
Hello,
Currently datepicker isn't compatible with Angular5. Do you plan to support it?

**Comment by kekeh** [comment]
It is already compatible with version 5 of Angular. This http://kekeh.github.io/mydatepicker/ page is angular/cli project and it uses version 5.0.5 of Angular.

The project of page is here: https://github.com/kekeh/mydatepicker/tree/gh-pages You can verify from the **package.json** that the version of Angular is 5.

What kind of problems you have with your project?

**Comment by mikol4j** [comment]
Ok, I can fully confirm this. After some modifications in package.json everything work good.
