### ISSUE TITLE
how to disable past date

### ISSUE THREAD

**Issue by mohammed534** [kekeh/mydatepicker#528]
i wasted 1 day of work to disable the past dates...i tried every concept...but no result...please help me on this..just needs to disable the past dates from today...

**Comment by kekeh** [comment]
Hi @mohammed534 

You can use the disableUntil option. Here ia an example on how to disable past dates starting from yesterday: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

If you want to disable starting from today just remove the d.setDate(d.getDate() -1); line and call the disableUntil() method.
