### ISSUE TITLE
date format dd mmm yyyy

### ISSUE THREAD

**Issue by lehrenberg** [kekeh/mydatepicker#53]
Is there any way to get the date displayed in the input field to have the format dd mmm yyyy, e.g. "30 Aug 1990"? I tried switching the dateFormat in the options as well as in the locale service.

**Comment by kekeh** [comment]
Now it is not possible. I will investigate this.

**Comment by kekeh** [comment]
Now you can use format like **dd mmm yyyy**. It shows date for example **15 Nov 2016**.

New version of the component is: 1.0.5.
