### ISSUE TITLE
Disable future dates

### ISSUE THREAD

**Issue by alok-srivastav** [kekeh/mydatepicker#530]
Hi Kekeh,

I need to disable future dates i.e. from the next day onwards always.
Please provide the solution for the same.

Thanks

**Comment by kekeh** [comment]
Hi @alok-srivastav 

You can use the **disableSince** option.

Here https://github.com/kekeh/mydatepicker/wiki/Set-disableSince-option is an example on how to disable future dates starting from tomorrow.
