### ISSUE TITLE
Show clearbutton if datepicker is enable

### ISSUE THREAD

**Issue by pkseasia** [kekeh/mydatepicker#537]
Hi,

I have few quires regarding mydatepicker:

1. How can set mask on my date picker like angular phone mask features.
2.  I don't want to show clearbutton in mydatepicker is disable and clearbutton should show if mydatepicker is enable if date is filled.

Thanks

**Comment by kekeh** [comment]
You have to use ngx-mydatepicker

repository: https://github.com/kekeh/ngx-mydatepicker
demo: https://kekeh.github.io/ngx-mydatepicker/

Check this issue: https://github.com/kekeh/ngx-mydatepicker/issues/45

Probably you can add mask (check above issue) and you can also select which buttons to add input box.

**Comment by pkseasia** [comment]
Thanks for Reply.

But I want that mydatepicker clear button should hide automatically if datepicker is in disable state and visible automatically if in enable state. 

Thanks

**Comment by kekeh** [comment]
If you want mask you have to use ngx-mydatepicker. There is option to hide/show the clear button. The option name is **showClearDateBtn**. Set it true/false.
