### ISSUE TITLE
compatibility with Angular 6

### ISSUE THREAD

**Issue by infactamente** [kekeh/mydatepicker#539]
Hi ,

I was wondering if its compatible with Angular 6 and 
if it can be added using ng add.

Thanks

**Comment by kekeh** [comment]
I don't know if it is compatible with angular 6. But probably yes. I have not tested it with angular 6. You have to follow instructions from the readme file. What you mean by ng add?

**Comment by infactamente** [comment]
thanks for response,
ng add new command introduced in @angular/cli v 6
example : ng add @progress/kendo-angular-buttons

**Comment by kekeh** [comment]
It is compatible with angular 6. Here is example application: https://github.com/kekeh/mydatepicker/tree/gh-pages
