### ISSUE TITLE
Feature request: disable array of dates

### ISSUE THREAD

**Issue by Misenooooo** [kekeh/mydatepicker#54]
I would welcome a feature to disable an array of concrete dates. 

Something like this http://stackoverflow.com/questions/30331543/disabling-specific-dates-from-html-datepicker-jquery.

**Comment by kekeh** [comment]
I added **disableDays** option:

Disable single days one by one. Array of disabled days. For example disable two separate days: disableDays: [{year: 2016, month: 11, day: 14}, {year: 2016, month: 1, day: 15]

Here is an example: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-inline/sample-date-picker-inline.ts
