### ISSUE TITLE
Problem with markDates attribute

### ISSUE THREAD

**Issue by mikol4j** [kekeh/mydatepicker#547]
Hello,
I am declaring a new object of IMyDpOptions and have a trouble with markDates property.
I'd like to load dates from database and can't figure out any solution to achieve this.
Always data come too late. I tried to return it as an Observable from my function getDays(), but this property does not accept Observable.

        public myDatePickerOptions: IMyDpOptions = {
        markDates: this.getDays() || []
    };

    getDays() : Array<IMyMarkedDates>
    {
        let obj: Array<IMyMarkedDates> = new Array<IMyMarkedDates>();
        obj[0] = <IMyMarkedDates>{};
        obj[0].color = '#ff0000';
        obj[0].dates = [];

            this._dataService.getJson('api/getDays')
                .subscribe(s => {
                    this.daysOff = s;
                    obj[0].dates = s || [];    
                    return obj;
                });
        

    }

How to properly do this?

**Comment by kekeh** [comment]
It is possible set date picker options dynamically. It works also in your case. Here is an example how to set options dynamically: https://github.com/kekeh/mydatepicker/wiki/Set-disableSince-option

The example is disableSince option but the idea works also with markDates option.

You have to create copy of options in order the date picker detect change of option. Then set new values like done in the example.

**Comment by mikol4j** [comment]
Works fine, but now I have to change month to make marked dayes visible.
I mean days are not marked when I click on datepicker first time.
When disableSince() function frome your example should be fired?

**Comment by kekeh** [comment]
You call the disableSince() in your case it is markDates() after you have read dates from the database. The markDates() function set values to the markDates option.

**Comment by mikol4j** [comment]
Of course, I understand. I've done it the same way as you described, however I still have to change month in datepicker to see result.

**Comment by kekeh** [comment]
You can test markDates here: http://kekeh.github.io/mydatepicker/

select the **Mark today** and open the date picker => today is marked.

Code of function is here: https://github.com/kekeh/mydatepicker/blob/gh-pages/src/app/sample-date-picker-normal/sample-date-picker-normal.ts#L118
