### ISSUE TITLE
How to Set Focus on My date Picker

### ISSUE THREAD

**Issue by pkseasia** [kekeh/mydatepicker#548]
How to set focus on my date piker.

I tried using @ViewChild("focusDateEl") trgfocusDateEl: ElementRef;

                                    <my-date-picker 
                                      focusDateEl
                                      [options]="myDatePickerOptions"
                                      [placeholder]="dateFormatPlaceholder"
                                      name="termination_date">
                                    </my-date-picker>

Thanks
Parveen

**Comment by kekeh** [comment]
Better to this component: https://github.com/kekeh/ngx-mydatepicker In this component the input box is your own code so you can set focus easily.

Here is demo of th component: https://kekeh.github.io/ngx-mydatepicker/
