### ISSUE TITLE
Set focus on my date picker

### ISSUE THREAD

**Issue by pkseasia** [kekeh/mydatepicker#549]
I was trying to set focus on my date picker but I was enable to set focus.

I have few quires : 

1. How to assign id to date picker ?
2.  Set focus on my date picker when open a popup.

Thanks
Parveen

**Comment by karthik-github1** [comment]
Did you able to find any solution on this?

**Comment by kekeh** [comment]
1. What is the purpose of id?
2. When calendar opens it is focused automatically (blue border). You can press tab or tab + shift to move focus forth and back.

**Comment by karthik-github1** [comment]
I would mainly like to set the focus on the input text control after validating the date which happens at onSubmit() of the form event.

**Comment by kekeh** [comment]
You can try to call the **setFocusToInputBox()** function as follows. I haven't tested this but it should work.

```html
<!-- define mydp local variable to the tag as follows -->
<my-date-picker #mydp="mydatepicker" [options]="myOptions"></my-date-picker>
```

```ts
import {Component, ViewChild} from '@angular/core';
import {MyDatePicker, IMyOptions, IMyDateModel} from 'mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // other options here...
        dateFormat: 'dd.mm.yyyy'
    }

    // Define the view child variable
    @ViewChild('mydp') mydp: MyDatePicker;

    constructor() {}

    // calling this set focus to input box
    setFocusToInput() {
        this.mydp.setFocusToInputBox();
    }
}
```

**Comment by karthik-github1** [comment]
Thank you @kekeh . It worked indeed!!
