### ISSUE TITLE
feature request: beforeShowDay callback

### ISSUE THREAD

**Issue by cristianmtr** [kekeh/mydatepicker#55]
really like the component.

wondering how hard it would be to add a `beforeShowDay` callback, similar to the one in jQuery UI [here](https://api.jqueryui.com/datepicker/#option-beforeShowDay), or the one in this [JS datepicker](https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&calendarWeeks=on&autoclose=on&todayHighlight=on&keyboardNavigation=on&forceParse=on&beforeShowDay=on&toggleActive=on#sandbox)

I would be willing to contribute to this, but I would appreciate some guidance

**Comment by Wotzhs** [comment]
Hi Cristian, are you trying to disable certain dates in the datepicker? If that's the case, I have a workaround in Angular2 that can achieve "similar" effect. 

The codes below allow me to disable the dates earlier than today for both start and end date, selecting any date in the start date **first**, will disable the dates between today's date and the selected date in the end date datepicker.

Similarly, selecting any date in the end date **first**, will disable all the dates after the selected dates in the start date datepicker.

I however have not tried to disable different individual dates.

**in some-component.component.ts**
```
import {Component, OnInit} from '@angular/core;
...
ngOnit(){
    this.startDateOptions ={
        dateFormat: "dd/mm/yyyy",
        disableUntil: {year: new Date().getFullYear() , month: new Date().getMonth()+1 , day: new Date().getDate()-1}}
    }

   this.endDateOptions = {
      dateFormat: "dd/mm/yyyy",
      disableUntil: {year: new Date().getFullYear() , month: new Date().getMonth()+1 , day: new Date().getDate()-1}
    }
}
...
updateStartDate(event:any){
    return this.endDateOptions = {
    	dateFormat: "dd/mm/yyyy",
    	disableUntil: event.date
    }
}

updateEndDate(event:any){
    return this.startDateOptions = {
    	dateFormat: "dd/mm/yyyy",
    	disableUntil: {year: new Date().getFullYear() , month: new Date().getMonth()+1 , day: new Date().getDate()-1},
        disableSince: event.date
    }
}

```

**in some-component.component.html**
```
...
<my-date-picker class="six wide field" [options]="startDateOptions" (dateChanged)="updateStartDate($event)"></my-date-picker>
<my-date-picker class="six wide field" [options]="endDateOptions" (dateChanged)="updateEndDate($event)"></my-date-picker>
...
```

**Comment by cristianmtr** [comment]
I have managed to get this working in a sort of hack-ish way. 

- add an ng2 input for a method from the parent
- before adding a day to the week (`week.push(...`), call that callback with the date

I need it for some custom state for specific dates. This is a backend-specific feature, and it's per individual dates.

**Comment by kekeh** [comment]
I have already added option to disable certain dates. Check it from version: 1.0.5

| disableDays  | no default value  | Disable single days one by one. Array of disabled days. For example: [{year: 2016, month: 11, day: 14}, {year: 2016, month: 1, day: 15] |

Changing content of the array updates disabled days to datepicker.

**Comment by kekeh** [comment]
I added **calendarViewChanged** callback. It is called every time when the calendar view change (year or month change). Latest version is 1.0.15.

Add callback attribute to the **my-date-picker** tag:
```html
(calendarViewChanged)="onCalendarViewChanged($event)"
```
Define the callback function for example:
```javascript
onCalendarViewChanged(event:any) {
  console.log('onCalendarViewChanged(): Year: ', event.year, ' - month: ', event.month, ' - first: ', event.first, ' - last: ', event.last);
}
```

Check function parameters from here: https://github.com/kekeh/mydatepicker#calendarviewchanged-callback

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal
