### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by pranjalsm** [kekeh/mydatepicker#551]
i wanted to change border to be none so i am trying   border: 0px  white  but css style is overriding to custom css how i can get it calender with no border
->
![image](https://user-images.githubusercontent.com/39515643/41893631-104aca6a-793a-11e8-8a65-cf309b504f4d.png)
 
for me 
<style>
    @import "./override.css";
</style>
This is not working

**Comment by kekeh** [comment]
It may be difficult to override styles of component. Here is another issue: https://github.com/kekeh/mydatepicker/issues/118

**Comment by pranjalsm** [comment]
I just wanted remove calendar border .. any other solution for it

**Comment by kekeh** [comment]
If border is blue it means it is focused. You have to override also those focus styles. But I am not sure that override of styles works.

You can also create own version of the component. Then you can set styles you want. You can start from here: https://github.com/kekeh/mydatepicker#development-of-this-component
