### ISSUE TITLE
disableSince and disableUntil issue

### ISSUE THREAD

**Issue by navin11** [kekeh/mydatepicker#552]
Hi, 

Thanks for the awesome date picker. I'm just wondering how can I enable a year in year selection if that whole year is not enabled by using "disableSince" and "disableUntil"

Example 

myDatePick : IMyDpOptions = {
              dateFormat: 'yyyy-mm-dd',
              showClearDateBtn: false,
              disableSince: {year: 2017, month: 2, day: 28},
              disableUntil: {year: 2015, month: 6, day: 28}
            };    
if I give above object, I'm not able to select 2017 from year selection. Critical issue is if I give same month and year, then I'm not able to select any year. Hope issue is clear.

![image 1](https://user-images.githubusercontent.com/28753680/42027037-55074928-7ae6-11e8-8879-2a6e938b2a4a.png)

**Comment by kekeh** [comment]
You can try to disable with disableDateRanges option and set aldo minYear and maxYear.

**Comment by navin11** [comment]
Thanks a lot, "disableDateRanges" with minYear and maxYear is working as expected. Happy to close this issue.
