### ISSUE TITLE
How to set minDate and maxDate?

### ISSUE THREAD

**Issue by zakirmd** [kekeh/mydatepicker#554]

**Comment by kekeh** [comment]
You can use both the **disableUntil** and the **disableSince** options to disable dates. You can do same also with the **minYear**, **maxYear** and **disableDateRanges** option.

The **disableUntil** example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option
The **disableSince** example: https://github.com/kekeh/mydatepicker/wiki/Set-disableSince-option

The examples above disable dates dynamically. If you don't need to disable dynamically you can set disable values directly to IMyOptions.
