### ISSUE TITLE
Unable to navigate to previous month when disableUntil and enableDays are used in combination.

### ISSUE THREAD

**Issue by lunar95** [kekeh/mydatepicker#555]
I need to enable only specific dates and disable the remaining. To achieve this I did:
 disableUntil:{day:31,month:12,year:9999},
    disableDays:[{day:8,month:6,year:2018},{day:6,month:7,year:2018},{day:2,month:9,year:2018},{day:12,month:10,year:2018},{day:14,month:5,year:2018}]
and I initialized myDate to present day date (Updates everyday).
It does not allow me to navigate to previous months when I'm doing this. Can you please help me with this. Thanks in advance.

**Comment by kekeh** [comment]
Hi @lunar95 

You can do it as follows:
```javascript
myDpOptions: IMyDpOptions = {
    minYear: 2017,
    maxYear: 2019,
    disableDateRanges: [{begin: {year: 2017, month: 1, day: 1}, end: {year: 2019, month: 12, day: 31}}],
    enableDays:[{day:8,month:6,year:2018},{day:6,month:7,year:2018},{day:2,month:9,year:2018},{day:12,month:10,year:2018},{day:14,month:5,year:2018}]
};
```
The **disableDateRanges** disable all from begin 2017 to end 2019. The **enableDays** enables specific dates.

Also if you want t to open specific month of calendar you can use the **defaultMonth** attribute: https://github.com/kekeh/mydatepicker#defaultmonth-attribute

**Comment by lunar95** [comment]
This calendar ends with year 9999. What's the beginning year... because I gave those enable dates to test the code...thanks in advance
