### ISSUE TITLE
Manual input change is not working with disableUntil

### ISSUE THREAD

**Issue by olehleskiv** [kekeh/mydatepicker#561]
When I added  
```
disableUntil: {
    year: 2015,
    month: 12,
    day: 31
  };
```
and manually input the date into field `01/01/2005` the value is not emitted, I got `null` from datepicker - so I cannot validate it using custom validators.

Does this work as designed?

**Comment by kekeh** [comment]
Hi @olehleskiv 

Disabled dates are not emitted. I works as designed. You cannot select disabled date from the calendar. You cannot select disabled date by typing it to input box.
