### ISSUE TITLE
disableUntil as last day of the month bug

### ISSUE THREAD

**Issue by Kojima13** [kekeh/mydatepicker#565]
Current:
-If the current date is 29 August 2018 and the min_date given in disableUntil is 31 August 2018
-The user go to the next month in the calendar (So the displayed month is now September)
-The user cannot go back to August.

Expected:
-If the current date is 29 August 2018 and the min_date given in disableUntil is 31 August 2018
-The user go to the next month in the calendar (So the displayed month is now September)
-The user can go back to August so he can select 31 August.

**Comment by kekeh** [comment]
Hi @Kojima13 

Set the disableHeaderButtons option to true and then it should be possible.

**Comment by kekeh** [comment]
Correction to my previous comment.

Instead of set option to true set it to false. Then it should work.

**Comment by Kojima13** [comment]
That's not what I want though. The disableHeaderButtons should be true and be actually working. Here I should be able to go back to the previous month because there is still 1 day enabled.
