### ISSUE TITLE
Textbox for datepicker is missing on Chrome version 69.0.3497.92 (64-bit)

### ISSUE THREAD

**Issue by joelduncan1** [kekeh/mydatepicker#569]
OS: Windows 10
Node.js: 8.11.4
NPM: 5.6.0
Chrome: 69.0.3497.92

Hi,

I am having an issue on the textbox for the datepicker is not showing for Chrome version 69 but it is showing on previous version of Chrome (version 68) 

Kindly need advice.

Regards,

**Comment by kekeh** [comment]
It is working here ok with the Chrome 69. Link: http://kekeh.github.io/mydatepicker/

Can you try it?

**Comment by joelduncan1** [comment]
weird it is working I bet it is only an issue to our css.

**Comment by kekeh** [comment]
ok. I will close issue.
