### ISSUE TITLE
Disabling the datepicker component is not working

### ISSUE THREAD

**Issue by jjsophi** [kekeh/mydatepicker#570]
By setting the componentdisabled to true, it disables, but it is not getting enabled again. 
Pls help

**Comment by kekeh** [comment]
This should work:

```html
<my-date-picker [options]="myDatePickerOptions"  (dateChanged)="onDateChanged($event)" 
    [disabled]="disabled"></my-date-picker>
```

```javascript
private disabled: boolean = false;

onDisableComponent(disabled: boolean) {
    this.disabled = disabled;
}
```

Here is a demo (Check/Uncheck **Disabled component**): http://kekeh.github.io/mydatepicker/

Code of demo is here: https://github.com/kekeh/mydatepicker/tree/gh-pages/src/app/sample-date-picker-normal
