### ISSUE TITLE
set date function is not working properly for this.myForm.patchValue when calling another component.

### ISSUE THREAD

**Issue by vedprakashpandey** [kekeh/mydatepicker#572]
I am trying to call setDate function from another component function call but it is not selected date . I try to see this.myForm value in console , value is properly available in date object but not showing in calender
input field.

![calendererror](https://user-images.githubusercontent.com/5336721/45874566-db8bca00-bdb2-11e8-9610-388b0dd052aa.PNG)

**Comment by kekeh** [comment]
Hi @vedprakashpandey 
Here is working example: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-access-modifier/sample-date-picker-access-modifier.ts#L67

**Comment by vedprakashpandey** [comment]
In my scenario there is a page which is super parent which is calling one modal popup child component and in modal popup has calendar component and I want when modal popup open that also triger calender set date when super parent call open modal popup and as popup show the date picker input field  should be selected date. But I think that is not find this.form.patchValue.

**Comment by vedprakashpandey** [comment]
Parent page call child modal popup function this.assignActivity.openActivityModal() --> Child Modal popup call child datepicker setDate function this.customDatePicker.setDefaultDate(date); -->
 setDefaultDate(defaultDate){
     // Set default date using the patchValue function  
      let newDate = new Date(defaultDate);      
      this.dateForm.patchValue({agendaDate: {
      date: {
          year: newDate.getFullYear(),
          month: newDate.getMonth() + 1,
          day: newDate.getDate()}
      }});
      console.log(this.dateForm.value.agendaDate.date);
    }


console show the form value but not show in input field also not highlighted  date in calender.
It may be two binding problem?.

**Comment by kekeh** [comment]
Maybe this is useful reading: https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html
