### ISSUE TITLE
404 XHR error problems at loading mydatepicker/src/my-date-picker/my-date-picker.component.html.js

### ISSUE THREAD

**Issue by gokulrajs** [kekeh/mydatepicker#58]
Hi,

I imported mydatepicker module to my app module. While running app, i faced xhr 404 error at loading mydatepicker/src/my-date-picker/my-date-picker.component.html.js and mydatepicker/src/my-date-picker/my-date-picker.component.css.js in browser console window.
I am using system js to load a module.

please give me a hint to resolve.

**Comment by ThomasYangLin** [comment]
hi,
a have the totally same problem when i use this component,can somebody give a solution?thanks a lot

**Comment by corner22** [comment]
same problem for me.

**Comment by Marfyy** [comment]
I got it working by changing the package in systemjs.config.js from **"./index.js"**, to **"./dist/index.js"**

Example:

```
packages: {
     mydatepicker: {
         main: './dist/index.js'
    }
```
Not sure if this is a valid long term fix...

**Comment by gokulrajs** [comment]
Yes.. You are correct Marfyy....

**Comment by gokulrajs** [comment]
Above one from Marfyy Or Build by gulp.... Use the same ./index.js... If you include as part of app, compilation of module leads this error....
Any further problems, please comment
