### ISSUE TITLE
Date highlight not showing correct

### ISSUE THREAD

**Issue by KumailHussain** [kekeh/mydatepicker#580]
I set the date on click but calendar is not highlighting the value
 <i class="fa fa-times-circle red popup-cross ripple" (click)="setDate()"></i>
 <input (dateChanged)="setScheduleDate(prop.data.reviewMeeting._id,'appealMeetingStatus',prop.data.reviewMeeting,null,'appealMeetingDate',$event)"  class="form-control custom-date calendar-input " style="float:none" placeholder="Select a date" ngx-mydatepicker name="mydate"
                           [(ngModel)]="model" [options]="calendarChild" #dp3="ngx-mydatepicker" />

setDate(){
      let today = new Date()
      
      this.model =   { year: today.getFullYear(), month: today.getMonth()+1, day: today.getDate() } ;

}

console is showing the correct date but on calendar its not

**Comment by kekeh** [comment]
Set model as follows. You missed date property.

model: any = {date: {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()}};

**Comment by KumailHussain** [comment]
I also tried the same solution but the calendar shows me wrong date
