### ISSUE TITLE
Show the selected date in angular2

### ISSUE THREAD

**Issue by ndlganeshu** [kekeh/mydatepicker#59]
Please let me know how can we show the selected date.

We tried selectedDate in options but not working.
or
using [selDate] = "selectedDate" completely breaking the input box.

Please suggest me.

**Comment by WaiYanCho** [comment]
Hi,
you should use as 

`<my-date-picker [options]="myDatePickerOptions"
               (dateChanged)="onDateChanged($event)" [selDate]="_obj.t1" name="date"></my-date-picker>`
 
 onDateChanged(event:any) {
        this._date =  this._util.changeDatetoFormat(event.formatted); 
    }

**Comment by kekeh** [comment]
The [selDate]="selectedDate" accepts string value as same format as **dateFormat** option is.

For example: 
`
private selectedDate:string = '14.11.2016';
`
