### ISSUE TITLE
Not working with Internet Explorer 11

### ISSUE THREAD

**Issue by kambojankit** [kekeh/mydatepicker#6]
Hey it doesn't seem to work on IE11, even the demo link doesn't work. I get the below error: 

> 'System' is undefined

**Comment by kekeh** [comment]
I think you can add IE11 support with this:

<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.min.js"></script>

**Comment by kambojankit** [comment]
Thanks for the quick help @kekeh. This issue is fixed with your changes. Hence closing this issue.
