### ISSUE TITLE
Mozilla firefox, Version earlier than 64, ReferenceError: event is not defined Stack trace in function onClickDocument

### ISSUE THREAD

**Issue by Chetna124** [kekeh/mydatepicker#634]
**ERROR: node_modules/mydatepicker/dist/my-date-picker.component.js"]/MyDatePicker.prototype.onClickDocument@http://localhost:4200/vendor.js:117444:1** 

Angular Version 8
Line no 444, my-date-picker-component.ts
MyDatePicker.prototype.onClickDocument = function (evt) {.......}
When i changed (evt) of this function to (event), i didn't face this error. But, I am facing the issue in production build. I cannot put this solution in production build.

Please give some leads.
![mozilla datepicker error](https://user-images.githubusercontent.com/22514356/83173703-ed507380-a136-11ea-8232-b64e10190f55.PNG)

**Comment by kekeh** [comment]
What is version of datepicker?

You can also use a new version of this component:
  - repository: https://github.com/kekeh/angular-mydatepicker
  - demo: https://kekeh.github.io/angular-mydatepicker/

**Comment by Chetna124** [comment]
> What is version of datepicker?
> 
> You can also use a new version of this component:
> 
> * repository: https://github.com/kekeh/angular-mydatepicker
> * demo: https://kekeh.github.io/angular-mydatepicker/

@kekeh ,I am using 2.6.10, Earlier I was using 2.6.3. I upgraded using npm install --save mydatepicker@latest. Bu still facing the same issue.

**Comment by kekeh** [comment]
Changed evt to event in onClickDocument function #636 merged.
