### ISSUE TITLE
Not getting exact date when i click back button in Form

### ISSUE THREAD

**Issue by Saiprasad2020** [kekeh/mydatepicker#639]
@kekeh

In my from i used my-date-picker ,the form having two steps first step is fill the order details , second step having address,

i my order details having two dates from date and todate, here i used my date picker,

i'm selectin two dates  But i if i click next it gone to second step of form ,

till here it's going good , when i click on back to made some modification in first step of form ,

what are the dates i selected i.e from date, todate is changes to single date i.e todate. or some time it's not display in date field 

for cleared that issues i used 

<my-date-picker name="myDate" [options]="myDatePickerOptions" formControlName="myDate" (dateChanged)="onDateChanged($event)" [selDate]="selDate">

It workd for me But if i used twice [selDate]="selfromdate" and [selDate]="seltodate"

It's taking only one we can't use [selDate] twice in same form ..
it's over riding one date with other which we are passing last date(todate) is overriding the first one (selfromdate)

So it's showing only one date which we enter last How we can override this problem

here also if i used this for from date it's overridning to todate ,
so how can i make the dates same when i go step2 , and back to step1 of form , 

i hope you got my point , it' very urgent can you please help me on this 

thanks in advance ..

**Comment by kekeh** [comment]
Instead of **selDate** attribute you can try to use **ngModel** to set date. Example: https://github.com/kekeh/mydatepicker#1-ngmodel-binding

or

If you are using reactive forms here is an example: https://github.com/kekeh/mydatepicker#2-reactive-forms
Check **setDate()** function.

In first step save the date. If user back from second step to first step restore saved date to **ngModel**.

**Comment by Saiprasad2020** [comment]
thanks you i only did the mistake it's working fine earlier only, i mean before sending the request what is he mistake i does is, in name both date i used like name='mydate' now i change to name='fromdate' and name='todate' so ti's working fine ,
any way thanks for responding 

earlier it was::
from date::: <my-date-picker **name="mydate"** [options]="myDatePickerInlineOptions" (dateChanged)="getValidateFromDate($event)"
									  [(ngModel)]="orderRequestData.from" required  #from="ngModel"
									  [class.is-invalid]="from.invalid && from.touched" ></my-date-picker>
									
todate::::my-date-picker **name="mydate"** [options]="mydatePickerOption" (dateChanged)="getValidateToDate($event)"
									  [(ngModel)]="orderRequestData.to" required 
									  required  #to="ngModel"
									  [class.is-invalid]="to.invalid && to.touched" ></my-date-picker>
			

so it shows the date which i mentioned second one. now i cahnge those to 

from date ::: 
my-date-picker **name="fromdate"** [options]="mydatePickerOption" (dateChanged)="getValidatefromDate($event)"
									  [(ngModel)]="orderRequestData.from" required 
									  required  #to="ngModel"
									  [class.is-invalid]="to.invalid && to.touched" ></my-date-picker>
todate to :: my-date-picker **name="todate" [options]="mydatePickerOption" (dateChanged)="getValidateToDate($event)"**
									  [(ngModel)]="orderRequestData.to" required 
									  required  #to="ngModel"
									  [class.is-invalid]="to.invalid && to.touched" ></my-date-picker>
									

it's working fine. Small issue but make big difference. 
thanks for responding
