### ISSUE TITLE
Convert date to timezone format 

### ISSUE THREAD

**Issue by sadashivm** [kekeh/mydatepicker#647]
Hello Team,
I want to convert the selected date to timezone format like,

**_2021-09-14T14:32:26+05:30_**

my date format option is,
![image](https://user-images.githubusercontent.com/10355473/133227873-d1baff12-4742-4389-8cf7-fa7e339de5ac.png)

and date picker looks like,
![image](https://user-images.githubusercontent.com/10355473/133228047-61b4abb7-3e30-468e-b3c6-557ce38f3072.png)

is there any way to convert the selected date in the above format?

**Comment by kekeh** [comment]
You can implement the **dateChanged** callback which provides a javascript date object from the selected date. Documentation: https://github.com/kekeh/mydatepicker#datechanged-callback

```html
<my-date-picker name="mydate" [options]="myDatePickerOptions"
     [(ngModel)]="model" (dateChanged)="onDateChanged($event)"></my-date-picker>
```

```ts
onDateChanged(event: IMyDateModel) {
  console.log('onDateChanged(): ', event.date, ' - jsdate: ', new Date(event.jsdate).toLocaleDateString(), ' - formatted: ', event.formatted, ' - epoc timestamp: ', event.epoc);
}
```

I think it is better to use newer version of the datepicker:
 - Repository: https://github.com/kekeh/angular-mydatepicker
 - Demo page: https://kekeh.github.io/angular-mydatepicker/
