### ISSUE TITLE
AOT mode is not supported

### ISSUE THREAD

**Issue by jinshad** [kekeh/mydatepicker#66]
Aot build not working with this module. It works fine with normal ng build. 

angular-cli: 1.0.0-beta.18
Steps to reproduce : ng build --aot

```
0% compiling Error encountered resolving symbol values statically. Reference to
 a local (non-exported) symbol 'myDpStyles'. Consider exporting the symbol (posi
tion 8:7 in the original .ts file), resolving symbol MyDatePicker in D:/angular-test/
node_modules/mydatepicker/src/my-date-picker/my-date-picker.component.ts
```

Please resolve this. Thanks in advance.

**Comment by nekkon** [comment]
+1

**Comment by esbeto** [comment]
I think this is pretty easy to achieve, instead of using `require`, use `templateUrl` and `styleUrls` instead.

**Comment by kekeh** [comment]
You can try again with version 1.0.7 from npm. 

I put template and styles as inline parameters to component also in typescript version.
