### ISSUE TITLE
Can i install it without raw loader?

### ISSUE THREAD

**Issue by kambojankit** [kekeh/mydatepicker#7]
I am using angular2-seed project which uses System Js for module loading. 

Will i still be able to use the plugin or it requires raw-loader as pre-requisite?

**Comment by kekeh** [comment]
If you don't want to use raw loader you have to change code (https://github.com/kekeh/mydatepicker/blob/master/src/app/mydatepicker.ts). Inside @View({
Add:
`
   templateUrl: 'app/template/mydatepicker.html',
   styleUrls: ['app/css/mydatepicker.css'],

`
Remove:
`
   template: require('raw!./template/mydatepicker.html'),
   styles: [require('raw!./css/mydatepicker.css')]
`

I verified that it works with IE11 here: http://kekeh.github.io/mydatepicker/
