### ISSUE TITLE
Implement clear date programatically

### ISSUE THREAD

**Issue by lnaie** [kekeh/mydatepicker#70]
I want to able to clean the date picker by clicking on other external button. Right now we have to call myDatePickerComponent.removeBtnClicked().

**Comment by kekeh** [comment]
This can be done with the following way:

1. Add selDate attribute to **my-date-picker** tag. For example: [selDate]="selectedDate"
2. Initially it can be empty:  private selectedDate:string = '';
3. In **onDateChanged**(event:any) callback set value every time to the selectedDate member when the date is selected. For example: this.selectedDate = event.formatted;
4. After that setting empty string to the selectedDate member clears the date. For example: 
`clearDate() {
this.selectedDate = '';
}`


Here is example: 

- https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-normal/sample-date-picker-normal.ts

- https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-normal/sample-date-picker-normal.html

New version number of the component is: 1.0.2

**Comment by navin11** [comment]
what if I have two datepicker field should get clear??

I've tried with 2 objects, which I will set [(ngModel)], but only one field getting cleared
