### ISSUE TITLE
Swedish local is missing

### ISSUE THREAD

**Issue by NiklasJFischer** [kekeh/mydatepicker#73]
'sv': {
            dayLabels: {su: 'Sön', mo: 'Mån', tu: 'Tis', we: 'Ons', th: 'Tor', fr: 'Fre', sa: 'Lör'},
            monthLabels: { 1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'Maj', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Okt', 11: 'Nov', 12: 'Dec' },
            dateFormat: 'yyyy-mm-dd',
            todayBtnTxt: 'Idag',
            firstDayOfWeek: 'mo',
            sunHighlight: false,
        }

**Comment by kekeh** [comment]
I added sv locale.

New version of the component is: 1.0.3
