### ISSUE TITLE
error TS6059

### ISSUE THREAD

**Issue by nanoo-k** [kekeh/mydatepicker#75]
Here's a sample of the error I'm recieving:

```
error TS6059: File '/.../node_modules/mydatepicker/
index.ts' is not under 'rootDir' '/.../src/ts'. 'ro
otDir' is expected to contain all source files.
```

The error occurs during my gulp command which compiles my Typescript and puts it in our public directory (posted below).

I've read elsewhere that this error occurs when compiling a directory that has `.ts` files next to `.d.ts` files? I stop getting the error when I don't try to include the`MyDatePickerModule` in my NgModule.

Below is a snapshot of my systemJS config. I'm using `mydatepicker v1.0.0`. Any idea how to debug this issue?
```
// SystemJS snapshot
var paths = {
    // We copy the node_modules we use to a public directory.
    'npm:': 'js/'
};

var map = {
    'mydatepicker':   'npm:mydatepicker/dist',
    ...
};

vat packages = {
   mydatepicker: {
      main: './index.js',
      defaultExtension: 'js'
    }
};
```

```
// GULP COMMAND which compiles our src code and puts it into a public directory
// gp_sourcemaps is 'gulp-sourcemaps'
// srcPath and destPath is just the path for the source and destination of our code
gulp.task('app-build', ['app-resources'], function () {
    return tsProject.src(srcPaths.app)
        .pipe(gp_sourcemaps.init())
            .pipe(tsProject())
        .pipe(gp_sourcemaps.write('/'))
        .pipe(gulp.dest(destPaths.app));
});
```

Other ppl with similar issue:
http://stackoverflow.com/questions/36066430/ts6059-in-ignored-directory
http://stackoverflow.com/questions/35648347/importing-ng2-bootstrap-changes-my-tsc-output-directory-structure/35878902#35878902

**Comment by nanoo-k** [comment]
When I run `npm install mydatepicker --save` it includes a src directory which includes the .ts files. If I delete that directory then I avoid the errors above. Now I'm looking at this one:

`src/ts/app.module.ts(23,36): error TS2307: Cannot find module 'mydatepicker'.`

This one I think is an issue with my SystemJS configuration.

**Comment by kekeh** [comment]
Try to import MyDatePickerModule this way:

import { MyDatePickerModule } from 'mydatepicker/dist/my-date-picker.module';

SystemJS config:
var map = {
    'mydatepicker':   'npm:mydatepicker',
    ...
};

vat packages = {
   mydatepicker: {
      defaultExtension: 'js'
    }
};

**Comment by nanoo-k** [comment]
Confirmation that this fixed it. Thanks!

**Comment by tavuntu** [comment]
old thread but it looks these are the right instructions: https://github.com/kekeh/mydatepicker
