### ISSUE TITLE
Datepicker not showing in grids

### ISSUE THREAD

**Issue by muneeb057** [kekeh/mydatepicker#76]
I am facing an issue in datepicker. It does not show completely when applied into text field in a table.

I have a table, in its <tr> I have applied date picker. The datepicker appears, but when clicked on the icon, the calendar that opens goes into the grid and shows half of it, as my grid's height is around 300px only. Please resolve this so that the calendar shows outside of the grid. See below image

![datepicker](https://cloud.githubusercontent.com/assets/23448564/20258279/c2d512d4-aa70-11e6-9326-f8c0d7857c57.png)

<my-date-picker (dateChanged)="onDateChanged($event,'DosFrom')" [options]="ProcOptions"></my-date-picker>

**Comment by kekeh** [comment]
I did one fix (version: 1.0.1) but probably reason is that your HTML table have CSS style **overflow: hidden** or **overflow-x: hidden**

Try to set style **overflow-x: visible**

**Comment by muneeb057** [comment]
Tried that, but didn't work. I set my table css to overflow-x: visible. I also tried changing css of parent div, that didn't work either. Can you specify what did you fix in latest version so that I can compare my version and can traceout the issue.

**Comment by kekeh** [comment]
Are you implementing own table or using existing component? I had exactly the same problem and the reason was overflow: hidden.

If you are using some existing component you have to use inspector of the browser and try to find overflow: hidden. 

Latest version is: 1.0.5

**Comment by muneeb057** [comment]
I am implementing my own table. I will try your suggestion and get back to you.

Thanks for the help !!
