### ISSUE TITLE
Default font is Bold on the date control

### ISSUE THREAD

**Issue by ssashok10** [kekeh/mydatepicker#77]
The default font for this control is BOLD and it looks odd on the screen. It would be nicer to see the font with non bold letters.

**Comment by kekeh** [comment]
There is no option but you can override styles of the datepicker. Check instructions and sampleapp from here: https://github.com/kekeh/mydatepicker#change-styles-of-the-component

Lates verion is: 1.0.11

**Comment by chris93007** [comment]
Tried to override css and it didn't work, i added the styles in the template's scss file.
