### ISSUE TITLE
Options to set default date on the date control

### ISSUE THREAD

**Issue by ssashok10** [kekeh/mydatepicker#78]
I am trying to set default date on the date control. However, i am not seeing it on the documentation. Is there any way that i can set the default date as current date? Thanks.

**Comment by kekeh** [comment]
This sets default date.

The [selDate]="selectedDate" attribute in **my-date-picker** tag accepts string value as same format as dateFormat option is.

For example:
private selectedDate:string = '14.11.2016';

**Comment by ssashok10** [comment]
Thanks. Yes. The string value works. I had issues with the date value.
