### ISSUE TITLE
Data binding

### ISSUE THREAD

**Issue by ws-gianni** [kekeh/mydatepicker#80]
<my-date-picker class="form-control" [options]="myDatePickerNormalOptions"
                        name="dataNascita" [(ngModel)]="medico.dataNascita" #dataNascita="ngModel">
</my-date-picker>

Error: No value accessor for form control with name: 'dataNascita'

Is possible to binding data?

**Comment by ws-gianni** [comment]
I added 'ngDefaultControl'; Now I do not have the error but I do not see the data.....

<my-date-picker class="form-control" [options]="myDatePickerNormalOptions"
                                  name="dataNascita" [(ngModel)]="medico.dataNascita" #dataNascita="ngModel"
                                  **ngDefaultControl**>
>
</my-date-picker>

**Comment by kekeh** [comment]
If you want to put some data to date picker you can use only these attributes:

- Mandatory attributes:
 - [options]="myDatePickerOptions"

- Optional attributes:
 - [selDate]="selectedDate" || [defaultMonth]="defaultMonth"
 - [locale]="locale"

**Comment by overwise** [comment]
Hi Kekeh,
Nice module, thank you. I'm not sure if I have the same problem as ws-gianni, but it goes under the same title. Obviously, we need to use the date that user choose, and I can't figure out how to do that. When I add `[(ngModel)]="test"` to `<my-date-picker>`, I get this error: `Can't bind to 'ngModel' since it isn't a known property of 'my-date-picker'`.
So, how to extract chosen date from the field?
Thanks

**Comment by kekeh** [comment]
There is a callback **dateChanged** which notifies the parent application when user select the date.

Add callback to the **my-date-picker** tag like below:
```html
<my-date-picker [options]="myDatePickerNormalOptions" 
(dateChanged)="onDateChanged($event)"></my-date-picker>
```
Then you need to implement callback function **onDateChanged** in your own application:
```javascript
onDateChanged(event:any) {
  console.log('onDateChanged(): ', event.date, ' - formatted: ', event.formatted, ' - epoc timestamp: ', event.epoc);
}
```
* **event.date** contain selected date as an Object
* **event.formatted** contain formatted date as a string
* **event.epoc** contain epoc time stamp as a number

Here is complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

You can run this sampleapp. Instructions are here: https://github.com/kekeh/mydatepicker#development-of-this-component

**Comment by kekeh** [comment]
I added value accessor to my-date-picker. Now **ngModel** and **formControlName** attributes are supported. Check more info from the README file.

Here is an example (run sampleapp): https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-access-modifier

New version of the component is: 1.2.1

**Comment by madukhai** [comment]
Hi, Kekeh, I using 
```
<my-date-picker name="dateFrom"  [options]="myDatePickerOptions" 
		                    formControlName="dateFrom" ></my-date-picker>
```
and get this error on my browser console
```
Template parse errors: Can't bind to 'options' since it isn't a known property of 'my-date-picker'.
1. If 'my-date-picker' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'my-date-picker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("     <my-date-picker name="dateFrom"  [ERROR ->][options]="" 	                    formControlName="dateFrom"  ></my-date-picker>     "): 
```

**Comment by kekeh** [comment]
Did you follow instructions from here: https://github.com/kekeh/mydatepicker#installation

What kind of configuration you have? Not seen this error earlier.

**Comment by madukhai** [comment]
yes, I followed that, and found that in the browser source there is  no `mydatepicker` in js folder

like it does not load `mydatepicker`

**Comment by madukhai** [comment]
nevermind, was my stupid mistake!
it is working fine!!!!

Thanks for your perfect date picker!
