### ISSUE TITLE
how can i use custom template or stylesheet

### ISSUE THREAD

**Issue by designedev** [kekeh/mydatepicker#81]
thanks to developer. it`s awesome module.

can i use external(custom) template or stylesheet using templeteUrl or styleUrls ?

**Comment by kekeh** [comment]
You can override styles if you want. All styles are here: https://github.com/kekeh/mydatepicker/blob/master/src/my-date-picker/my-date-picker.component.css

For example override selection area background color:
.mydp .selection {
       background-color: yellow;
}

Those overrides have to be loaded after the date picker component has been loaded.

**Comment by chris93007** [comment]
There was no src folder during npm install.
