### ISSUE TITLE
parseSelectedDate called with date object

### ISSUE THREAD

**Issue by wburgers** [kekeh/mydatepicker#85]
Hi,

Inside the ngOnChanges function, when selecting a new date, the changes.selDate propery is set.
This property contains two things: currentValue and previousValue.
the currentValue is a date object, but is parsed with the parseSelectedDate function.
I have set a custom date format, so it tries to parse the date object according to the custom format.
This won't work, because the currentValue is an object.

Stacktrace:
TypeError: dateString.substring is not a function
    at ValidatorService.parseDatePartNumber
    at MyDatePicker.parseSelectedDate
    at MyDatePicker.ngOnChanges

Edit:
I must add that I've bound the selDate property with an initial value in the custom date format.
<my-date-picker [options]="datePickerOptions" (dateChanged)="updateToValue($event)" [selDate]="toValue"></my-date-picker>

**Comment by kekeh** [comment]
I am not able to reproduce with sampleapp (https://github.com/kekeh/mydatepicker/tree/master/sampleapp). 

```html
    <my-date-picker [options]="myDatePickerOptions" (dateChanged)="onDateChanged($event)"
                    [selDate]="selectedDate"></my-date-picker>
```
If you set value to the **selectedDate** variable in the **onDateChanged()** callback check that you set it like below. It have to be **event.formatted** not **event.date**.
```javascript
    onDateChanged(event:any) {
        if(event.formatted !== '') {
            this.selectedDate = event.formatted;
        }
    }
```

**Comment by wburgers** [comment]
Ah right
The event itself was pushed back into the selectedDate.
Thanks for your very quick response and help!
