### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Stoope** [kekeh/mydatepicker#87]
Hi! How can i detect type of validation error in input field? For example, i want to show error message like "format error", "max date error" and disable submit button.

**Comment by kekeh** [comment]
If user type an invalid date to the input field the background of input field is changed to red but there is not any notification to the host application. I need to add a new callback to this.

**Comment by Stoope** [comment]
It would be very useful for me, thank you for answer. Now there is no way to detect validation error or add custom validators, right?

**Comment by kekeh** [comment]
I added **inputFieldChanged** callback. Take the latest version 1.0.13. 

Add callback to **my-date-picker** tag:
```html
(inputFieldChanged)="onInputFieldChanged($event)"

```
Define callback function:
```javascript
onInputFieldChanged(event:any) {
  console.log('onInputFieldChanged(): Value: ', event.value, ' - dateFormat: ', event.dateFormat, ' - valid: ', event.valid);
}
```
Readme: https://github.com/kekeh/mydatepicker/blob/master/README.md#inputfieldchanged-callback

Here is a complete example: https://github.com/kekeh/mydatepicker/tree/master/sampleapp/sample-date-picker-normal

**Comment by Stoope** [comment]
Thank you! That's what I need!

**Comment by nimishgoel56** [comment]
I am using this inputFieldChanged event. It gets called when input(selected by datepicker ) is changed. 
inputFieldChanged event do not get fired when I put some invalid date by keyboard in the text box and now remove all the text one by one using backbutton and when last character is removed from textbox it should fire the inputFieldChanged event, but no event gets fired.  You can check in the screenshot also, When I removed last character also 0,  this event was supposed to fire and we should get the blank value in the console. Any possiblity to find how to fire that event in case of last character removed(When We are putting the invalid date by keyboard.)
![screenshot 11](https://user-images.githubusercontent.com/30027827/29168515-d5032914-7dec-11e7-8f25-75cea1f08ddd.png)

**Comment by Stoope** [comment]
It's a bug. I've make pull request https://github.com/kekeh/mydatepicker/pull/396.
