### ISSUE TITLE
iSeldate usage

### ISSUE THREAD

**Issue by designedev** [kekeh/mydatepicker#88]
i want to fix displaying date if user checked invalid date.(programmatically)

ex)
in html :
<my-date-picker [options]="myDatePickerOptions" (dateChanged)="dateChanged($event)" [selDate]="dateText"></my-date-picker>

in component : 
dateChanged() {
//to fix displaying date..
this.dateText = '2016-10-01' 
}

when i change date first time, date shown as '2016-10-01'
but after second click, date show user-clicked date.

how can i fix diaplaying date text?

**Comment by kekeh** [comment]
You can avoid user to select invalid date by using **disableUntil**, **disableSince**, **disableDays** or **disableWeekends** options. You can change them programmatically.

But if user type invalid field to input field the **dateChanged()** callback is not called. I am adding a new callback to this just now.

**Comment by designedev** [comment]
thank you.

**Comment by kekeh** [comment]
Here is example how to use **disableUntil** and **disableDays** options: https://github.com/kekeh/mydatepicker/blob/master/sampleapp/sample-date-picker-inline/sample-date-picker-inline.ts
