### ISSUE TITLE
[selDate] is not working at runtime

### ISSUE THREAD

**Issue by ssashok10** [kekeh/mydatepicker#97]
I am using [selDate] to set the initial date and it works fine. However, i am in a need of resting the date at run time. I have tried the below,

```
1. I have set the "myDate" value to be the current date which is not working.
    [selDate]="myDate"
```

```
2. I have tried the blow after assigning the [selDate] value and its not working too.
        let copySDatePickerComponent = Object.assign({}, this.datePickerOptions);
        this.datePickerOptions = copyDatePickerComponent;
```

What is the correct way to re-set the date values during run time?

**Comment by kekeh** [comment]
**selDate** is a string value and it is own attribute. you can do as follows:

In **dateChanged** callback set value to **this.myDate** every time when the date changes like below:
```javascript
onDateChanged(event:any) {
         ....
         this.myDate = event.formatted;
}
```
Then you can set new value to **selDate** like below:

```javascript
    // Clear the date
    this.myDate = '';

    // Or set new date for example
    this.myDate = '29.11.2016';
```

**Comment by windmaomao** [comment]
I don't understand what is `selDate`, because if we have two-way binding, then why the date cannot automatically fire this onDateChange event like the rest of form input. 

What is the purpose of having a `selDate` at the first place?
