### ISSUE TITLE
Expanded language support

### ISSUE THREAD

**Issue by alex-i-e** [kekeh/mydatepicker#98]
Hi,
How can add new language  for LocaleService (expand current language list) ?

**Comment by kekeh** [comment]
At first you fork the mydatepicker repository.

Then add locale to LocaleService and create a pull request. Github instructions: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by alex-i-e** [comment]
yes, please, 
can you add this settings, if I clear understand into locale.service:
  "de": {
            dayLabels: {su: "So", mo: "Mo", tu: "Di", we: "Mi", th: "Do", fr: "Fr", sa: "Sa"},
            monthLabels: { 1: "Jan", 2: "Feb", 3: "Mär", 4: "Apr", 5: "Mai", 6: "Jun", 7: "Jul", 8: "Aug", 9: "Sep", 10: "Okt", 11: "Nov", 12: "Dez" },
            dateFormat: "dd.mm.yyyy",
            todayBtnTxt: "Heute",
            firstDayOfWeek: "mo",
            sunHighlight: true
        }

thx a lot!

**Comment by kekeh** [comment]
Thanks. You can now check from here: http://kekeh.github.io/mydatepicker/

Select **de** locale from inline mode date picker.
