### ISSUE TITLE
Wrong month opens in inline mode

### ISSUE THREAD

**Issue by DarkXaHTeP** [kekeh/mydatepicker#99]
I tried to use datepicker in my project and looks like that in inline mode it always opens on the month where today date is, even when I set [selDate] which is not an expected behavior

Steps to reproduce:
1)set inline: true in datepicker options
2)set [selDate] attribute to some date in year 2017
3)open page with datepicker
4)observe that datepicker is opened on November 2016 and date is not selected.

I also took a look at the code and found out that in ngOnChanges method you are accessing this.selectedDate when processing options before it is set. Maybe this information will help

**Comment by kekeh** [comment]
Thanks! I fixed it in version 1.0.22.

**Comment by DarkXaHTeP** [comment]
Thank you! I'm impressed with the speed :)
